local _G = GLOBAL
local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.Archery= "弓箭"
STRINGS.TABS.Archery = "弓箭"

GLOBAL.STRINGS.ACTIONS["ARMCROSSBOW"] = {
	XBOW = "武装弩 ",
	MUSKET = "重新装填步枪",
}
GLOBAL.STRINGS.ACTIONS.CHANGEARROWTYPE = "更改要使用的类型"
GLOBAL.STRINGS.ACTIONS.TRANSFERCHARGETOPROJECTILE= "给一发子弹充电"

STRINGS.NAMES.ARROW_CARVER = "箭头制造工具"
STRINGS.RECIPE_DESC.ARROW_CARVER = "用来制作箭头。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARROW_CARVER = "我可以用合适的东西做一些箭头。"

STRINGS.NAMES.BOW = "木弓"
STRINGS.RECIPE_DESC.BOW = "使用带B的箭头"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOW = "我以前是个好射手...直到我的膝盖中了一箭。"

STRINGS.NAMES.QUIVER = "箭筒"
STRINGS.RECIPE_DESC.QUIVER = "储存你的箭！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.QUIVER = "有了这些东西，我会看起来像个严肃的弓箭手。"

STRINGS.NAMES.CROSSBOW = "弩"
STRINGS.RECIPE_DESC.CROSSBOW = "装备/右键图标上弦/用带X的箭头"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROSSBOW = "这东西比我还大。"

STRINGS.NAMES.MAGICBOW = "魔弓"
STRINGS.RECIPE_DESC.MAGICBOW = "就像仙女尾巴一样。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAGICBOW = "我预计很快就会有一只放屁的独角兽。"

STRINGS.NAMES.MUSKET = "步枪"
STRINGS.RECIPE_DESC.MUSKET = "装备/右键图标上膛/需要步枪子弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSKET = "我是第五个火枪手吗？"

STRINGS.NAMES.ARROW = "普通弓箭头"
STRINGS.RECIPE_DESC.ARROW = "不要徒手扔。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARROW = "可能最好和蝴蝶结一起使用..."

STRINGS.NAMES.GOLDARROW = "黄金弓箭头"
STRINGS.RECIPE_DESC.GOLDARROW = "有风格的狩猎。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDARROW = "我相信我能找到更好的方法..."

STRINGS.NAMES.MOONSTONEARROW = "月岩弓箭头"
STRINGS.RECIPE_DESC.MOONSTONEARROW = "昂贵但高效。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONSTONEARROW = "锋利闪亮！"

STRINGS.NAMES.FIREARROW = "火焰弓箭头"
STRINGS.RECIPE_DESC.FIREARROW = "最好小心点。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIREARROW = "我应该避免在营地中间使用它..."

STRINGS.NAMES.ICEARROW = "寒冰弓箭头"
STRINGS.RECIPE_DESC.ICEARROW = "保持冷静。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEARROW = "我应该把它放在冰箱里吗？"

STRINGS.NAMES.THUNDERARROW = "闪电弓箭头"
STRINGS.RECIPE_DESC.THUNDERARROW = "暴风雨就要来了。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.THUNDERARROW = "加号上的红线..."

STRINGS.NAMES.DISCHARGEDTHUNDERARROW = "发射雷箭"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DISCHARGEDTHUNDERARROW = "它看起来不再活跃了。"

STRINGS.NAMES.BOLT = "普通弩箭头"
STRINGS.RECIPE_DESC.BOLT = "不是牙签。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOLT = "这么大武器的小弹丸..."

STRINGS.NAMES.POISONBOLT = "剧毒弩箭头"
STRINGS.RECIPE_DESC.POISONBOLT = "用砒霜烹制。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POISONBOLT = "有必要这么丑吗？ "

STRINGS.NAMES.EXPLOSIVEBOLT = "爆炸弩箭头"
STRINGS.RECIPE_DESC.EXPLOSIVEBOLT = "不要直接使用。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EXPLOSIVEBOLT = "这真的是个好主意吗？ "

STRINGS.NAMES.MUSKET_BULLET = "步枪子弹 "
STRINGS.RECIPE_DESC.MUSKET_BULLET = "我们去猎鹿吧。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSKET_BULLET = "看起来像弹珠 "

STRINGS.NAMES.Z_FIREFLIESBALL = "萤火虫球"
STRINGS.RECIPE_DESC.Z_FIREFLIESBALL = "魔弓的能量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.Z_FIREFLIESBALL = "它可能对某些东西有用。 不要问我什么。"

STRINGS.NAMES.Z_BLUEGOOP = "蓝色粘液"
STRINGS.RECIPE_DESC.Z_BLUEGOOP = "魔弓的能量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.Z_BLUEGOOP = "看起来很恶心。 "