local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.CACTUSMACE = "仙人掌棒"
STRINGS.RECIPE_DESC.CACTUSMACE = "伤害68.5/无耐久/慢慢t腐烂"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CACTUSMACE = "一只尖棒。"

STRINGS.NAMES.DARK_AXE = "暗黑斧"
STRINGS.RECIPE_DESC.DARK_AXE = "快速砍树/加快理智下降"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DARK_AXE = "那是一把可怕的斧头。"

STRINGS.NAMES.DARK_PICKAXE = "暗黑镐"
STRINGS.RECIPE_DESC.DARK_PICKAXE = "快速挖矿/加快理智下降"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DARK_PICKAXE = "那是一把可怕的镐。"

STRINGS.NAMES.EWECUSHAT = "骑士头盔"
STRINGS.RECIPE_DESC.EWECUSHAT = "90%防御/1000耐久/20%防水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.EWECUSHAT = "耐用的头盔。"

STRINGS.NAMES.FLYSWATTER = "苍蝇拍"
STRINGS.RECIPE_DESC.FLYSWATTER = "拍打那些虫子。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FLYSWATTER = "它非常适合杀死小昆虫。"

STRINGS.NAMES.FRYINGPAN = "平底锅"
STRINGS.RECIPE_DESC.FRYINGPAN = "42.5伤害/320耐久"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRYINGPAN = "这真的很难。"

STRINGS.NAMES.GROWTHSTAFF = "成长之杖"
STRINGS.RECIPE_DESC.GROWTHSTAFF = "催熟周围植物。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GROWTHSTAFF = "它散发着能量。"

STRINGS.NAMES.HOLLOWHAT = "碎骨帽"
STRINGS.RECIPE_DESC.HOLLOWHAT = "60%增速/280s耐久/加快理智下降"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOLLOWHAT = "一个诡异的头骨。"

STRINGS.NAMES.LIGHTNECKLACE = "光明项链"
STRINGS.RECIPE_DESC.LIGHTNECKLACE = "提供照明"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIGHTNECKLACE = "它的发光很有帮助。"

STRINGS.NAMES.SPARTAHELMUT = "黄金头盔"
STRINGS.RECIPE_DESC.SPARTAHELMUT = "70%防御/450耐久/20%防水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPARTAHELMUT = "它的设计似乎很古老。"

STRINGS.NAMES.SPARTASWURD = "利刃"
STRINGS.RECIPE_DESC.SPARTASWURD = "51伤害/110耐久"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPARTASWURD = "它忠于它的名字。"

STRINGS.NAMES.SUMMERBANDANA = "夏季头巾"
STRINGS.RECIPE_DESC.SUMMERBANDANA = "降温！！！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUMMERBANDANA = "它可以让热量远离一点。"

STRINGS.NAMES.WOODENMACE = "木棒槌"
STRINGS.RECIPE_DESC.WOODENMACE = "34伤害/35耐久/前期好用"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WOODENMACE = "这是一只木头做的棒子。"

STRINGS.NAMES.ARMORMOSQUITO = "防蚊服"
STRINGS.RECIPE_DESC.ARMORMOSQUITO = "60%防御/400耐久/防蚊子攻击"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORMOSQUITO = "闻起来像血。"

STRINGS.NAMES.BARONSUIT = "男爵服"
STRINGS.RECIPE_DESC.BARONSUIT = "快速回复理智，略微保暖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BARONSUIT = "我是现代少将的典范。"

STRINGS.NAMES.BIRCHNUTHAT = "尖刺头盔"
STRINGS.RECIPE_DESC.BIRCHNUTHAT = "50%防御/225耐久/20%防水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BIRCHNUTHAT = "哎哟，小心那些钉子！"