local STRINGS = GLOBAL.STRINGS

---------------------------------------神奇魔药---------------------------------------

STRINGS.NAMES.Alchemy= "炼药"
STRINGS.TABS.Alchemy = "炼药"

STRINGS.NAMES.ALCHEMYSTATION = "炼药坩埚"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALCHEMYSTATION = "我可以在这里制作药水。"
STRINGS.RECIPE_DESC.ALCHEMYSTATION = "让我们自制一些魔法吧。"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.ALCHEMYSTATION = "烧死女巫！！"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.ALCHEMYSTATION = "沃尔夫冈不能在那里做饭。"
STRINGS.CHARACTERS.WENDY.DESCRIBE.ALCHEMYSTATION = "我可以做饮料来延年益寿。"
STRINGS.CHARACTERS.WX78.DESCRIBE.ALCHEMYSTATION = "我不需要提高自己"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.ALCHEMYSTATION = "有多少奇怪的物质会有这个？"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.ALCHEMYSTATION = "这看起来不像是一个明智的行为，嗯！"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.ALCHEMYSTATION = "这不是我的魔法！"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.ALCHEMYSTATION = "女巫用这个！"
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.ALCHEMYSTATION = "我们可以用它们来提高性能！"

STRINGS.NAMES.HEALTHPOTION = "生命药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HEALTHPOTION = "闻起来像止咳糖浆。"
STRINGS.RECIPE_DESC.HEALTHPOTION = "回复生命值"

STRINGS.NAMES.SANITYPOTION = "精神药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANITYPOTION = "这就是我想象的液化大脑的味道。"
STRINGS.RECIPE_DESC.SANITYPOTION = "回复理智"

STRINGS.NAMES.FIREPOTION = "火焰药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FIREPOTION = "感觉就像一条温暖的毯子。"
STRINGS.RECIPE_DESC.FIREPOTION = "提升温度,一段时间内攻击你的敌人有几率被点燃"	

STRINGS.NAMES.ICEPOTION = "寒冰药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEPOTION = "真正的冰镇饮料。"
STRINGS.RECIPE_DESC.ICEPOTION = "降低温度,一段时间内攻击你的敌人有几率被冰冻"

STRINGS.NAMES.SPEEDPOTION = "速度药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPEEDPOTION = "我的味蕾跟不上这个。"
STRINGS.RECIPE_DESC.SPEEDPOTION = "增加移速."

STRINGS.NAMES.HUNGERPOTION = "饥饿药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HUNGERPOTION = "我肯定这只是罐子里的汤。"
STRINGS.RECIPE_DESC.HUNGERPOTION = "在旅途中品尝美味佳肴。"

STRINGS.NAMES.INSANITYPOTION = "疯狂药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.INSANITYPOTION = "闻起来是个坏主意。"
STRINGS.RECIPE_DESC.INSANITYPOTION = "减少理智."

STRINGS.NAMES.LIGHTPOTION = "光明药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIGHTPOTION = "我能尝到太阳的力量。"
STRINGS.RECIPE_DESC.LIGHTPOTION = "一段时间内你可发出光芒."

STRINGS.NAMES.POWERPOTION = "力量药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POWERPOTION = "闻起来又热又汗。"
STRINGS.RECIPE_DESC.POWERPOTION = "一段时间内增加攻击力."

STRINGS.NAMES.ARMORPOTION = "防御药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORPOTION = "有金属的味道。"
STRINGS.RECIPE_DESC.ARMORPOTION = "一段时间内增加防御力."

STRINGS.NAMES.RANDOMPOTION = "神秘药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RANDOMPOTION = "多么令人困惑的香气啊。"
STRINGS.RECIPE_DESC.RANDOMPOTION = "来赌一下呗."

STRINGS.NAMES.BOLTPOTION = "闪电药水"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BOLTPOTION = "这真是令人震惊。"
STRINGS.RECIPE_DESC.BOLTPOTION = "电!"

---------------------------------------炸药包---------------------------------------

STRINGS.NAMES.SMALLBOMB = "小型炸弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SMALLBOMB = "一个小炸药。"
STRINGS.RECIPE_DESC.SMALLBOMB = "75伤害 / 不会点燃物品."

STRINGS.NAMES.LARGEBOMB = "大型炸弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LARGEBOMB = "一定要小心这个。"
STRINGS.RECIPE_DESC.LARGEBOMB = "200伤害 / 爆炸范围内引燃物品."

STRINGS.NAMES.SPIKEBOMB = "孢子炸弹 "
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPIKEBOMB = "有点难把握。"
STRINGS.RECIPE_DESC.SPIKEBOMB = "50 伤害 / 制造持续60s的孢子云."

STRINGS.NAMES.SHADOWBOMB = "暗影炸弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWBOMB = "这个会让你大吃一惊。"
STRINGS.RECIPE_DESC.SHADOWBOMB = "100 伤害 / 不会点燃物品."

STRINGS.NAMES.ICEBOMB = "寒冰炸弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ICEBOMB = "这是一个爆炸性的冰块。 "
STRINGS.RECIPE_DESC.ICEBOMB = "50伤害 / 直接冰冻目标."

STRINGS.NAMES.VOLTBOMB = "伏特炸弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.VOLTBOMB = "多么令人震惊的小炸弹。 "
STRINGS.RECIPE_DESC.VOLTBOMB = "50 伤害 / 对潮湿目标 175 伤害."


STRINGS.NAMES.STICKYBOMB = "粘性炸弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STICKYBOMB = "令人作呕但有效的炸弹。"
STRINGS.RECIPE_DESC.STICKYBOMB = "100 伤害 / 在 4 秒内减缓目标."