local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.LARGECHEST = "黄金箱"
STRINGS.RECIPE_DESC.LARGECHEST = "一个5x5的大箱子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LARGECHEST = "看起来真漂亮！"

STRINGS.NAMES.LARGEICEBOX = "大冰箱"
STRINGS.RECIPE_DESC.LARGEICEBOX = "5x5的大冰箱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LARGEICEBOX = "我已经利用了寒冷的力量！"