local _G = GLOBAL
local STRINGS = GLOBAL.STRINGS

GLOBAL.STRINGS.NAMES.SCYTHE = "镰刀"
GLOBAL.STRINGS.RECIPE_DESC.SCYTHE = "快速收割某些植物"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCYTHE = "快速收割某些植物"
            
GLOBAL.STRINGS.NAMES.SCYTHE_GOLDEN = "黄金镰刀"        
GLOBAL.STRINGS.RECIPE_DESC.SCYTHE_GOLDEN = "比普通镰刀更加耐用"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCYTHE_GOLDEN = "比普通镰刀更加耐用"