local _G = GLOBAL
local STRINGS = GLOBAL.STRINGS

GLOBAL.STRINGS.NAMES.ALWAYSONTIKITORCH = "永恒火炬"
STRINGS.RECIPE_DESC.ALWAYSONTIKITORCH = "照亮我的路宝贝！"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALWAYSONTIKITORCH = "岛上的众神保佑我。"

_G.STRINGS.NAMES.SEEDOMATIC_ITEM = "自动播种机"
_G.STRINGS.NAMES.SEEDOMATIC = "自动播种机"
_G.STRINGS.RECIPE_DESC.SEEDOMATIC_ITEM = "加入种子自动播种3x3范围内土地。"
_G.STRINGS.RECIPE_DESC.SEEDOMATIC = "加入种子自动播种3x3范围内土地。"
_G.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEEDOMATIC_ITEM = "这是一台自动播种机！"
_G.STRINGS.CHARACTERS.GENERIC.DESCRIBE.SEEDOMATIC = "这是一台自动播种机！"

STRINGS.NAMES.SHELTER = "木制雨棚"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHELTER = "树荫，甜蜜的树荫。"
STRINGS.CHARACTERS.WORTOX.DESCRIBE.SHELTER = "他们也不喜欢小鬼的味道。"
STRINGS.CHARACTERS.WALTER.DESCRIBE.SHELTER = "我也想要一条毛巾！"
STRINGS.CHARACTERS.WINONA.DESCRIBE.SHELTER = "这就是我要求的！"
STRINGS.CHARACTERS.WURT.DESCRIBE.SHELTER = "你为什么不喜欢水？"
STRINGS.CHARACTERS.WILLOW.DESCRIBE.SHELTER = "把元素放在外面，但它会很容易燃烧的。"
STRINGS.CHARACTERS.WOLFGANG.DESCRIBE.SHELTER = "伟大的沃尔夫冈值得舒适。"
STRINGS.CHARACTERS.WENDY.DESCRIBE.SHELTER = "欢迎呼吸。"
STRINGS.CHARACTERS.WX78.DESCRIBE.SHELTER = "已获得Thatch屋顶保护"
STRINGS.CHARACTERS.WICKERBOTTOM.DESCRIBE.SHELTER = "从太阳无情的纱布中解脱出来。"
STRINGS.CHARACTERS.WOODIE.DESCRIBE.SHELTER = "最好的庇护所一个木匠可以要求。"
STRINGS.CHARACTERS.WAXWELL.DESCRIBE.SHELTER = "Phew."
STRINGS.CHARACTERS.WATHGRITHR.DESCRIBE.SHELTER = "让雨停在我的头盔上"
STRINGS.CHARACTERS.WEBBER.DESCRIBE.SHELTER = "几乎像蜘蛛窝一样好"
STRINGS.CHARACTERS.WARLY.DESCRIBE.SHELTER = "伟大的室内！"
STRINGS.CHARACTERS.WORMWOOD.DESCRIBE.SHELTER = "朋友之家"
STRINGS.RECIPE_DESC.SHELTER = "可以躲避大部分的雨水"

STRINGS.NAMES.ICEMAKER = "制冰机IM3000"
STRINGS.RECIPE_DESC.ICEMAKER = "一台可以制造冰的机器"

GLOBAL.STRINGS.NAMES.CELLAR = "风暴地窖"
STRINGS.RECIPE_DESC.CELLAR = "80格大箱子。就像我家的地下室一样，到处都是垃圾 "
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.CELLAR = "我喜欢"

GLOBAL.STRINGS.NAMES.ROPE_BRIDGE_ITEM = "索桥"
GLOBAL.STRINGS.RECIPE_DESC.ROPE_BRIDGE_ITEM = "鼠标置于河对岸右键搭桥，需要木板与绳子"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROPE_BRIDGE_ITEM = "可能会出什么问题？"
GLOBAL.STRINGS.NAMES.ROPE_BRIDGE_STUMP = "索桥"
GLOBAL.STRINGS.RECIPE_DESC.ROPE_BRIDGE_STUMP = "鼠标置于河对岸右键搭桥，需要木板与绳子"
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROPE_BRIDGE_STUMP = "可能会出什么问题？"
_G.STRINGS.ACTIONS.DROP.ROPE_BRIDGE="放置索桥"
_G.STRINGS.ACTIONS.DEPLOY.ROPE_BRIDGE="放置索桥"
_G.STRINGS.ACTIONS.TOGGLE_DEPLOY_MODE.ROPE_BRIDGE="放置索桥"


GLOBAL.STRINGS.NAMES.PATH_LIGHT = "小路灯"
STRINGS.RECIPE_DESC.PATH_LIGHT = "照亮你前进的道路."
GLOBAL.STRINGS.CHARACTERS.GENERIC.DESCRIBE.PATH_LIGHT = "这是一盏灯"

