local _G = GLOBAL
local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.BLOODBAG = "血包"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOODBAG = "我想知道这是不是我的血型..."
STRINGS.CHARACTERS.WX78.DESCRIBE.BLOODBAG = "我应该不需要这个."
STRINGS.CHARACTERS.WENDY.DESCRIBE.BLOODBAG = "如果我姐姐有这个..."
STRINGS.CHARACTERS.WILLOW.DESCRIBE.BLOODBAG = "我想知道这是否会燃烧..."
STRINGS.RECIPE_DESC.BLOODBAG = "一个装满血的袋子，可恢复100血"