local STRINGS = GLOBAL.STRINGS

STRINGS.NAMES.GOLDSWORD = "黄金剑"
STRINGS.RECIPE_DESC.GOLDSWORD = "伤害47，耐久125."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GOLDSWORD = "哦，又尖又尖！ 但最重要的是，它是黄金制成的 "
STRINGS.NAMES.STONESWORD = "普通剑"
STRINGS.RECIPE_DESC.STONESWORD = "伤害40，耐久75."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STONESWORD = "哦，又尖又尖！ "
