local STRINGS = GLOBAL.STRINGS


STRINGS.NAMES.TURF_TEST = "一块试验草皮"

--Carpet
STRINGS.NAMES.TURF_CARPETBLACKFUR = "熊皮地毯"
STRINGS.RECIPE_DESC.TURF_CARPETBLACKFUR = "制作一卷熊皮地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETBLACKFUR = "用怪物的毛皮制成的温暖舒适的地毯。"

STRINGS.NAMES.TURF_CARPETBLUE = "蓝色地毯"
STRINGS.RECIPE_DESC.TURF_CARPETBLUE = "制作一卷蓝色地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETBLUE = "和你一样忧郁。"

STRINGS.NAMES.TURF_CARPETCAMO = "迷彩地毯"
STRINGS.RECIPE_DESC.TURF_CARPETCAMO = "制作一卷迷彩地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETCAMO = "我打赌你没看到这地毯。"

STRINGS.NAMES.TURF_CARPETFUR = "毛皮地毯"
STRINGS.RECIPE_DESC.TURF_CARPETFUR = "制作一卷毛皮地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETFUR = "Warm, snuggly, smelly."

STRINGS.NAMES.TURF_CARPETPINK = "粉色地毯"
STRINGS.RECIPE_DESC.TURF_CARPETPINK = "制作一卷粉色地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETPINK = "Pink carpet? As if!"

STRINGS.NAMES.TURF_CARPETPURPLE = "紫色地毯"
STRINGS.RECIPE_DESC.TURF_CARPETPURPLE = "制作一卷紫色地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETPURPLE = "Purple is a royal color and also the color of this carpet."

STRINGS.NAMES.TURF_CARPETRED = "红色地毯"
STRINGS.RECIPE_DESC.TURF_CARPETRED = "制作一卷红地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETRED = "Wash the white rug near the berries they said, it will be fine they told me..."

STRINGS.NAMES.TURF_CARPETRED2 = "钻石地毯"
STRINGS.RECIPE_DESC.TURF_CARPETRED2 = "制作一卷红钻石地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETRED2 = "Shine bright like a blood diamond."

STRINGS.NAMES.TURF_CARPETTD = "炫彩地毯"
STRINGS.RECIPE_DESC.TURF_CARPETTD = "制作一卷炫彩地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETTD = "This carpet man, it like... whoa..."

STRINGS.NAMES.TURF_CARPETWIFI = "无线地毯"
STRINGS.RECIPE_DESC.TURF_CARPETWIFI = "制作一卷无线地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_CARPETWIFI = "Can you feel me now? Good."
--Nature
STRINGS.NAMES.TURF_NATUREASTROTURF = "人造草坪"
STRINGS.RECIPE_DESC.TURF_NATUREASTROTURF = "制作一卷人造草皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_NATUREASTROTURF = "Grass without the hassle!"

STRINGS.NAMES.TURF_NATUREDESERT = "沙漠草坪"
STRINGS.RECIPE_DESC.TURF_NATUREDESERT = "制作一卷沙漠草皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_NATUREDESERT = "Your own piece of dry, cracked, barren地皮"
--Rock
STRINGS.NAMES.TURF_ROCKBLACKTOP = "柏油草坪"
STRINGS.RECIPE_DESC.TURF_ROCKBLACKTOP = "制作一卷黑顶草皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ROCKBLACKTOP = "Blacktop, endless and pointless opportunities."

STRINGS.NAMES.TURF_ROCKGIRAFFE = "长颈鹿岩石草坪"
STRINGS.RECIPE_DESC.TURF_ROCKGIRAFFE = "制作一卷长颈鹿岩石草坪."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ROCKGIRAFFE = "Made from freshly squeezed giraffe."

STRINGS.NAMES.TURF_ROCKMOON = "月岩草坪"
STRINGS.RECIPE_DESC.TURF_ROCKMOON = "制作一卷月岩草坪."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ROCKMOON = "Moon Rock turf phoooneee hooomeeee."

STRINGS.NAMES.TURF_ROCKYELLOWBRICK = "黄砖草坪"
STRINGS.RECIPE_DESC.TURF_ROCKYELLOWBRICK = "制作一卷黄砖草坪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ROCKYELLOWBRICK = "Just follow it."
--Tile
STRINGS.NAMES.TURF_TILECHECKERBOARD = "棋盘瓷砖"
STRINGS.RECIPE_DESC.TURF_TILECHECKERBOARD = "制作一卷棋盘瓷砖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TILECHECKERBOARD = "Checkmate."

STRINGS.NAMES.TURF_TILEFROSTY = "冰霜瓷砖"
STRINGS.RECIPE_DESC.TURF_TILEFROSTY = "制作一卷冰霜瓷砖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TILEFROSTY = "Do you wanna build some tile?"

STRINGS.NAMES.TURF_TILESQUARES = "方形瓷砖"
STRINGS.RECIPE_DESC.TURF_TILESQUARES = "制作一卷方形瓷砖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TILESQUARES = "Such tile, much squares."
--Wood
STRINGS.NAMES.TURF_WOODCHERRY = "樱木地板"
STRINGS.RECIPE_DESC.TURF_WOODCHERRY = "制作一卷樱木地板"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_WOODCHERRY = "Where do you find cherries anyway?"

STRINGS.NAMES.TURF_WOODDARK = "深木地板"
STRINGS.RECIPE_DESC.TURF_WOODDARK = "制作一卷深木地板"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_WOODDARK = "Charlie's favorite color."

STRINGS.NAMES.TURF_WOODPINE = "松木地板"
STRINGS.RECIPE_DESC.TURF_WOODPINE = "制作一卷松木地板"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_WOODPINE = "Flooring that makes pinecones useful."
-- Spikes
STRINGS.NAMES.TURF_SPIKES = "尖刺草坪"
STRINGS.RECIPE_DESC.TURF_SPIKES = "制作一卷松木地板尖刺草坪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_SPIKES = "Spikes that slow you down."



STRINGS.RECIPE_DESC.TURF_FOREST = "制造一卷森林地皮"
STRINGS.RECIPE_DESC.TURF_DECIDUOUS = "制造一卷落叶林地皮"
STRINGS.RECIPE_DESC.TURF_GRASS = "制造一卷长草地皮"
STRINGS.RECIPE_DESC.TURF_SAVANNA = "制造一卷热带草原地皮"
STRINGS.RECIPE_DESC.TURF_DESERTDIRT = "制造一卷沙土地皮"
STRINGS.RECIPE_DESC.TURF_MARSH = "制造一卷菌类地皮"
STRINGS.RECIPE_DESC.TURF_FUNGUS = "制造一卷蓝色菌类地皮"
STRINGS.RECIPE_DESC.TURF_FUNGUS_RED = "制造一卷红色菌类地皮"
STRINGS.RECIPE_DESC.TURF_FUNGUS_GREEN = "制造一卷绿色菌类地皮"
STRINGS.RECIPE_DESC.TURF_MUD = "制造一卷泥泞地皮"
STRINGS.RECIPE_DESC.TURF_SINKHOLE = "制造一卷泥泞地皮"
STRINGS.RECIPE_DESC.TURF_ROCKY = "制造一卷岩石地皮"
STRINGS.RECIPE_DESC.TURF_CAVE = "制造一卷鸟粪地皮"
STRINGS.RECIPE_DESC.TURF_UNDERROCK = "制造一卷洞穴石地皮"