STRINGS.CARNEYTAB = "制造"

STRINGS.NAMES.WHITEBERET = "白色贝雷帽"
STRINGS.RECIPE_DESC.WHITEBERET = "出门不能忘记戴帽子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WHITEBERET = "涤纶的质感，不像是手工纺织品"

STRINGS.NAMES.ANGELCRYSTAL = "天使水晶"
STRINGS.RECIPE_DESC.ANGELCRYSTAL = "蕴含影响心智的能量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANGELCRYSTAL = "一下子开窍了"

STRINGS.NAMES.WINDYKNIFE = "微风短剑"
STRINGS.RECIPE_DESC.WINDYKNIFE = "顺手的短剑怎么用都顺手"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WINDYKNIFE = "精巧得难以置信"

STRINGS.NAMES.NYLON = "尼龙背包"
STRINGS.RECIPE_DESC.NYLON = "加强了压缩带的防水型内框架背包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.NYLON = "很大却很轻，非常厚实"

STRINGS.CHARACTER_TITLES.carney = "卡尼猫"
STRINGS.CHARACTER_NAMES.carney = "Carney"
STRINGS.CHARACTER_DESCRIPTIONS.carney = "*灵活的战斗技能\n*随着时间逐渐成长\n*喜欢一直在旅行"
STRINGS.CHARACTER_QUOTES.carney = "正在到处旅行着"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.carney = 
{
	GENERIC = "这是谁!",
	ATTACKER = "打啊",
	MURDERER = "谋杀啊!",
	REVIVER = "啥玩意儿?!",
	GHOST = "我是鬼",
}

STRINGS.NAMES.carney = "Carney"

STRINGS.CARNEYSTRINGS={
[1] = "等级提升啦!",
}

STRINGS.CARNEYUI={
[1] = "玩法说明",
}