local speech = 
{
	DESCRIBE={},ACTIONFAIL={},COMBAT_QUIT={},BATTLECRY={},ANNOUNCE_EAT={},EAT_FOOD={},
	ANNOUNCE_MESSAGEBOTTLE={},ANNOUNCE_PICKPOOP={},ANNOUNCE_DEHUMID={},ANNOUNCE_TOO_HUMID={},
    ANNOUNCE_PUGALISK_INVULNERABLE={},
}
for _,v in pairs({"FERTILIZE","USEDOOR","DRAW","COOK","BUILD","GIVE","SHOP","MOUNT","REPAIRBOAT","CHANGEIN","SADDLE","TEACH","PICKUP","RUMMAGE","WRITE","SHAVE","STORE",})do
    speech.ACTIONFAIL[v] = {}
end
for _,v in pairs({"EVERGREEN_SPARSE","CROW","BLUE_MUSHROOM","DIVININGRODBASE","CAMPFIRE","CRAB","GRASS","DECIDUOUSTREE","GEMSOCKET","FISH_FARM","BUTTERFLY","GREEN_MUSHROOM","COLDFIRE","FIREFLIES","COOKPOT","ASH","BAMBOOTREE","BUSH_VINE","FIRESUPPRESSOR","CAVE_ENTRANCE_OPEN","CAVE_EXIT","BERRYBUSH","COCONADE","BIRDCAGE","GLOMMERFLOWER","DIVININGROD","DEPLETED_GRASS","FROG","COCONUT","BEEBOX","FIREPIT","CAVE_ENTRANCE","COLDFIREPIT","COFFEEBUSH","BEE","EVERGREEN","FARMPLOT","CATCOONDEN","CHESTER_EYEBONE","ACORN","BEEFALO","CACTUS","COMPASS",	"MERMHOUSE","MEATRACK","MUSHTREE_TALL","MARSH_BUSH","MANDRAKE","KILLERBEE","HEATROCK","MOUND","MUSHTREE_MEDIUM","JUNGLETREE","LAVAE_PET","LAVAE_EGG_CRACKED","MUSSEL_FARM","LIGHTNING_ROD","INSANITYROCK","NIGHTMARE_TIMEPIECE","JUNGLETREESEED","ICEMAKER","MOSQUITO","LAVASPIT","MARSH_TREE","LIMPETROCK","LAVAE_EGG","LIGHTNINGGOAT","LOG","MERMHEAD","MOLE","HOMESIGN","MUSHTREE_SMALL",	"PINECONE","RABBITHOUSE","SAPLING","RAINOMETER","SPIDER","SEA_CHIMINEA","ROBIN_WINTER","SEA_YARD","TRAWLNETDROPPED","RESURRECTIONSTATUE","RED_MUSHROOM","ROCK_ICE","TEENBIRD","SUNKEN_BOAT","TENT","TREASURECHEST","PLANT_NORMAL","SHARKITTENSPAWNER","PIRATIHATITATOR","RABBIT","SNAKEDEN","SIESTAHUT","TALLBIRDNEST","SMALLBIRD","REEDS","STATUEGLOMMER","PALMTREE","RESEARCHLAB4","OBSIDIANFIREPIT","RELIC","ROCK_LIGHT","SAND_CASTLE","PIGHOUSE","ROBIN","RESEARCHLAB2","RESEARCHLAB","TALLBIRDEGG_CRACKED","SPIDER_WARRIOR","SANITYROCK","PIGMAN","TELEPORTATO_BASE","TELEBASE","TAR_EXTRACTOR","RABBITHOLE","PIGHEAD","RESEARCHLAB3",	"WALRUS_CAMP","WINTEROMETER","WORM","WALL_WOOD","VOLCANO_ALTAR","WORMHOLE","WALL_HAY",})do
	speech.DESCRIBE[v] = {}
end
for _,v in pairs({"RELIC_4","PIGMAN_MAYOR","PIGMAN_HATMAKER","PIGMAN_MINER","PLAYERHOUSE_CITY","PARROT_BLUE","PIGMAN_FARMER","PIG_SHOP_GENERAL","PIGMAN_BEAUTICIAN","PIG_SHOP_PRODUCE","RABID_BEETLE","PEEKHEN","PIGEON","PIGHOUSE_CITY","PIGMAN_BANKER","RELIC_5","PIG_SHOP_ARCANE","PIGMAN_STOREOWNER","PIGHOUSE_MINE","VAMPIREBAT","RELIC_3","RELIC_2","RELIC_1","PIKO","PEAGAWK","SCORPION","SNAPDRAGON","PIG_RUINS_ENTRANCE","RAINFORESTTREE","SPIDER_MONKEY","PIG_SHOP_ACADEMY","PIG_SHOP_HATSHOP","PIG_SHOP_HOOFSPA","PIG_SHOP_FLORIST","RECONSTRUCTION_PROJECT","PIGMAN_HUNTER","PIGMAN_PROFESSOR","PIGMAN_ERUDITE","PIGMAN_FLORIST","PIGMAN_MECHANIC","PIGMAN_COLLECTOR","ZEB","WARDROBE","PIG_SHOP_WEAPONS","PIGMAN_ROYALGUARD","PIGHOUSE_FARM","PIG_GUARD_TOWER","CHICKEN","DUNGBEETLE","MINISIGN","CITY_LAMP","LAWNORNAMENT","NETTLE","HEDGE","BILL","KINGFISHER","MEAN_FLYTRAP","ADULT_FLYTRAP","GLOWFLY","DUNGPILE","ANTMAN","GRASS_TALL",})do
    speech.DESCRIBE[v] = {}
end

speech.ANNOUNCE_CANFIX = "只要研究一下说明书……"
speech.ANNOUNCE_HAYFEVER = "呼吸困难……不，不是因为心脏病"
speech.ANNOUNCE_CRAFTING_FAIL = "下次不会跟丢了。"
speech.ANNOUNCE_ADVENTUREFAIL = "回到过去再来一次如何？"
speech.ANNOUCE_OTHERWORLD_DEED = "我的房子在小镇里,不在这儿."
speech.ANNOUNCE_QUAKE = "像魔女之夜一样的灾难。"
speech.ANNOUNCE_CHARLIE = "是使魔吗？" --查理即将攻击
speech.ANNOUNCE_TURFTOOHARD = "这块地太硬,撬不起来."
speech.ACTIONFAIL.FERTILIZE.WRONGDIRT = "我觉得它并不喜欢这个肥料。"
speech.ACTIONFAIL.USEDOOR.GENERIC = "它打不开."
speech.ACTIONFAIL.USEDOOR.LOCKED = "它锁住了."
speech.ACTIONFAIL.DRAW.NOIMAGE = "缺乏实物啊，哪里会有呢"
speech.ACTIONFAIL.COOK.GENERIC = "哦，我不能。"
speech.ACTIONFAIL.COOK.TOOFAR = "太远了！"
speech.ACTIONFAIL.BUILD.MOUNTED = "我的魔法没有瞬移功能啊"
speech.ACTIONFAIL.GIVE.BUSY = "难以交流吗？"
speech.ACTIONFAIL.GIVE.SLEEPING = "真羡慕你，这么悠闲。"
speech.ACTIONFAIL.GIVE.DEAD = "救不了你吗……"
speech.ACTIONFAIL.SHOP.GENERIC = "我做不到."
speech.ACTIONFAIL.SHOP.CANTPAY = "可恶，有点贵"
speech.ACTIONFAIL.MOUNT.TARGETINCOMBAT = "等牛平复下来再说吧"
speech.ACTIONFAIL.MOUNT.INUSE = "Someone beat me to the saddle!"
speech.ACTIONFAIL.REPAIRBOAT.GENERIC = "站在这里可没法修啊"
speech.ACTIONFAIL.CHANGEIN.GENERIC = "我现在不想改变。"
speech.ACTIONFAIL.CHANGEIN.BURNING = "现在太危险了！"
speech.ACTIONFAIL.SADDLE.TARGETINCOMBAT = "It won't let me do that while it's angry."
speech.ACTIONFAIL.TEACH.KNOWN = "学过了，我还记得。"
speech.ACTIONFAIL.TEACH.CANTLEARN = "我终究学不会啊。"
speech.ACTIONFAIL.PICKUP.GENERIC = "我做不到."
speech.ACTIONFAIL.PICKUP.CANTPAY = "这个轮回是不是该学学赚钱的方法？"
speech.ACTIONFAIL.RUMMAGE.GENERIC = "我不能。"
speech.ACTIONFAIL.WRITE.GENERIC = "不用改了"
speech.ACTIONFAIL.SHAVE.GENERIC = "我不能剃掉！"
speech.ACTIONFAIL.SHAVE.RIDING = "It might be dangerous to shave now"
speech.ACTIONFAIL.SHAVE.AWAKEBEEFALO = "等他睡着了再说"
speech.ACTIONFAIL.SHAVE.NOBITS = "像QB一样，光秃秃的"
speech.ACTIONFAIL.STORE.GENERIC = "该好好整理一番" 
speech.ACTIONFAIL.STORE.NOTALLOWED = "乱放东西会让小圆很头疼的"
speech.ANNOUNCE_BOOMERANG = "使用回旋镖要小心"
speech.ANNOUNCE_NODANGERSLEEP = "现在不是睡觉的时候啊！"
speech.ANNOUNCE_UNIMPLEMENTED = "好，我再等等"
speech.ANNOUNCE_INV_FULL = "我的时之盾都装不进这么多东西"  --身上的物品满了
speech.ACTIONFAIL_GENERIC = "我做不到" 
speech.ANNOUNCE_ACCOMPLISHMENT_DONE = "要是小圆在可以看到我就好了"
speech.ANNOUNCE_DUSK = "今夜，会有魔女出现吗？" --进入黄昏
speech.ANNOUNCE_ENTER_DARK = "太暗了，提高警惕！"  --进入黑暗
speech.ANNOUNCE_WETTER = "小圆……带伞了吗？"  --潮湿（2级）
speech.ANNOUNCE_NODANGERSIESTA = "现在不是偷懒的时候！"
speech.ANNOUCE_BATS = "显然，它并不是真正意义上的使魔"
speech.ANNOUNCE_SOAKED = "好想念小圆的伞啊……" --潮湿（3级）
speech.ANNOUNCE_FREEDOM = "我的命运由自己掌控"
speech.ANNOUNCE_TOOL_SLIP = "握不住了吗"
speech.ANNOUNCE_BOAT_SINKING = "不好，赶快修船！"
speech.ANNOUNCE_MAPWRAP_WARN = "这个世界……有问题！"
speech.ANNOUNCE_RESEARCH = "或许要靠自学来寻找解决方法"
speech.ANNOUNCE_SNEEZE = "阿嚏!"
speech.ANNOUNCE_LIGHTNING_DAMAGE_AVOIDED = "魔女比闪电可怕多了"
speech.ANNOUNCE_WORMS = "似乎有可怕的生物出现了"  --蠕虫袭击
speech.ANNOUNCE_SHARX = "我需要一艘更大的船。。。"
speech.ANNOUNCE_MAPWRAP_LOSECONTROL = "我被关在这片区域里了！"
speech.ANNOUNCE_THORNS = "有刺。"
speech.ANNOUNCE_NOHUNGERSIESTA = "上次偷军火的时候该顺便拿点罐头的"
speech.ANNOUNCE_WHALE_HUNT_LOST_TRAIL_SPRING = "下次一定找到它"
speech.ANNOUNCE_HUNT_LOST_TRAIL_SPRING = "下次不会跟丢了"
speech.ANNOUNCE_HUNGRY = "要是杏子在旁边就好了" --饥饿
speech.ANNOUNCE_LOWRESEARCH = "我从那儿没学到什么"
speech.ANNOUNCE_BOAT_SINKING_IMMINENT = "我不能死在海上！我还要保护小圆！"
speech.EAT_FOOD.TALLBIRDEGG_CRACKED = "这不会也是一只QB吧"   --孵化的高脚鸟蛋
speech.DESCRIBE_MYSTERY = "或许在哪次轮回中见过？"
speech.DESCRIBE_SMOLDERING = "要着火了。"
speech.ANNOUNCE_PICKPOOP[1] = "呃!"
speech.ANNOUNCE_PICKPOOP[2] = "恶心!"
speech.ANNOUNCE_PICKPOOP[3] = "呕!"
speech.ANNOUNCE_PICKPOOP[4] = "我弄到手上了!"
speech.ANNOUNCE_INSUFFICIENTFERTILIZER = "还饿么，植物？"
speech.DESCRIBE_TOODARK = "太暗了，看不清！"
speech.ANNOUNCE_TRAP_WENT_OFF = "喔噗嘶"
speech.ANNOUNCE_WHALE_HUNT_LOST_TRAIL = "我不知道它去了哪里。。。"
speech.DESCRIBE_GENERIC = "它是某种。。东西"  --检查物品描述的缺省值
speech.COMBAT_QUIT.GENERIC = "我肯定让他见识过了！"
speech.COMBAT_QUIT.PREY = "他速度太快了！"
speech.COMBAT_QUIT.PIG = "这次我放他走"
speech.COMBAT_QUIT.SPIDER_WARRIOR = "虽然弱小，不可大意"   --蜘蛛战士
speech.COMBAT_QUIT.SPIDER = "十分弱小的怪物"   --蜘蛛
speech.ANNOUNCE_WAVE_BOOST = "放松一下……"
speech.BATTLECRY.GENERIC = "不可掉以轻心！"
speech.BATTLECRY.PREY = "节约弹药！"
speech.BATTLECRY.PIG = "是一块猪肉，补充点营养吧" --猪人
speech.BATTLECRY.SPIDER_WARRIOR = "别想伤害小圆！"   --蜘蛛战士
speech.BATTLECRY.SPIDER = "不要出现在小圆面前！"   --蜘蛛
speech.ANNOUNCE_TAXDAY = "军火费有着落了"
speech.ANNOUNCE_MYSTERY_DOOR_NOT_FOUND = "Nothing."
speech.ANNOUNCE_MYSTERY_DOOR_FOUND = "A door. How adorable."
speech.ANNOUNCE_NONIGHTSIESTA = "晚上是用来睡觉，而不是小憩的。"
speech.ANNOUNCE_COLD = "这样的身体……也会感到冷吗"
speech.ANNOUCE_UNDERLEAFCANOPY = "树下阴沉沉的."
speech.ANNOUNCE_HUNT_BEAST_NEARBY = "离目标很近了"
speech.ANNOUNCE_SHELTER = "在树旁躲一下吧" --下雨天躲树下
speech.ANNOUNCE_NONIGHTSIESTA_CAVE = "不安全，换个地方。"
speech.ANNOUNCE_MYSTERY_NOREWARD = "这儿什么也没有."
speech.ANNOUNCE_MAGIC_FAIL = "魔法不是这么用的。"
speech.ANNOUNCE_MAPWRAP_RETURN = "我想我感到有什么东西擦着我的腿了。。。"
speech.ANNOUNCE_EAT.GENERIC = "比不上小圆亲手做的"
speech.ANNOUNCE_EAT.STALE = "这味道……算了，这样的身体也没必要挑了"--吃黄色食物
speech.ANNOUNCE_EAT.PAINFUL = "只能应急一下了" --吃怪物肉
speech.ANNOUNCE_EAT.INVALID = "拒绝。"
speech.ANNOUNCE_EAT.YUCKY = "这……连魔法少女都受不了的味道"
speech.ANNOUNCE_EAT.SPOILED = "就算是魔法少女也不能吃这个啊"
speech.ANNOUNCE_NOHUNGERSLEEP = "饿得看见小圆了……"
speech.ANNOUNCE_MYSTERY_FOUND = "这里肯定有些东西"
speech.ANNOUNCE_COMPASS_OUT = "这个指南针现在不指路了。"
speech.ANNOUNCE_DEHUMID[1] = "啊,好多了."
speech.ANNOUNCE_TOO_HUMID[1] = "这%s太重了."
speech.ANNOUNCE_TOO_HUMID[2] = "这%s太热了."
speech.ANNOUNCE_HUNT_LOST_TRAIL = "啧，跟丢了吗"
speech.ANNOUNCE_HAYFEVER_OFF = "呼……连灵魂宝石都差点化了"
speech.ANNOUNCE_BOAT_DAMAGED = "小心，船有点损坏了。"
speech.ANNOUNCE_GAS_DAMAGE = "咳!咳!"
speech.ANNOUNCE_TOOLCORRODED = "我的工具锈蚀了!"
speech.ANNOUNCE_NO_TRAP = "好吧，挺简单的"
speech.ANNOUNCE_WHALE_HUNT_BEAST_NEARBY = "大家伙在前面"
speech.ANNOUNCE_GNATS_DIED = "接招吧,虫子们."
speech.ANNOUNCE_DAMP = "该通知小圆小雨了" --潮湿（1级）
speech.ANNOUNCE_CRAB_ESCAPE = "这家伙跑得比魔女还快"
speech.ANNOUNCE_CHARLIE_ATTACK = "可恶，到底是什么东西？"   --被查理攻击
speech.ANNOUNCE_NODAYSLEEP_CAVE = "还不能休息"
speech.ANNOUNCE_MESSAGEBOTTLE[1] = "这个消息模糊了。我看不清它。"
speech.ANNOUNCE_OTHER_WORLD_PLANT = "我不认为这块土地有足够的营养。"
speech.ANNOUNCE_WET = "小圆，别感冒了啊"
speech.ANNOUNCE_MORETREASURE = "这个军火库好像很富裕啊"
speech.ANNOUNCE_NOSLEEPONFIRE = "还是不要在这睡了"
speech.ANNOUNCE_TREASURE = "就偷这个军火库吧"
speech.ANNOUNCE_OTHER_WORLD_TREASURE = "这个军火库太远了"
speech.ANNOUNCE_TRAWL_FULL = "我的网装满了！"  --拖网装满
speech.ANNOUNCE_HOT = "心脏病发作了吗？不对，是太热了"
speech.ANNOUNCE_TORCH_OUT = "还需要火把！"
speech.ANNOUNCE_HIGHRESEARCH = "我觉得自己真是太聪明了！"
speech.ANNOUNCE_WORMHOLE = "唔……洗干净衣服再去找小圆吧" --跳虫洞
speech.ANNOUNCE_PUGALISK_INVULNERABLE[1] = "它的皮太硬了!"
speech.ANNOUNCE_PUGALISK_INVULNERABLE[2] = "难啃的骨头."
speech.ANNOUNCE_PUGALISK_INVULNERABLE[3] = "去死吧,混账!"
speech.ANNOUCE_ALARMOVER = "我想我逃过一劫."
speech.ANNOUNCE_ENTER_LIGHT = "能看清了。" --进入光源
speech.ANNOUNCE_NOWARDROBEONFIRE = "我没法在它着火的时候弄它。"
speech.ANNOUNCE_ACCOMPLISHMENT = "我感觉好有成就感！"
speech.ANNOUNCE_BURNT = "温度过高，离开这里"
speech.ANNOUNCE_KNOCKEDOUT = "嗷，我的脑袋！"
speech.ANNOUNCE_DEERCLOPS = "巨兽之夜要来了" --boss来袭
speech.ANNOUNCE_FAN_OUT = "还想再吹一会啊"
speech.ANNOUNCE_VOLCANO_ERUPT = "如魔女之夜一般的灾难"
speech.ANNOUNCE_BEES = "蜜——蜂——！！！！"
speech.ANNOUNCE_PECKED = "哎！停下！"
speech.ANNOUNCE_HOUNDS = "危险的讯号"
speech.ANNOUNCE_MOSQUITOS = "用枪也无法击毙，太讨厌了"
speech.ANNOUNCE_NODAYSLEEP = "现在还不能休息"

local DESCRIBE = speech.DESCRIBE	
DESCRIBE.ADVENTURE_PORTAL = "不想再去一次"  --麦斯威尔的门
DESCRIBE.DEERCLOPS = "鹿型魔女……哦不，是巨兽"  --独眼巨鹿
DESCRIBE.COFFEEBEANS = "提神的好东西，很适合魔法少女."  --咖啡豆
DESCRIBE.CORN_COOKED = "不能提供足够的能量"  --爆米花
DESCRIBE.FROGLEGS_COOKED = "我觉得青蛙其实跟魔女没什么关系"  --熟青蛙腿
DESCRIBE.BLOWDART_SLEEP = "也算是一种远程武器了"  --麻醉吹箭
DESCRIBE.EVERGREEN_SPARSE.BURNT = "有炭才有火药"  --粗壮常青树
DESCRIBE.EVERGREEN_SPARSE.CHOPPED = "还可以利用一下"  --粗壮常青树
DESCRIBE.EVERGREEN_SPARSE.GENERIC = "树木和枪械确实存在一定联系"  --粗壮常青树
DESCRIBE.EVERGREEN_SPARSE.BURNING = "要有炭了"  --粗壮常青树
DESCRIBE.CROW.GENERIC = "乌鸦总是被人和魔女联系到一起"  --乌鸦
DESCRIBE.CROW.HELD = "它似乎很想变成一只魔女"  --乌鸦
DESCRIBE.FEATHER_ROBIN_WINTER = "小圆会喜欢吗"  --蓝色羽毛
DESCRIBE.GHOST = "魔女会吃这个吗？"  --鬼魂
DESCRIBE.BOARDS = "板子."  --木板
DESCRIBE.CAVE_BANANA_TREE = "它或许可以进行光合作用."  --洞穴香蕉树
DESCRIBE.GREENSTAFF = "可惜不能解构魔女"  --解构魔杖
DESCRIBE.BIRDTRAP = "抓鸟用的"  --捕鸟器
DESCRIBE.BIRCHNUTDRAKE = "会长大的."  --坚果
DESCRIBE.BLOWDART_FIRE = "远没有手枪好用"  --燃烧吹箭
DESCRIBE.DRAGONPIE = "很像小圆的手艺"  --火龙果派
DESCRIBE.CHESSJUNK1 = "一堆棋子."  --破碎的发条机器
DESCRIBE.BLUE_MUSHROOM.GENERIC = "沙耶加色的蘑菇"  --蓝蘑菇
DESCRIBE.BLUE_MUSHROOM.INGROUND = "它好像睡着了!"  --蓝蘑菇
DESCRIBE.BLUE_MUSHROOM.PICKED = "我想知道它会不会长回来?"  --蓝蘑菇
DESCRIBE.BEEFALOWOOL = "给小圆做件衣服吧"  --牛毛
DESCRIBE.BERRIES = "小圆上次是怎么处理的来着"  --浆果
DESCRIBE.COFFEEBEANS_COOKED = "烤了之后味道好多了"  --烘咖啡豆
DESCRIBE.BLOWDART_POISON = "毒杀或许也是一种手段"  --带毒吹箭
DESCRIBE.GOLDENAXE = "那把斧头挺花哨"  --黄金斧头
DESCRIBE.BLUE_CAP = "它很古怪,还有黏性"  --蓝菇头
DESCRIBE.BLUBBERSUIT = "很保暖，就像小圆送我的那件大衣"  --鲸脂套装
DESCRIBE.GOLDENPITCHFORK = "我干嘛把干草叉弄这么花哨?"  --黄金草叉
DESCRIBE.BIRD_EGG_COOKED = "小圆早餐必备的……"  --熟鸡蛋
DESCRIBE.BUTTERFLYMUFFIN = "小圆好像给我买过一次"  --奶油松饼
DESCRIBE.BISHOP_NIGHTMARE = "破烂不堪"  --损坏的主教
DESCRIBE.CAPTAINHAT = "小圆，看我像船长吗？啊，她不在这"  --船长帽
DESCRIBE.EYETURRET_ITEM = "能给我提供一些帮助"  --恒迪尤斯·舒提尤斯
DESCRIBE.BEARGER = "这熊神烦!"  --熊獾
DESCRIBE.DIVININGRODBASE.GENERIC = "我很奇怪它到底能做什么."  --探测杖的支架
DESCRIBE.DIVININGRODBASE.READY = "看起来我们需要一个更大的钥匙了."  --探测杖的支架
DESCRIBE.DIVININGRODBASE.UNLOCKED = "现在我的机器可以工作了!"  --探测杖的支架
DESCRIBE.CAMPFIRE.GENERIC = "些许的温暖……"  --营火
DESCRIBE.CAMPFIRE.OUT = "有点冷清"  --营火
DESCRIBE.CAMPFIRE.EMBERS = "太暗了"  --营火
DESCRIBE.CAMPFIRE.HIGH = "烫了我一下"  --营火
DESCRIBE.CAMPFIRE.LOW = "火变得有点小了"  --营火
DESCRIBE.CAMPFIRE.NORMAL = "好看又舒服"  --营火
DESCRIBE.COOKEDMANDRAKE = "……吃了吧。"  --熟曼德拉草
DESCRIBE.ANTIVENOM = "为了活下去……"  --抗蛇毒血清
DESCRIBE.CRAB.GENERIC = "小圆上次好像想吃海鲜来着"  --兔蟹
DESCRIBE.CRAB.HIDDEN = "海鲜呢？"  --兔蟹
DESCRIBE.CHARCOAL = "可以做成火药"  --木炭
DESCRIBE.DOYDOYEGG_CRACKED = "唔.我相信还会有更多!"  --裂开的渡渡鸟蛋
DESCRIBE.GRASS.BARREN = "用肥料可以拯救它"  --草
DESCRIBE.GRASS.PICKED = "拔光了"  --草
DESCRIBE.GRASS.WITHERED = "我都受不了，何况是它"  --草
DESCRIBE.GRASS.GENERIC = "这个是一簇草。"  --草
DESCRIBE.GRASS.BURNING = "烧起来了，离远一点。"  --草
DESCRIBE.BUZZARD = "这秃鹫有点诡异!"  --秃鹫
DESCRIBE.FISHINGROD = "上次和小圆钓鱼是在……"  --钓竿
DESCRIBE.FISH_RAW_SMALL_COOKED = "还不如生吃"  --熟小块鱼肉
DESCRIBE.BELL_BLUEPRINT = "它挺科学!"  --
DESCRIBE.BUNNYMAN = "只能确定它不是魔女"  --兔人
DESCRIBE.BONESTEW = "让我来烹饪真是浪费"  --肉汤
DESCRIBE.FOOTBALLHAT = "很结实，保护好头部"  --橄榄球头盔
DESCRIBE.FISH_COOKED = "烤好了"  --熟鱼
DESCRIBE.BERRIES_COOKED = "味道不太一样"  --烤浆果
DESCRIBE.BUGNET = "抓点萤火虫送给小圆吧"  --网
DESCRIBE.DECIDUOUSTREE.BURNT = "这下有木炭了"  --桦树
DESCRIBE.DECIDUOUSTREE.POISON = "怎么会有这种东西？又不是魔女"  --桦树
DESCRIBE.DECIDUOUSTREE.CHOPPED = "还有利用的空间"  --桦树
DESCRIBE.DECIDUOUSTREE.GENERIC = "它非常茂盛,大部分时候."  --桦树
DESCRIBE.DECIDUOUSTREE.BURNING = "正在生产木炭"  --桦树
DESCRIBE.GEMSOCKET.VALID = "看上去可以了"  --宝石放置台
DESCRIBE.GEMSOCKET.GEMS = "我需要一颗宝石."  --宝石放置台
DESCRIBE.FISH_FARM.REDFISH = "小圆看到这么多鱼一定会很开心"  --养鱼场
DESCRIBE.FISH_FARM.EMPTY = "只有渔场肯定不够"  --养鱼场
DESCRIBE.FISH_FARM.BLUEFISH = "我该收获这些鱼了！"  --养鱼场
DESCRIBE.FISH_FARM.TWOFISH = "这些鱼仍在繁殖。"  --养鱼场
DESCRIBE.FISH_FARM.STOCKED = "不可操之过急"  --养鱼场
DESCRIBE.FISH_FARM.ONEFISH = "这有一条鱼！"  --养鱼场
DESCRIBE.FISH5_COOKED = "这种做法小圆不会喜欢的"  --煮熟的霓虹灯鱼
DESCRIBE.ARMORWOOD = "不错的防护手段"  --木制盔甲
DESCRIBE.BIOLUMINESCENCE = "小圆会喜欢这个"  --荧光生物
DESCRIBE.BUTTERFLY.GENERIC = "抓一只送给小圆吧"  --蝴蝶
DESCRIBE.BUTTERFLY.HELD = "小圆不在，只能以后送她了"  --蝴蝶
DESCRIBE.ACORN_COOKED = "我记得桦木没有果子啊"  --烤桦坚果
DESCRIBE.GRASS_WATER = "我认为你渴了,草."  --草
DESCRIBE.BUOY = "如小圆一般的明灯"  --浮标
DESCRIBE.GREEN_MUSHROOM.GENERIC = "仁美色的蘑菇"  --绿蘑菇
DESCRIBE.GREEN_MUSHROOM.INGROUND = "它好像睡着了!"  --绿蘑菇
DESCRIBE.GREEN_MUSHROOM.PICKED = "我想知道它会不会长回来?"  --绿蘑菇
DESCRIBE.FLOTSAM = "她们总说我的身材浮不起来……"  --漂浮物
DESCRIBE.FLOWER_CAVE_TRIPLE = "这光芒无法与小圆相比"  --荧光草
DESCRIBE.COLDFIRE.GENERIC = "这种逆熵系统难道是QB搞出来的？"  --吸热营火
DESCRIBE.COLDFIRE.OUT = "好吧,已经结束了"  --吸热营火
DESCRIBE.COLDFIRE.EMBERS = "在火熄灭之前我得加点东西"  --吸热营火
DESCRIBE.COLDFIRE.HIGH = "逆熵系统失控了吗"  --吸热营火
DESCRIBE.COLDFIRE.LOW = "功率有点小"  --吸热营火
DESCRIBE.COLDFIRE.NORMAL = "对牛顿很不友好的篝火"  --吸热营火
DESCRIBE.FIREFLIES.GENERIC = "抓一点给小圆如何？"  --萤火虫
DESCRIBE.FIREFLIES.HELD = "小圆应该会喜欢的!"  --萤火虫
DESCRIBE.EYETURRET = "它似乎会保护我"  --恒迪尤斯·舒提尤斯
DESCRIBE.COOKEDMONSTERMEAT = "魔法少女不配享用美食……"  --熟怪兽肉
DESCRIBE.BLUEAMULET = "像冰一样冷!"  --寒冰护符
DESCRIBE.FEATHERSAIL = "和羽毛一样轻!"  --简版羽帆
DESCRIBE.FISH5 = "看起来像一条鱼，但是感觉湿乎乎的。"  --霓虹灯鱼
DESCRIBE.FLOWER_CAVE_DOUBLE = "这光芒无法与小圆相比"  --荧光草
DESCRIBE.FISH4 = "它的表皮能防水。"  --小丑鱼
DESCRIBE.ARMORSNURTLESHELL = "穿上这个的话，小圆会很想给我拍照"  --圆壳蛞蝓壳
DESCRIBE.BUSHHAT = "这什么造型？"  --丛林帽
DESCRIBE.GOLDENSHOVEL = "真想卖了换点军火"  --黄金铲子
DESCRIBE.CRATE = "一定有办法打开的."  --木箱
DESCRIBE.CORMORANT = "储存量赶得上我的盾了"  --鸬鹚
DESCRIBE.CAVIAR = "小圆好像做过两次"  --鱼子酱
DESCRIBE.BEEHAT = "下次郊游给小圆准备一个"  --养蜂人的帽子
DESCRIBE.GLOMMER = "长得比QB还奇怪"  --格罗姆
DESCRIBE.COOKPOT.BURNT = "这锅废了."  --烹煮锅
DESCRIBE.COOKPOT.DONE = "开饭吧。"  --烹煮锅
DESCRIBE.COOKPOT.COOKING_LONG = "先打个魔女再回来"  --烹煮锅
DESCRIBE.COOKPOT.COOKING_SHORT = "就快好了!"  --烹煮锅
DESCRIBE.COOKPOT.EMPTY = "我的厨艺还是不行"  --烹煮锅
DESCRIBE.CROCODOG = "船和人得离那混蛋的嘴远一点。"  --鳄狗
DESCRIBE.BASALT = "子弹都打不动!"  --玄武岩
DESCRIBE.BIRD_EGG = "它似乎也是火药的原材料"  --鸡蛋
DESCRIBE.DEPLETED_BUSH_VINE = "总有一天它会回来的."  --
DESCRIBE.DURIAN_COOKED = "小圆说过，榴莲不是这么吃的"  --超臭榴莲
DESCRIBE.CHIMINEA = "这个结构很理想"  --室外壁炉
DESCRIBE.BALLPHINHOUSE = "为什么他们都有地方住"  --海豚宫殿
DESCRIBE.DRAGONFRUIT_COOKED = "这样处理会让小圆很头疼吧"  --烤火龙果
DESCRIBE.ENCRUSTEDBOAT = "好想带着小圆兜风"  --甲壳船
DESCRIBE.FLAMEGEYSER = "像火焰喷射器"  --压力火泉
DESCRIBE.BURNT_MARSH_BUSH = "一切都燃烧殆尽了."  --
DESCRIBE.BOOMERANG = "好原始的武器"  --回旋镖
DESCRIBE.DRAGONFRUIT_SEEDS = "能种出好东西"  --火龙果种子
DESCRIBE.GREENGEM = "它闪烁着仁美般的光彩."  --绿宝石
DESCRIBE.CORAL_BRAIN = "蕴含着几次轮回才能学会的知识."  --聪明豆
DESCRIBE.DIVININGRODSTART = "这个棒子看起来很有用啊!"  --探测杖的支架
DESCRIBE.BEDROLL_STRAW = "稍微休息一下？"  --稻草卷
DESCRIBE.COCONUT_COOKED = "这个小圆肯定没吃过"  --烤椰子
DESCRIBE.ASH.GENERIC = "终将归于尘土."  --灰烬
DESCRIBE.ASH.REMAINS_THINGIE = "那有一个完美的科学解释."  --灰烬
DESCRIBE.ASH.REMAINS_GLOMMERFLOWER = "那朵花在传送中付诸一炬了!"  --灰烬
DESCRIBE.ASH.REMAINS_EYE_BONE = "那个眼珠在传送中被付诸一炬了!"  --灰烬
DESCRIBE.BALLPHIN = "好可爱，像小圆一样单纯"  --宽吻海豚
DESCRIBE.BAMBOOTREE.BURNT = "有点浪费."  --竹子
DESCRIBE.BAMBOOTREE.CHOPPED = "接招吧,大自然!"  --竹子
DESCRIBE.BAMBOOTREE.GENERIC = "看起来相当结识."  --竹子
DESCRIBE.BAMBOOTREE.BURNING = "这个不能烧成炭"  --竹子
DESCRIBE.BLOWDART_PIPE = "不像枪支一样需要保养"  --吹箭
DESCRIBE.CACTUS_MEAT_COOKED = "小圆说得对，这东西可以吃"  --煮好的仙人掌肉
DESCRIBE.FRESHFRUITCREPES = "甜蜜水果!均衡早餐的一部分."  --新鲜水果薄饼
DESCRIBE.DRAGOONSPIT = "一个特别恶心的东西!"  --呆龙的口水
DESCRIBE.DRAGOONHEART = "龙骑士曾经储存他们亲情的地方."  --呆龙心脏
DESCRIBE.CAVE_BANANA_BURNT = "不是我的错!"  --
DESCRIBE.DOYDOYEGG_COOKED = "小圆吃不到真是太可惜了啊"  --渡渡鸟煎蛋
DESCRIBE.DEPLETED_GRASS_WATER = "再见,可爱的植物."  --
DESCRIBE.DEPLETED_BAMBOOTREE = "它还会长吗?"  --
DESCRIBE.BACONEGGS = "小圆经常给我做！"  --鸡蛋火腿
DESCRIBE.BISHOP = "好像在上学的时候见过这家伙……是错觉吧"  --发条主教
DESCRIBE.ANCIENT_ALTAR_BROKEN = "貌似这东西坏了."  --破碎的远古伪科学站
DESCRIBE.COCONUT_HALVED = "当我一起点击它们的时候,他们会发出马叫声."  --半个椰子
DESCRIBE.BRAINJELLYHAT = "有了这个，就不用自学设计图了"  --智慧帽
DESCRIBE.ARMORCACTUS = "她们总说我的身上有刺，但小圆不在乎"  --仙人掌盔甲
DESCRIBE.FEATHER_CROW = "我有预感，未来我会爱上这东西"  --黑色羽毛
DESCRIBE.DRAGOONEGG = "魔女在孵化？不，只是一只呆龙"  --呆龙蛋
DESCRIBE.BUSH_VINE.BURNT = "我觉得我本能预防它的."  --藤蔓丛
DESCRIBE.BUSH_VINE.CHOPPED = "接招吧,大自然!"  --藤蔓丛
DESCRIBE.BUSH_VINE.GENERIC = "全是藤蔓!"  --藤蔓丛
DESCRIBE.BUSH_VINE.BURNING = "哎呀."  --藤蔓丛
DESCRIBE.DRUMSTICK_COOKED = "炸得小圆差远了"  --炸鸡腿
DESCRIBE.CRABHOLE = "他们管沙子里的洞叫他们的家."  --兔蟹的窝
DESCRIBE.CORN = "可以充饥"  --玉米
DESCRIBE.DRAGOONDEN = "谁都要睡觉啊."  --呆龙巢
DESCRIBE.DOYDOYEGG = "这蛋似乎跟火药没关系."  --渡渡鸟蛋
DESCRIBE.FIRESUPPRESSOR.LOWFUEL = "燃料不足，还好这家伙不会变成魔女."  --雪球发射器
DESCRIBE.FIRESUPPRESSOR.ON = "工作吧"  --雪球发射器
DESCRIBE.FIRESUPPRESSOR.OFF = "停一下."  --雪球发射器
DESCRIBE.DUG_ELEPHANTCACTUS = "这简直是个火力点."  --仙象掌
DESCRIBE.FISH3 = "海鲜与坪肉，超棒的大餐。"  --紫色石斑鱼
DESCRIBE.BOAT_TORCH = "这点亮度还是很难完成射击."  --船载火炬
DESCRIBE.EGGPLANT = "怎么烹饪来着？下次问问小圆"  --茄子
DESCRIBE.BLUBBER = "可以作为燃料."  --鲸油
DESCRIBE.CARGOBOAT = "移动的弹药库"  --货船
DESCRIBE.CAVE_ENTRANCE_OPEN.GENERIC = "堵住了吗？"  --落水洞
DESCRIBE.CAVE_ENTRANCE_OPEN.OPEN = "下面似乎很危险，保持警惕"  --落水洞
DESCRIBE.BLOWDART_FLUP = "天然的麻醉枪？"  --眼睛吹箭
DESCRIBE.CORAL_BRAIN_ROCK = "我不知道它是怎么长出来的..."  --聪明芽
DESCRIBE.FISH_RAW = "足够让小圆吃饱了"  --生鱼片
DESCRIBE.CAVE_EXIT.GENERIC = "我想我就呆在这里得了."  --绳索
DESCRIBE.CAVE_EXIT.OPEN = "先回去修整一下？"  --绳索
DESCRIBE.FISH_RAW_SMALL = "只有一点点鱼肉."  --小块鱼肉
DESCRIBE.ANIMAL_TRACK = "或许可以解决一下食物需求"  --动物足迹
DESCRIBE.FLUP = "沼跃鱼并没有看穿一切，它不知道惹我的后果是什么"  --追踪性弹涂鱼
DESCRIBE.BERRYBUSH.BARREN = "我想它需要施肥"  --浆果灌木丛
DESCRIBE.BERRYBUSH.PICKED = "或许它们会再长出来?"  --浆果灌木丛
DESCRIBE.BERRYBUSH.GENERIC = "味道还行"  --浆果灌木丛
DESCRIBE.BERRYBUSH.WITHERED = "那么热,什么都不长."  --浆果灌木丛
DESCRIBE.CUTGRASS = "上次跟小圆去割草，弄了很多"  --割下的草
DESCRIBE.BATWING_COOKED = "说了不要惹我。"  --煮熟的黑蝙蝠翅膀
DESCRIBE.COCONADE.GENERIC = "原料太粗糙，只能做成这样了."  --椰壳炸弹
DESCRIBE.COCONADE.BURNING = "爆炸的威力很一般，但还是得躲远点."  --椰壳炸弹
DESCRIBE.BIRDCAGE.GENERIC = "把小圆放进去……天呐我在想什么"  --鸟笼
DESCRIBE.BIRDCAGE.STARVING = "小圆，鸟饿了……啊，她不在。"  --鸟笼
DESCRIBE.BIRDCAGE.SKELETON = "如果小圆在的话，应该不会犯这种错误."  --鸟笼
DESCRIBE.BIRDCAGE.OCCUPIED = "真希望里面关的是QB"  --鸟笼
DESCRIBE.BIRDCAGE.HUNGRY = "你饿了吗？啊，以前都是小圆喂鸟来着."  --鸟笼
DESCRIBE.BIRDCAGE.SLEEPING = "啊,他睡着了"  --鸟笼
DESCRIBE.BIRDCAGE.DEAD = "这鸟……被我养死了吗？"  --鸟笼
DESCRIBE.GLOMMERFLOWER.GENERIC = "不可思议的花和小家伙"  --格罗姆的花
DESCRIBE.GLOMMERFLOWER.DEAD = "小圆看见这个的话一定会很伤心"  --格罗姆的花
DESCRIBE.DEVTOOL_NODEV = "我还不够强壮,无法挥舞它."  --
DESCRIBE.DEERCLOPS_EYEBALL = "似乎大有用处"  --巨鹿眼球
DESCRIBE.CARROT_SEEDS = "小圆应该能认出来是什么种子."  --胡萝卜种子
DESCRIBE.DORSALFIN = "我会为你报仇的"  --背鳍
DESCRIBE.CORALREEF = "真想带小圆来看看这个景色"  --珊瑚礁
DESCRIBE.BOATREPAIRKIT = "根据设计图来使用"  --修船套件
DESCRIBE.GOOSE_FEATHER = "给小圆做个扇子吧"  --掉落的羽毛
DESCRIBE.FLOWERHAT = "小圆给我做过一个，可惜腐烂了"  --花环
DESCRIBE.DOYDOY = "我想像保护小圆一样保护这家伙"  --渡渡鸟
DESCRIBE.BLUEGEM = "它闪着那个笨蛋一样的光"  --蓝宝石
DESCRIBE.DRAGONFRUIT = "为了让小圆能经常吃到，我钻研了不少赚钱技巧"  --火龙果
DESCRIBE.DOYDOYBABY = "让我想起了达也."  --幼小的渡渡鸟
DESCRIBE.FISH3_COOKED = "鱼整个都烤好了。"  --煮熟的紫色石斑鱼
DESCRIBE.ELEPHANTCACTUS_STUMP = "拔掉了一个炮楼."  --仙象掌根
DESCRIBE.ELEPHANTCACTUS_ACTIVE = "猛烈的火力压制."  --刺人的象仙人掌
DESCRIBE.EGGPLANT_COOKED = "还是比不上小圆的收益"  --红烧茄子
DESCRIBE.GASHAT = "这下不怕使用毒气的魔女了."  --粉尘净化器
DESCRIBE.DIVININGROD.GENERIC = "看起来像一种制导装置."  --探测杖
DESCRIBE.DIVININGROD.HOT = "我控制不住这东西了!"  --探测杖
DESCRIBE.DIVININGROD.COLD = "信号很模糊."  --探测杖
DESCRIBE.DIVININGROD.WARM = "我正在向正确的方向走呢."  --探测杖
DESCRIBE.DIVININGROD.WARMER = "我现在已经很接近了"  --探测杖
DESCRIBE.BIGFOOT = "它能踩死舞台魔女吗？"  --大脚
DESCRIBE.ARMOR_WINDBREAKER = "当年的我瘦得能被风吹走"  --风衣
DESCRIBE.FLOWER_EVIL = "我还以为蔷薇魔女出现了"  --恶魔之花
DESCRIBE.CORAL = "找个最漂亮的送给小圆"  --珊瑚
DESCRIBE.BEEMINE = "这地雷的威力简直太可怜了"  --蜜蜂地雷
DESCRIBE.FEATHERHAT = "快藏起来，小圆看到了会强迫我戴上的"  --羽毛帽
DESCRIBE.FOLIAGE = "一些绿叶植物."  --树叶
DESCRIBE.BLUEPRINT = "它挺科学!"  --蓝图
DESCRIBE.DEPLETED_GRASS.GENERIC = "这大概是一簇草"  --草
DESCRIBE.CUTLICHEN = "小圆总是说这个很有营养."  --苔藓
DESCRIBE.ARMOR_LIFEJACKET = "先给小圆套上吧"  --救生衣
DESCRIBE.DURIAN_SEEDS = "能种出甜美的东西."  --榴莲种子
DESCRIBE.BOTTLELANTERN = "像小圆一样给我带来光明."  --水瓶提灯
DESCRIBE.CUTSTONE = "很平整"  --石砖块
DESCRIBE.GOLDENPICKAXE = "嘿,金子实际上不是软的吗?"  --黄金鹤嘴锄
DESCRIBE.FROG.GENERIC = "他能掌控时间"  --青蛙
DESCRIBE.FROG.SLEEPING = "他好像很想拿走我的时间"  --青蛙
DESCRIBE.FROG.DEAD = "别想夺走我的时间."  --青蛙
DESCRIBE.ARMOROBSIDIAN = "怎么会这么坚固？."  --十胜石盔甲
DESCRIBE.BISHOP_CHARGE_HIT = "损伤很大!"  --
DESCRIBE.COOKEDSMALLMEAT = "嗯……烤得一般"  --熟肉块
DESCRIBE.FLOWERSALAD = "没有小圆喂我，吃不下去啊"  --花瓣沙拉
DESCRIBE.BATBAT = "它到底是怎样使我恢复健康的？."  --蝙蝠斧棒
DESCRIBE.ARMOUREDBOAT = "是艘战列舰."  --装甲的船
DESCRIBE.FROG_POISON = "它也具备掌控时间的能力."  --箭毒蛙
DESCRIBE.ARMORDRAGONFLY = "没有燃料，为何会这么热？"  --龙鳞盔甲
DESCRIBE.BABYOX = "虽然是小牛，但是一样的臭。"  --水牛宝宝
DESCRIBE.COCONUT.GENERIC = "塞点火药进去如何？."  --椰子
DESCRIBE.COCONUT.PLANTED = "会变成许多椰子."  --椰子
DESCRIBE.FEATHERFAN = "好想给小圆也扇一下."  --鹅毛扇
DESCRIBE.DURIAN = "榴莲为什么会有毒？"  --榴莲
DESCRIBE.FISHTACOS = "易碎又美味的!"  --鱼炸玉米饼
DESCRIBE.CATCOONHAT = "很适合小圆!"  --猫帽
DESCRIBE.BEEBOX.GENERIC = "蜜蜂对我虎视眈眈"  --蜂箱
DESCRIBE.BEEBOX.SOMEHONEY = "我应该等一会"  --蜂箱
DESCRIBE.BEEBOX.FULLHONEY = "要不要时停之后再采蜜？"  --蜂箱
DESCRIBE.BEEBOX.NOHONEY = "它是空的"  --蜂箱
DESCRIBE.BEEBOX.BURNT = "怎么糊了?"  --蜂箱
DESCRIBE.GLOMMERFUEL = "好像可以当燃料."  --格罗姆的粘液
DESCRIBE.DRAGOON = "别让这家伙靠近弹药库"  --呆龙
DESCRIBE.ARMORSEASHELL = "它居然能防毒，难以理解"  --海贝盔甲
DESCRIBE.BERMUDATRIANGLE = "我……晕船."  --带电的等腰三角
DESCRIBE.FRUITMEDLEY = "有水果味."  --水果拼盘
DESCRIBE.DUG_BAMBOOTREE = "让它长成竹子吧"  --竹根
DESCRIBE.FISH = "小圆，鱼怎么处理……她不在啊"  --鱼
DESCRIBE.DEAD_SWORDFISH = "差点把手划破，还是别让小圆碰吧."  --死旗鱼
DESCRIBE.FIREPIT.GENERIC = "肯定比黑暗好"  --石头篝火
DESCRIBE.FIREPIT.OUT = "至少我还能重新开始."  --石头篝火
DESCRIBE.FIREPIT.EMBERS = "在火熄灭之前我得加点东西"  --石头篝火
DESCRIBE.FIREPIT.HIGH = "别让它烧了弹药！"  --石头篝火
DESCRIBE.FIREPIT.LOW = "没法瞄准目标了"  --石头篝火
DESCRIBE.FIREPIT.NORMAL = "好看又舒服"  --石头篝火
DESCRIBE.BATCAVE = "我才不想吵醒他们."  --蝙蝠洞
DESCRIBE.CALIFORNIAROLL = "但我没有筷子."  --加州卷
DESCRIBE.FISH_MED_COOKED = "还是不如小圆炸得好."  --鱼排
DESCRIBE.ARMOR_SNAKESKIN = "给小圆也做一件吧"  --蛇鳞上衣
DESCRIBE.BISQUE = "煮得很鲜"  --鲜贝浓汤
DESCRIBE.CEVICHE = "吃不饱啊."  --酸橘汁腌鱼
DESCRIBE.CAVE_ENTRANCE.GENERIC = "可以炸开……还是挖开吧"  --
DESCRIBE.CAVE_ENTRANCE.OPEN = "我觉得在下面肯定能发现许多东西"  --
DESCRIBE.CLOTHSAIL = "古老的动力设备"  --布帆
DESCRIBE.CHESSJUNK2 = "又一堆棋子."  --破碎的发条机器
DESCRIBE.GOLDNUGGET = "很值钱，但是这里没有商店"  --金块
DESCRIBE.BAMBOO = "也许我能用它迷惑我的敌人?"  --竹子
DESCRIBE.BOAT_LANTERN = "有时会让我成为靶子"  --船灯
DESCRIBE.CARROT = "不会做的话就会很难吃."  --胡萝卜
DESCRIBE.COLDFIREPIT.GENERIC = "像医院一样阴冷"  --吸热篝火
DESCRIBE.COLDFIREPIT.OUT = "至少我还能重新开始."  --吸热篝火
DESCRIBE.COLDFIREPIT.EMBERS = "在火熄灭之前我得加点东西"  --吸热篝火
DESCRIBE.COLDFIREPIT.HIGH = "还好它被封起来了!"  --吸热篝火
DESCRIBE.COLDFIREPIT.LOW = "火变得有点小了"  --吸热篝火
DESCRIBE.COLDFIREPIT.NORMAL = "让我回想起了病床上的生涯"  --吸热篝火
DESCRIBE.CACTUS_FLOWER = "有刺，但很漂亮，像我一样"  --仙人掌花
DESCRIBE.BAT = "许多人害怕它，但显然不包括我"  --黑蝙蝠
DESCRIBE.CARROT_PLANTED = "小圆说不能挑食，但是胡萝卜好硬"  --胡萝卜
DESCRIBE.GREEN_CAP_COOKED = "这玩意居然能提神醒脑"  --烤绿蘑菇
DESCRIBE.FLOWER = "这个花坛被小圆承包了"  --花
DESCRIBE.DOYDOYFEATHER = "漂亮的羽毛，小圆会喜欢的吧"  --渡渡鸟的羽毛
DESCRIBE.CANE = "或许很适合心脏病人……"  --步行手杖
DESCRIBE.FABRIC = "古老的服装材料"  --布
DESCRIBE.DUBLOON = "哪里能买东西呢"  --金币
DESCRIBE.CUTLASS = "竟然如此锋利"  --旗鱼短剑
DESCRIBE.COFFEEBUSH.BARREN = "或许开一枪就能生长了"  --咖啡树
DESCRIBE.COFFEEBUSH.PICKED = "也许它们能长回来?"  --咖啡树
DESCRIBE.COFFEEBUSH.GENERIC = "这里有咖啡喝"  --咖啡树
DESCRIBE.COFFEEBUSH.WITHERED = "没精打采的"  --咖啡树
DESCRIBE.EARRING = "平息火山的愤怒吧"  --至尊耳环
DESCRIBE.BURIEDTREASURE = "能捡到什么武器呢"  --X标记点
DESCRIBE.BEARDHAIR = "好丑，人不该长胡子"  --胡须
DESCRIBE.EYEPLANT = "好讨厌，像被魔女注视着."  --眼球草
DESCRIBE.CATCOON = "有趣的小家伙."  --浣猫
DESCRIBE.ANCIENT_STATUE = "一枪打不碎."  --远古雕像
DESCRIBE.COFFEEBOT = "这是个咖啡机."  --
DESCRIBE.FLINT = "能打火，但是不能开火"  --燧石
DESCRIBE.COFFEE = "小圆，第二杯半价哦"  --咖啡
DESCRIBE.FEATHER_ROBIN = "杏子吃剩下的"  --红色羽毛
DESCRIBE.ACCOMPLISHMENT_SHRINE = "请给我一个师的弹药"  --神灯
DESCRIBE.CUTREEDS = "割芦苇,为手工艺品和业余爱好做准备"  --割下的芦苇
DESCRIBE.GOATMILK = "好想给小圆也喝一杯."  --伏特羊奶
DESCRIBE.BEARGERVEST = "不知为何，有点饱了"  --熊皮背心
DESCRIBE.FROGLEGS = "如果你不惹我，我也不想吃了你"  --青蛙腿
DESCRIBE.DOUBLE_UMBRELLAHAT = "这个伞不行，不能撑给小圆"  --双层伞帽
DESCRIBE.BANANAPOP = "轰！蕉冻完成了"  --香蕉冻
DESCRIBE.BEARGER_FUR = "吃了多少东西才能长出这样的皮毛."  --厚皮毛
DESCRIBE.CARROT_COOKED = "有点糊……"  --烤胡萝卜
DESCRIBE.GUACAMOLE = "鳄梨是营销产物，我确认"  --鳄梨酱
DESCRIBE.GLOMMERWINGS = "不符合流体力学"  --格罗姆的翅膀
DESCRIBE.BANDAGE = "藏好，别让杏子给吃了"  --蜂蜜药膏
DESCRIBE.DEVTOOL = "闻起来像培根一样!"  --开发工具
DESCRIBE.EEL = "这东西卷起来放在流水席上就会变得非常贵"  --鳗鱼
DESCRIBE.BEEMINE_MAXWELL = "毫无威力可言的设计"  --麦斯威尔的蜜蜂炸弹
DESCRIBE.BABYBEEFALO = "啊.真可爱!"  --牛宝宝
DESCRIBE.ELEPHANTCACTUS = "火力很猛"  --仙象掌
DESCRIBE.CAVE_BANANA_COOKED = "小圆也很喜欢"  --煮熟的香蕉
DESCRIBE.BEDROLL_FURRY = "想和小圆一起睡在里面"  --毛皮铺盖
DESCRIBE.DUG_BUSH_VINE = "我觉得我要把它捡起来."  --藤蔓根
DESCRIBE.BLUE_CAP_COOKED = "现在不同了......"  --烤蓝蘑菇
DESCRIBE.BEE.GENERIC = "别用炮弹打蜜蜂"  --蜜蜂
DESCRIBE.BEE.HELD = "小心!"  --蜜蜂
DESCRIBE.FROGGLEBUNWICH = "居然还有这种吃法"  --青蛙圆面包三明治
DESCRIBE.BOAT = "简易载具"  --
DESCRIBE.ARMORSLURPER = "魔法少女要忍饥挨饿……"  --饥饿腰带
DESCRIBE.DRAGON_SCALES = "优秀的热源，能不能发电呢."  --鳞片
DESCRIBE.EVERGREEN.BURNT = "炭，火药的原料"  --常青树
DESCRIBE.EVERGREEN.CHOPPED = "还能再利用一下"  --常青树
DESCRIBE.EVERGREEN.GENERIC = "这些都很松软."  --常青树
DESCRIBE.EVERGREEN.BURNING = "制炭中~"  --常青树
DESCRIBE.GREENAMULET = "造出来的子弹会不会哑火？"  --建造护符
DESCRIBE.BOATCANNON = "可惜这东西没法手持开火."  --船载加农炮
DESCRIBE.DUG_BERRYBUSH = "现在它能带到任何地方了."  --浆果灌木丛
DESCRIBE.DOYDOYNEST = "先有渡渡鸟,还是先有渡渡鸟蛋?"  --渡渡鸟巢
DESCRIBE.FIREHOUND = "像一颗行走的子弹"  --红色猎犬
DESCRIBE.GUNPOWDER = "一切军火的基础！"  --火药
DESCRIBE.FURTUFT = "黑白的毛."  --
DESCRIBE.FEM_PUPPET = "她被困住了!"  --
DESCRIBE.ANCIENT_ALTAR = "让我看看有什么黑科技……"  --远古伪科学站
DESCRIBE.BEEHIVE = "这个就可以一炮消灭了"  --蜂窝
DESCRIBE.CAVE_FERN = "这是个蕨类植物."  --蕨类植物
DESCRIBE.ARMORLIMESTONE = "好紧，麻美恐怕穿不上"  --石灰石套装
DESCRIBE.CHESTER = "智能弹药箱"  --切斯特
DESCRIBE.GUANO = "同样是可燃的"  --鸟屎
DESCRIBE.FISHINHOLE = "这里没有要求禁止炸鱼."  --鱼群
DESCRIBE.DUG_SAPLING = "我可以把它移植的离家近些."  --树苗
DESCRIBE.AXE = "子弹打光了就得用斧头了"  --斧头
DESCRIBE.COOKEDMEAT = "好像有点烤焦了"  --熟肉
DESCRIBE.DUG_COFFEEBUSH = "想喝咖啡还得自己种"  --咖啡树
DESCRIBE.FERTILIZER = "只是一堆粪."  --便便篮
DESCRIBE.CACTUS_MEAT = "小圆说这东西其实很好吃的."  --仙人掌肉
DESCRIBE.BEEFALOHAT = "带上这个帽子，我就是女牛仔了."  --牛帽
DESCRIBE.AERODYNAMICHAT = "头上生风"  --星芒头盔
DESCRIBE.FISHSTICKS = "垃圾食品，但是好吃."  --炸鱼条
DESCRIBE.BATWING = "惹我的后果很惨重."  --黑蝙蝠翅膀
DESCRIBE.EYEBRELLAHAT = "我要像这把伞一样守护小圆."  --眼球伞
DESCRIBE.CORALLARVE = "这是一个小珊瑚礁。"  --珊瑚种子
DESCRIBE.FARMPLOT.GENERIC = "我应该种点庄稼."  --
DESCRIBE.FARMPLOT.BURNT = "我的杰作"  --烧焦的
DESCRIBE.FARMPLOT.GROWING = "长啊,植物,长啊!"  --
DESCRIBE.FARMPLOT.NEEDSFERTILIZER = "我想它需要施肥"  --
DESCRIBE.DRUMSTICK = "炸一下才好吃"  --鸡腿
DESCRIBE.GRASS_UMBRELLA = "差不多是装饰品."  --漂亮太阳伞
DESCRIBE.FISH4_COOKED = "烤到完美。"  --煮熟的小丑鱼
DESCRIBE.CATCOONDEN.GENERIC = "树墩上有个小洞."  --中空树桩
DESCRIBE.CATCOONDEN.EMPTY = "再无生气."  --中空树桩
DESCRIBE.CORN_SEEDS = "它是玉米种子."  --玉米种子
DESCRIBE.BUTTER = "我不能相信它是黄油!"  --蝴蝶黄油
DESCRIBE.EEL_COOKED = "闻起来真香!"  --煮熟的鳗鱼
DESCRIBE.DUG_GRASS = "这个需要被种植."  --长草簇
DESCRIBE.EGGPLANT_SEEDS = "它是茄子的种子."  --茄子种子
DESCRIBE.CAVE_BANANA = "这东西黏糊糊的."  --洞穴香蕉
DESCRIBE.BELL = "蕴藏着可怕的魔力."  --旧钟
DESCRIBE.BACKPACK = "可以多带几个弹夹."  --背包
DESCRIBE.GOLDENMACHETE = "不如买了换子弹!"  --黄金砍刀
DESCRIBE.AMULET = "它似乎无法保护我的生命"  --生命护符
DESCRIBE.CHESTER_EYEBONE.GENERIC = "你要帮我扛枪吗"  --切斯特眼骨
DESCRIBE.CHESTER_EYEBONE.WAITING = "醒醒，该运子弹了"  --切斯特眼骨
DESCRIBE.GREEN_CAP = "它看起来很正常"  --绿菇头
DESCRIBE.GEARS = "可以制成复杂的枪械"  --齿轮
DESCRIBE.FIRESTAFF = "没有子弹好用"  --火魔杖
DESCRIBE.ACORN.GENERIC = "这东西现实中不存在吧."  --桦坚果
DESCRIBE.ACORN.PLANTED = "长出更多干果~."  --桦坚果
DESCRIBE.EARMUFFSHAT = "兔兔那么可爱，当然是要做成耳罩"  --兔毛耳套
DESCRIBE.DUG_MARSH_BUSH = "我应该种这个"  --尖刺灌木
DESCRIBE.BUTTERFLYWINGS = "这东西居然能做成松饼……"  --蝴蝶翅膀
DESCRIBE.DRAGONFLYCHEST = "华而不实"  --龙鳞宝箱
DESCRIBE.ARMORMARBLE = "太重了，不太适合我"  --大理石盔甲
DESCRIBE.DRAGONFLY = "子弹可能打不透这鳞片"  --龙蝇
DESCRIBE.DIRTPILE = "这是一堆污泥......还是?"  --可疑的土堆
DESCRIBE.BEEFALO.GENERIC = "这似乎是人工培育的牛"  --皮弗娄牛
DESCRIBE.BEEFALO.SLEEPING = "如果我一枪打中要害……"  --皮弗娄牛
DESCRIBE.BEEFALO.FOLLOWER = "或许它可以变成我的载具"  --皮弗娄牛
DESCRIBE.BEEFALO.NAKED = "光秃秃的"  --皮弗娄牛
DESCRIBE.FISH_MED = "一条肥鱼."  --死掉的狗鱼
DESCRIBE.CACTUS.GENERIC = "小圆说能吃，那就肯定是能吃的."  --仙人掌
DESCRIBE.CACTUS.PICKED = "小圆怎么处理的来着."  --仙人掌
DESCRIBE.CHESSJUNK3 = "或许可以学习一下这种机械结构……."  --破碎的发条机器
DESCRIBE.COONTAIL = "感觉它还在抽动."  --猫尾
DESCRIBE.DEADLYFEAST = "我，我要忍住这诱惑……"  --致命盛宴
DESCRIBE.ARMOR_SANITY = "这件防弹衣……完全不科学"  --暗影盔甲
DESCRIBE.ARMORGRASS = "几乎没有防御能力"  --草制盔甲
DESCRIBE.ARMORRUINS = "可以轻松挡住子弹."  --铥矿甲胄
DESCRIBE.BONESHARD = "枪下亡魂，化作骨片."  --骨片
DESCRIBE.FLOWER_CAVE = "这下可以在洞穴中瞄准目标了"  --荧光草
DESCRIBE.COMPASS.GENERIC = "我得不到读数"  --指南针
DESCRIBE.COMPASS.S = "南边."  --指南针
DESCRIBE.COMPASS.SE = "东南方向."  --指南针
DESCRIBE.COMPASS.E = "东边."  --指南针
DESCRIBE.COMPASS.W = "西边."  --指南针
DESCRIBE.COMPASS.NE = "东北方向."  --指南针
DESCRIBE.COMPASS.SW = "西南方向."  --指南针
DESCRIBE.COMPASS.NW = "西北方向."  --指南针
DESCRIBE.COMPASS.N = "北边."  --指南针
-------abcdefg--------	
DESCRIBE.LAVA_POND_ROCK6 = "这个石头怎么看都是片麻岩."  --
DESCRIBE.MOLEHILL = "多温馨的一个住所啊!"  --洞穴
DESCRIBE.JELLYFISH_PLANTED = "虽然很可爱，但是很危险."  --水母
DESCRIBE.LUREPLANT = "小圆很喜欢这种植物."  --肉球茎
DESCRIBE.MERM = "一枪打不死!"  --鱼人
DESCRIBE.MERMHOUSE.GENERIC = "危险的气息"  --
DESCRIBE.MERMHOUSE.BURNT = "这下没有怪物住在里面了."  --烧焦的
DESCRIBE.LIVINGTREE = "好像有些名堂"  --完全正常的树
DESCRIBE.ICEPACK = "它到底是怎么保鲜的……"  --隔热包
DESCRIBE.MARSH_PLANT_TROPICAL = "好多."  --植物
DESCRIBE.KNIGHTBOAT = "它的舰炮太低级了"  --浮船骑士
DESCRIBE.HONEYNUGGETS = "吃起来像鸡肉,但我不认为它是."  --甜蜜金砖
DESCRIBE.MINIFAN = "不知何故,微风出来后快一倍."  --
DESCRIBE.KOALEFANT_SUMMER = "非常可口"  --考拉象
DESCRIBE.MANRABBIT_TAIL = "小圆，你也摸摸看吧"  --兔毛
DESCRIBE.MUSSEL_BED = "下面似乎有好吃的"  --贻贝床
DESCRIBE.HARPOON = "它的穿透力比子弹还强！"  --鱼叉
DESCRIBE.LAVAPOOL = "这烈焰仿佛要刺穿我的灵魂宝石."  --熔岩池
DESCRIBE.MULTITOOL_AXE_PICKAXE = "这个玩意太棒了!"  --挖/砍工具
DESCRIBE.MINERHAT = "会不会太显眼了？"  --矿工帽
DESCRIBE.NIGHTMARELIGHT = "我想知道那个功能是干什么用的."  --梦魇灯
DESCRIBE.MEATRACK.DRYING = "这比买风干肉便宜多了"  --晒肉架
DESCRIBE.MEATRACK.DONE = "小圆，吃肉干……她不在啊"  --晒肉架
DESCRIBE.MEATRACK.BURNT = "好可惜"  --晒肉架
DESCRIBE.MEATRACK.GENERIC = "我得把肉晒干"  --晒肉架
DESCRIBE.MEATRACK.DRYINGINRAIN = "这得多久才能干啊"  --晒肉架
DESCRIBE.MINOTAUR = "那东西看起来不是很高兴啊."  --远古守卫者
DESCRIBE.MUSHTREE_TALL.GENERIC = "那蘑菇太大了~~~"  --蓝色蘑菇树
DESCRIBE.MUSHTREE_TALL.BLOOM = "你在远处说的话我听不到,但是我能闻得到你."  --蓝色蘑菇树
DESCRIBE.MANGROVETREE = "我想知道它是否喝够水了?"  --红树林
DESCRIBE.MONKEYBALL = "去玩吧，别来烦我"  --愚猴球
DESCRIBE.MOLEHAT = "就像魔女的视界一样"  --鼹鼠帽
DESCRIBE.MOONROCKNUGGET = "我觉得有必要去抓只向尾猫!"  --
DESCRIBE.MARSH_BUSH.GENERIC = "小圆小心，有刺"  --尖刺灌木
DESCRIBE.MARSH_BUSH.PICKED = "啊，我没管住手."  --尖刺灌木
DESCRIBE.MARSH_BUSH.BURNING = "这下没次了"  --尖刺灌木
DESCRIBE.MANDRAKE.GENERIC = "……活的？"  --曼德拉草
DESCRIBE.MANDRAKE.PICKED = "其实我很危险。"  --曼德拉草
DESCRIBE.MANDRAKE.DEAD = "或许能保我一命"  --曼德拉草
DESCRIBE.KILLERBEE.GENERIC = "霰弹枪一发会死几只呢？"  --杀人蜂
DESCRIBE.KILLERBEE.HELD = "没比子弹大多少"  --杀人蜂
DESCRIBE.LIMESTONE = "勉强能抗住子弹吧."  --石灰石
DESCRIBE.LIMPETS_COOKED = "很鲜"  --熟帽贝
DESCRIBE.INVENTORYMOUND ="千万小心，我可不想躺在这里"  --坟墓
DESCRIBE.LOBSTERHOLE = "躲在水里，子弹很难打中"  --龙虾的巢穴
DESCRIBE.HEATROCK.GENERIC = "恶劣环境中很需要这个东西"  --热能石
DESCRIBE.HEATROCK.HOT = "这下能握住枪了"  --热能石
DESCRIBE.HEATROCK.FROZEN = "像是在摸灵魂宝石."  --热能石
DESCRIBE.HEATROCK.WARM = "暖暖的，像小圆的xi……手."  --热能石
DESCRIBE.HEATROCK.COLD = "但还是不能替代防晒霜"  --热能石
DESCRIBE.MOUND.DUG = "对不起，我需要活下去"  --坟墓
DESCRIBE.MOUND.GENERIC = "……要不要拿走呢"  --坟墓
DESCRIBE.NEEDLESPEAR = "太脆了，华而不实."  --仙人掌刺
DESCRIBE.LEIF = "一枪爆头恐怕也打不死……"  --树精守卫
DESCRIBE.MOOSE_NESTING_GROUND = "有必要引起重视一下这里面的东西."  --
DESCRIBE.MYSTERYMEAT = "这东西绝对不能吃."  --胆汁盖肉
DESCRIBE.MONSTERLASAGNA = "看着就感觉有毒."  --怪物千层饼
DESCRIBE.MONSTERTARTARE = "这附近有些别的东西可以吃."  --怪物鞑靼
DESCRIBE.MAGMAROCK_GOLD_FULL = "淘金者和手枪是一对好伙伴."  --
DESCRIBE.MAGMAROCK_FULL = "火药的必要原料就在这里了."  --
DESCRIBE.KRAKEN_TENTACLE = "擒贼先擒王！"  --呱肯海妖的触手
DESCRIBE.LIGHTNINGGOATHORN = "好像能导电."  --伏特羊角
DESCRIBE.KRAKENCHEST = "里面会有什么武器呢."  --深渊宝箱
DESCRIBE.MUSHTREE_MEDIUM.GENERIC = "这些玩意过去在我的浴室里也长过."  --红色蘑菇树
DESCRIBE.MUSHTREE_MEDIUM.BLOOM = "我对此感到有点冒犯."  --红色蘑菇树
DESCRIBE.KRAKEN = "枪枪爆头，带走它!"  --呱肯海妖
DESCRIBE.LAVA_POND_ROCK3 = "这个石头怎么看都是片麻岩."  --
DESCRIBE.KNIGHT = "去看看怎么回事!"  --发条骑士
DESCRIBE.LOBSTERDINNER = "听说有个大军火商很喜欢它"  --龙虾正餐
DESCRIBE.MAXWELLLIGHT = "我很奇怪它们是怎么工作的."  --麦斯威尔之光
DESCRIBE.MESSAGEBOTTLE = "里面一定写着一个军火库的地址"  --瓶中信
DESCRIBE.MOSSLING = "它会把我的军需品洗劫一空，干掉它！"  --幼鹿角鹅
DESCRIBE.HOUNDBONE = "不是我打死的"  --尸骨
DESCRIBE.HORN = "高级战利品"  --牛角
DESCRIBE.JUNGLETREE.BURNT = "我想我本来可以阻止的."  --丛林树
DESCRIBE.JUNGLETREE.CHOPPED = "还有利用价值"  --丛林树
DESCRIBE.JUNGLETREE.GENERIC = "那棵树需要理发."  --丛林树
DESCRIBE.JUNGLETREE.BURNING = "制造木炭中."  --丛林树
DESCRIBE.HAMBAT = "这东西的威力怎么会这么强"  --火腿棒
DESCRIBE.LEIF_SPARSE = "他很庞大!"  --树精守卫
DESCRIBE.HEALINGSALVE = "帮我省点魔力"  --治疗药膏
DESCRIBE.LAVAE_PET.GENERIC = "似乎暂时没有攻击性"  --
DESCRIBE.LAVAE_PET.STARVING = "喂它一点东西吧"  --
DESCRIBE.LAVAE_PET.CONTENT = "它似乎很快乐."  --
DESCRIBE.LAVAE_PET.HUNGRY = "饿了么？开美团吧"  --
DESCRIBE.LAVAE_EGG_CRACKED.COLD = "它在出生前就要冻死了"  --严寒
DESCRIBE.LAVAE_EGG_CRACKED.COMFY = "它很期待这个世界吧."  --
DESCRIBE.LOBSTER_DEAD_COOKED = "你在冒着香气."  --美味的龙虾
DESCRIBE.HAWAIIANSHIRT = "它不安全!"  --花纹衬衫
DESCRIBE.ICEHAT = "让我冷静一下吧."  --冰块
DESCRIBE.MOSQUITOSACK_YELLOW = "或许我该好好研究一下这种东西."  --黄蚊子血袋
DESCRIBE.MUSSEL_FARM.GENERIC = "我不知道它们是从布鲁塞尔来的."  --青口贝
DESCRIBE.MUSSEL_FARM.STICKPLANTED = "再等等。"  --青口贝
DESCRIBE.LIGHTNING_ROD.GENERIC = "当心雷暴损害"  --避雷针
DESCRIBE.LIGHTNING_ROD.CHARGED = "雷电伤不到我"  --避雷针
DESCRIBE.LOBSTER_DEAD = "烤着吃应该不错."  --死了的龙虾
DESCRIBE.INSANITYROCK.INACTIVE = "它看上去更像一座金字塔,而不是方尖碑"  --方尖碑
DESCRIBE.INSANITYROCK.ACTIVE = "小心!"  --方尖碑
DESCRIBE.MONSTERMEAT_DRIED = "勉强能吃了."  --怪兽肉干
DESCRIBE.MERMFISHER = "打渔似乎只是它的爱好而已，其实它是素食者."  --鱼人渔夫
DESCRIBE.MAXWELLLOCK = "看起来就像一个钥匙孔."  --噩梦锁头
DESCRIBE.MAGMAROCK_GOLD = "有金子，但是没有交易人"  --熔岩金矿
DESCRIBE.NIGHTMARE_TIMEPIECE.WAXING = "我觉得它变得更浓了!"  --铥矿徽章
DESCRIBE.NIGHTMARE_TIMEPIECE.NOMAGIC = "这里可没有魔法."  --铥矿徽章
DESCRIBE.NIGHTMARE_TIMEPIECE.WANING = "貌似它正在减少."  --铥矿徽章
DESCRIBE.NIGHTMARE_TIMEPIECE.WARN = "这里正在变得越来越魔幻了."  --铥矿徽章
DESCRIBE.NIGHTMARE_TIMEPIECE.DAWN = "梦魇就要结束了!"  --铥矿徽章
DESCRIBE.NIGHTMARE_TIMEPIECE.STEADY = "貌似可以稳得住."  --铥矿徽章
DESCRIBE.NIGHTMARE_TIMEPIECE.CALM = "一切都好."  --铥矿徽章
DESCRIBE.MAGMAROCK = "挖出硝石，做成火药"  --熔岩矿
DESCRIBE.MOOSE = "不能轻易打死，那群小宝宝更难对付."  --
DESCRIBE.IRONWIND = "它的能量到底来自于哪里？."  --铁风发动机
DESCRIBE.HOTCHILI = "好，好辣"  --辣椒酱
DESCRIBE.JELLYFISH_COOKED = "不太想吃这个……."  --熟水母
DESCRIBE.JUNGLETREESEED.GENERIC = "我能听见小蛇的嘶嘶声."  --
DESCRIBE.JUNGLETREESEED.PLANTED = "它会长成很好的丛林树."  --
DESCRIBE.MUSSEL_COOKED = "烤了才好吃"  --熟青口贝
DESCRIBE.LAVA_POND_ROCK7 = "这个石头怎么看都是片麻岩."  --
DESCRIBE.MAGIC_SEAL = "好像没啥用."  --魔法豹印
DESCRIBE.HOUNDSTOOTH = "好锋利!"  --狗牙
DESCRIBE.LICHEN = "只有蓝藻才能在这种光线下生存."  --洞穴苔藓
DESCRIBE.MUSSELBOUILLABAISE = "想象我可以运行它的实验!"  --贻贝普罗旺斯鱼汤
DESCRIBE.ICEMAKER.OUT = "它需要更多燃料."  --制冰机3000
DESCRIBE.ICEMAKER.NORMAL = "运行着呢."  --制冰机3000
DESCRIBE.ICEMAKER.VERYLOW = "我听见里面有点噼啪声."  --制冰机3000
DESCRIBE.ICEMAKER.LOW = "它看起来在减速生产."  --制冰机3000
DESCRIBE.ICEMAKER.HIGH = "运行良好!"  --制冰机3000
DESCRIBE.MANGROVETREE_BURNT = "我真想知道这是怎么发生的."  --
DESCRIBE.LAVA_POND_ROCK4 = "As gneiss a place as any."  --
DESCRIBE.MOSQUITO.GENERIC = "恶心的小吸血鬼"  --蚊子
DESCRIBE.MOSQUITO.HELD = "原来我还是有血液的"  --蚊子
DESCRIBE.NUBBIN = "我要好好利用它。"  --珊瑚种子
DESCRIBE.LIMPETS = "可能挨饿没那么糟糕."  --帽贝
DESCRIBE.LAVASPIT.COOL = "我喜欢把它叫成\"丽娃\"."  --龙蝇唾液
DESCRIBE.LAVASPIT.HOT = "好烫！"  --龙蝇唾液
DESCRIBE.MINOTAURHORN = "再来撞我啊"  --守卫者的角
DESCRIBE.MACHETE = "太笨重，不适合携带"  --砍刀
DESCRIBE.MONSTERMEAT = "呃,我可不想吃那个."  --怪兽肉
DESCRIBE.HAIL_ICE = "上次在魔女结界里见过类似的东西."  --冰雹
DESCRIBE.NIGHTLIGHT = "它发出可怕的光"  --暗夜照明灯
DESCRIBE.JAMMYPRESERVES = "就这么吞下去吧， 能充饥."  --果酱蜜饯
DESCRIBE.MARSH_TREE.BURNT = "现在它已经被烧毁了而且到处都是刺."  --针叶树
DESCRIBE.MARSH_TREE.CHOPPED = "现在没那么尖了!"  --针叶树
DESCRIBE.MARSH_TREE.GENERIC = "那些刺看起来很尖!"  --针叶树
DESCRIBE.MARSH_TREE.BURNING = "烧炭!"  --针叶树
DESCRIBE.MAXWELLHEAD = "我可以看穿他的毛孔"  --麦斯威尔之首
DESCRIBE.INVENTORYGRAVE = "这儿在我之前有人来过了!"  --墓碑
DESCRIBE.LAVA_POND_ROCK = "这个石头怎么看都是片麻岩."  --
DESCRIBE.LIGHTBULB = "可以用于照明"  --荧光果
DESCRIBE.KRAMPUS_SACK = "坚实的大包"  --坎普斯背包
DESCRIBE.LIVINGJUNGLETREE = "看得我很像来一枪."  --正常的丛林树
DESCRIBE.MOSQUITO_POISON = "我该备点青蒿素."  --毒蚊子
DESCRIBE.MESSAGEBOTTLEEMPTY = "只是一个空瓶子."  --空瓶子
DESCRIBE.NIGHTMAREFUEL = "这是燃料？"  --噩梦燃料
DESCRIBE.LOGRAFT = "这看起来...有点像船..."  --木筏
DESCRIBE.MALE_PUPPET = "他被困住了!"  --
DESCRIBE.LIMPETROCK.GENERIC = "我能用这堆蜗牛装满一个桶."  --帽贝岩
DESCRIBE.LIMPETROCK.PICKED = "没有蜗牛我可就装不满桶了."  --帽贝岩
DESCRIBE.LAVAE_TOOTH = "这是一个卵齿！"  --
DESCRIBE.JELLYFISH_DEAD = "我说了别电我"  --死水母
DESCRIBE.JELLYFISH = "你不要电我啊"  --水母
DESCRIBE.HONEYHAM = "甜蜜的开胃菜."  --蜜汁火腿
DESCRIBE.LAVAE_EGG.GENERIC = "里面流出一股暖流."  --
DESCRIBE.LAVA_POND_ROCK5 = "这个石头怎么看都是片麻岩."  --
DESCRIBE.MUSSEL = "如果它们能稍微松一点就好了."  --青口贝
DESCRIBE.MUSSEL_STICK = "它能提供我一天的补给."  --采贝器
DESCRIBE.HOUND = "不要伤害小圆！也别咬我！"  --猎犬
DESCRIBE.HOUNDFIRE = "着火了!着火了!"  --火
DESCRIBE.KRAMPUS = "惩罚坏孩子吗？可惜，魔法少女不归你管"  --坎普斯
DESCRIBE.KNIGHT_NIGHTMARE = "这是个梦魇!"  --损坏的骑士
DESCRIBE.JELLYOPOP = "有点麻，是错觉吗"  --果冻冰淇淋
DESCRIBE.LOBSTERBISQUE = "好想让小圆也来一碗."  --龙虾浓汤
DESCRIBE.LIVINGLOG = "魔力反应很强"  --有生命的木材
DESCRIBE.LAVA_POND_ROCK2 = "这个石头怎么看都是片麻岩."  --
DESCRIBE.ICESTAFF = "射出蓝色的子弹."  --冰魔杖
DESCRIBE.MARSH_PLANT = "这是植物"  --植物
DESCRIBE.LIGHTNINGGOAT.GENERIC = "它一直在发出“咩啊啊”的声音！"  --伏特羊
DESCRIBE.LIGHTNINGGOAT.CHARGED = "活着的避雷针."  --伏特羊
DESCRIBE.LITTLE_WALRUS = "就像魔法少女的未来一样，这家伙不可久留"  --小海象
DESCRIBE.LANTERN = "更具文明气息的光亮"  --提灯
DESCRIBE.MOOSEEGG = "它里面的东西像要逃逸的电子一样."  --
DESCRIBE.MARBLEPILLAR = "我看我能用得上它"  --大理石柱子
DESCRIBE.MAXWELL = "我讨厌那个家伙."  --麦斯威尔
DESCRIBE.LOCKEDWES = "麦斯威尔把他石化了"  --维斯
DESCRIBE.NIGHTSTICK = "电!"  --晨星
DESCRIBE.MARBLETREE = "我不觉得斧子能劈开它"  --大理石树
DESCRIBE.ICE = "要是麻美也像你一样冷静就好了"  --冰
DESCRIBE.MUSHTREE_TALL_WEBBED = "蜘蛛认为这是很重要的."  --
DESCRIBE.LUGGAGECHEST = "这看起来像是老式蒸汽货车."  --行李箱
DESCRIBE.LUREPLANTBULB = "现在我终于可以建立我第一个肉农场了."  --多肉的球茎
DESCRIBE.MINOTAURCHEST = "这里面一定有一批高端的军火."  --大豪华宝箱
DESCRIBE.LOG.GENERIC = "它大,它重,它是木头的"  --木材
DESCRIBE.LOG.BURNING = "好烫的木头!"  --木材
DESCRIBE.LUMPY_SAPLING = "这棵树是怎么繁殖的？"  --
DESCRIBE.MERMHOUSE_FISHER = "闻起来可不怎么样."  --渔夫的小屋
DESCRIBE.MEATBALLS = "我自己煮的，小圆你尝尝？啊小圆不在"  --肉丸
DESCRIBE.LAVA_POND = "高尚的!"  --
DESCRIBE.NITRE = "每一颗硝石都会变成火药"  --硝石
DESCRIBE.KOALEFANT_WINTER = "枪械的发明使得这些强大的生物也无法对抗人类"  --考拉象
DESCRIBE.JELLYJERKY = "好像味道变好了一些."  --干水母
DESCRIBE.MANDRAKESOUP = "得找个安全的地方才能喝."  --曼德拉草汤
DESCRIBE.MOSQUITOSACK = "这袋子或许能装点子弹"  --蚊子血袋
DESCRIBE.ICECREAM = "第二杯半价！好吧我知道小圆不在。"  --冰淇淋
DESCRIBE.MERMHEAD.GENERIC = "真是臭死了,我还要闻一整天"  --鱼人头
DESCRIBE.MERMHEAD.BURNT = "烧焦的野兽肉闻起来更糟糕了."  --鱼人头
DESCRIBE.MAXWELLPHONOGRAPH = "这些音乐是从那里来的."  --麦斯威尔的留声机
DESCRIBE.MEAT = "它正一点点变质,但是没问题"  --肉
DESCRIBE.MAXWELLTHRONE = "他看起来不舒服啊."  --噩梦王座
DESCRIBE.LAVAE = "摸上去太热了."  --
DESCRIBE.MOLE.UNDERGROUND = "别偷我的子弹."  --鼹鼠
DESCRIBE.MOLE.HELD = "你刚才是不是对我的子弹有想法来着？."  --鼹鼠
DESCRIBE.MOLE.ABOVEGROUND = "算了，还是别在它身上浪费子弹了."  --鼹鼠
DESCRIBE.MEAT_DRIED = "这个世界里少有的美食了."  --肉干
DESCRIBE.MARBLE = "子弹打上去恐怕要跳弹"  --大理石
DESCRIBE.MANDRAKE_COOKED = "它看起来不再那么奇怪了"  --
DESCRIBE.KABOBS = "在棍子上的午餐."  --肉串
DESCRIBE.ICEHOUND = "这体温……怎么可能存活"  --蓝色猎犬
DESCRIBE.ICEBOX = "军备物资存放点"  --冰箱
DESCRIBE.HOME = "一定有人住在这"  --
DESCRIBE.HONEYCOMB = "最好别捅它"  --蜂巢
DESCRIBE.HONEY = "用途很多"  --蜂蜜
DESCRIBE.HOMESIGN.GENERIC = "它说「你在这里.」"  --指示牌
DESCRIBE.HOMESIGN.UNWRITTEN = "指示牌还没人写过~"  --指示牌
DESCRIBE.HOMESIGN.BURNT = "文字看不清了."  --指示牌
DESCRIBE.HAMMER = "机制破坏性的体现"  --锤子
DESCRIBE.LOBSTER = "再跑就打死你……算了没必要."  --龙虾
DESCRIBE.NIGHTSWORD = "唔……这把剑让我有点恐慌"  --暗影之剑
DESCRIBE.HOUNDMOUND = "出来一只我就打死一只."  --猎犬丘
DESCRIBE.MUSHTREE_SMALL.GENERIC = "一个神奇的蘑菇？"  --绿色蘑菇树
DESCRIBE.MUSHTREE_SMALL.BLOOM = "它在试图繁殖."  --绿色蘑菇树
DESCRIBE.MONKEY = "别让他们把军火都走了."  --暴躁猴
DESCRIBE.MONKEYBARREL = "像个游击队的据点"  --暴躁猴窝
-------hijklmn--------	
DESCRIBE.QUACKERINGRAM = "我的创造力是没有界限的吗？！"  --海妖之锤
DESCRIBE.SPORE_TALL = "它在到处飘~~"  --
DESCRIBE.PINECONE.GENERIC = "我可以听见里面有一棵小树,努力想长出来"  --松果
DESCRIBE.PINECONE.PLANTED = "我很快就要变成一棵树了."  --松果
DESCRIBE.PIRATEPACK = "我可以把我的战利品放这里."  --赃物袋
DESCRIBE.PALMLEAF_UMBRELLA = "小圆，一起回家吧？."  --热带遮阳伞
DESCRIBE.TWIGS = "它是一堆小树枝"  --小树枝
DESCRIBE.SUPERTELESCOPE = "让近视眼变成远视眼"  --EX望远镜
DESCRIBE.PLANTMEAT = "小圆，这东西能吃吗？."  --多叶的肉
DESCRIBE.RED_CAP = "闻起来不错"  --红菇头
DESCRIBE.TRAP_TEETH_MAXWELL = "我可不想踩在那上面!"  --麦斯威尔的狗牙陷阱
DESCRIBE.RAINHAT = "头发如果湿了，就撩不起来了."  --雨帽
DESCRIBE.RUINSHAT = "更适合小圆"  --铥矿皇冠
DESCRIBE.RABBITHOUSE.GENERIC = "那可不是真的胡萝卜"  --兔子窝
DESCRIBE.RABBITHOUSE.BURNT = "这可不算烤萝卜"  --兔子窝
DESCRIBE.THULECITE = "这是一种稀土金属……啥？"  --铥矿
DESCRIBE.SAPLING.WITHERED = "要是凉点就好了."  --树苗
DESCRIBE.SAPLING.PICKED = "他尝到教训了"  --树苗
DESCRIBE.SAPLING.GENERIC = "小树苗如此可爱!"  --树苗
DESCRIBE.SAPLING.BURNING = "烧的好快!"  --树苗
DESCRIBE.TENTACLE_PILLAR_ARM = "小巧而不稳定的武器."  --小触手
DESCRIBE.SLURTLESLIME = "易燃易爆，做成炸药吧"  --蜗龟粘液
DESCRIBE.SPORE_SMALL_INV = "我可以在我的口袋里留一点光."  --
DESCRIBE.PIGGUARD = "他看起来不像其他人一样友善."  --猪人守卫
DESCRIBE.OXHAT = "又漂亮又干燥.这个头盔可以保护我的脑袋."  --角状头盔
DESCRIBE.POWCAKE = "我不认为自己饿到想吃下它"  --芝士蛋糕
DESCRIBE.TURF_DRAGONFLY = "你想看看那是不是防火的吗?"  --
DESCRIBE.SHIPWRECKED_EXIT = "然后,我驶向地平线!"  --海之船送
DESCRIBE.PITCHFORK = "麦斯威尔或许正在找这东西呢."  --草叉
DESCRIBE.QUACKENDRILL = "只要钻一下，就步入现代化——怎么可能啊."  --海妖之钻
DESCRIBE.RAINOMETER.GENERIC = "它能测出天气阴沉的程度"  --雨量计
DESCRIBE.RAINOMETER.BURNT = "测量部件灰飞烟灭了."  --雨量计
DESCRIBE.SEEDS = "每一个都是个迷"  --种子
DESCRIBE.TROPICALBOUILLABAISSE = "只要喝上一口，海水就会避开我……这到底是什么魔法"  --热带鱼羹
DESCRIBE.TAR_TRAP = "我想知道谁把它清理干净？"  --焦油陷阱
DESCRIBE.TARSUIT = "为了保持干燥，凑合穿吧。"  --焦油套装
DESCRIBE.TALLBIRD = "瞄准那只眼睛，两枪带走吧"  --高脚鸟
DESCRIBE.TARLAMP = "真是一个漂亮的灯。"  --焦油灯
DESCRIBE.TURF_CHECKERFLOOR = "这些非常时髦"  --方格地板
DESCRIBE.SPIDER.GENERIC = "蜘蛛有时候比大怪物要难缠"  --蜘蛛
DESCRIBE.SPIDER.SLEEPING = "逐个击破吧"  --蜘蛛
DESCRIBE.SPIDER.DEAD = "终究扛不住子弹"  --蜘蛛
DESCRIBE.SEA_CHIMINEA.GENERIC = "科学保护我的火焰。"  --漂浮火炉
DESCRIBE.SEA_CHIMINEA.OUT = "它还是熄灭了。"  --漂浮火炉
DESCRIBE.SEA_CHIMINEA.EMBERS = "得在它熄灭之前放点燃料进去。"  --漂浮火炉
DESCRIBE.SEA_CHIMINEA.HIGH = "我很高兴我们被水围绕着。"  --漂浮火炉
DESCRIBE.SEA_CHIMINEA.LOW = "火焰变小了。"  --漂浮火炉
DESCRIBE.SEA_CHIMINEA.NORMAL = "和它一样舒适。"  --漂浮火炉
DESCRIBE.ROBIN_WINTER.GENERIC = "寒荒之地的生命"  --雪雀
DESCRIBE.ROBIN_WINTER.HELD = "它如此柔软"  --雪雀
DESCRIBE.SEA_YARD.LOWFUEL = "我要快点装满它。"  --海之基地
DESCRIBE.SEA_YARD.ON = "做好万全准备，包括载具"  --海之基地
DESCRIBE.SEA_YARD.OFF = "它现在不是井井有条的。"  --海之基地
DESCRIBE.ROE_COOKED = "煎鱼籽。"  --煮熟的鱼籽
DESCRIBE.SWEATERVEST = "小圆也给我做过这样一件背心"  --小巧背心
DESCRIBE.SPIDERQUEEN = "就像操控使魔的魔女"  --蜘蛛女王
DESCRIBE.ROE = "鱼卵。"  --鱼卵
DESCRIBE.RUINS_RUBBLE = "可以修复."  --损毁的废墟
DESCRIBE.TRAWLNETDROPPED.SOON = "这绝对是在下沉."  --拖网
DESCRIBE.TRAWLNETDROPPED.SOONISH = "会不会是捞到了一把枪？"  --拖网
DESCRIBE.TRAWLNETDROPPED.GENERIC = "海上……应该捞不到军火吧"  --拖网
DESCRIBE.RESURRECTIONSTATUE.GENERIC = "多么帅气的恶魔啊!"  --肉块雕像
DESCRIBE.RESURRECTIONSTATUE.BURNT = "再也不能用了."  --肉块雕像
DESCRIBE.SPEARGUN = "这枪太不方便了，但是威力好大"  --矛枪
DESCRIBE.RED_MUSHROOM.GENERIC = "这是一个杏子色的蘑菇"  --红蘑菇
DESCRIBE.RED_MUSHROOM.INGROUND = "它好像睡着了!"  --红蘑菇
DESCRIBE.RED_MUSHROOM.PICKED = "我想知道它会不会长回来?"  --红蘑菇
DESCRIBE.STALAGMITE_TALL_LOW = "石头,石头,石头,石头......"  --
DESCRIBE.TREEGUARD = "这家伙也是军火发烧友"  --椰树守卫
DESCRIBE.ROCK_ICE.GENERIC = "孤寂的冰川."  --迷你冰川
DESCRIBE.ROCK_ICE.MELTED = "它结冰的时候才有点用."  --迷你冰川
DESCRIBE.REFLECTIVEVEST = "能凉快一点吧"  --夏季背心
DESCRIBE.POISONCROCODOG = "有毒，千万小心"  --黄色鳄狗
DESCRIBE.TURF_FOREST = "一块土地"  --森林草皮
DESCRIBE.RAINBOWJELLYJERKY = "对不起，我得吃了你"  --风干彩虹水母
DESCRIBE.RAINBOWJELLYFISH_COOKED = "还是这么色彩斑斓吗"  --煮熟的彩虹水母
DESCRIBE.TRUNKVEST_WINTER = "冬季生存装备"  --寒冬背心
DESCRIBE.TURF_SAVANNA = "一块土地"  --热带草原草皮
DESCRIBE.SAIL = "马力不足，凑合用一下吧."  --草帆
DESCRIBE.RAINBOWJELLYFISH_PLANTED = "没有攻击性"  --彩虹水母
DESCRIBE.RAINBOWJELLYFISH = "安全的食物来源"  --彩虹水母
DESCRIBE.SPORE_MEDIUM_INV = "我可以在我的口袋里留一点光."  --
DESCRIBE.PICKAXE = "据说矿工很喜欢用这武器，但不适合我"  --鹤嘴锄
DESCRIBE.SUNKEN_BOAT_TRINKET_5 = "运势差了点"  --旧靴子
DESCRIBE.PENGUIN = "需要密集的火力才能击败他们"  --企鸥
DESCRIBE.TURF_BADLANDS = "又是一种新地形"  --
DESCRIBE.SHIPWRECKED_ENTRANCE = "能通过这个离开这里吗？"  --海之船送
DESCRIBE.OBSIDIAN = "它似乎富含魔力"  --十胜石
DESCRIBE.PUMPKIN_SEEDS = "它是一个南瓜子."  --南瓜种子
DESCRIBE.POTTEDFERN = "盆子里的蕨类植物."  --蕨类植物盆栽
DESCRIBE.RUBBLE = "只是碎石砾而已."  --
DESCRIBE.TENTACLE_PILLAR = "一个泥坑."  --大触手
DESCRIBE.TELEPORTATO_POTATO = "这是steam的服务器吗？"  --金属土豆零件
DESCRIBE.STAFF_TORNADO = "这种风力下，子弹几乎不可能打偏"  --旋风
DESCRIBE.SWORDFISH = "你确定要挑战我吗？"  --旗鱼
DESCRIBE.PURPLEAMULET = "它在对我低语."  --梦魇护符
DESCRIBE.TEENBIRD.GENERIC = "不是一只很高的鸟"  --小高脚鸟
DESCRIBE.TEENBIRD.HUNGRY = "我最好给它找些食物"  --小高脚鸟
DESCRIBE.TEENBIRD.STARVING = "它眼中闪耀着危险."  --小高脚鸟
DESCRIBE.SNAKESKINHAT = "这能从我头发上击退雨."  --蛇鳞帽
DESCRIBE.TURF_TIDALMARSH = "沼泽地毯."  --潮滩地皮
DESCRIBE.TURF_FUNGUS = "又是一种新地形"  --菌类草地
DESCRIBE.TURF_MAGMAFIELD = "岩浆地毯."  --岩浆地皮
DESCRIBE.TRINKET_22 = "我很确定有人想要这个."  --酒瓶蜡烛
DESCRIBE.TRINKET_10 = "我希望能在需要用到这些东西之前就能离开这里."  --二手假牙
DESCRIBE.TRINKET_21 = "我应该测量它来确定它的规模."  --玩具船
DESCRIBE.TRINKET_20 = "我不确定是什么,但是让我感觉更聪明!"  --六分仪
DESCRIBE.STALAGMITE_MED = "我看它就是块石头"  --
DESCRIBE.TREASURECHEST_TRAP = "多方便啊!"  --宝箱陷阱
DESCRIBE.TURF_FUNGUS_RED = "真菌红地毯."  --菌类草地
DESCRIBE.SPEAR_LAUNCHER = "装填然后射击……好像也不错"  --矛枪
DESCRIBE.SNAKESKINSAIL = "爬上去然后出发!"  --蛇皮帆
DESCRIBE.SUNKEN_BOAT.GENERIC = "那个家伙看起来很想说话."  --沉船
DESCRIBE.SUNKEN_BOAT.ABANDONED = "这就是为什么我讨厌水的原因."  --沉船
DESCRIBE.SANDBAGSMALL_ITEM = "可以堆成掩体"  --沙袋
DESCRIBE.PIRATEGHOST = "你是被子弹打死的吗？"  --海盗的鬼魂
DESCRIBE.POND_ALGAE = "在池塘里的一些水藻."  --水藻
DESCRIBE.SNAKE = "子弹很难命中它"  --蛇
DESCRIBE.PEG_LEG = "我可以表演截肢如果有人想戴上它."  --假腿
DESCRIBE.OX_HORN = "我用号角抓住了牛."  --角
DESCRIBE.TURF_SINKHOLE = "又是一种新地形"  --泥泞的地皮
DESCRIBE.TURF_JUNGLE = "非常粗糙的地皮."  --丛林地皮
DESCRIBE.SPIDERHOLE_ROCK = "把有年岁的带子镶在上面."  --
DESCRIBE.ROCK = "用子弹爆破显然不现实"  --
DESCRIBE.TURF_WOODFLOOR = "这些是地板"  --木质地板
DESCRIBE.ROCKY = "看来很难用枪械击败他"  --岩石大龙虾
DESCRIBE.PETALS_EVIL = "充满了魔力，但是没有叹息之种"  --恶魔花瓣
DESCRIBE.PANDORASCHEST = "它里面可能会有很神奇的东西,也可能会有很恐怖的东西."  --装饰箱
DESCRIBE.STEELWOOL = "或许可以做成防弹衣。"  --Steel Wool
DESCRIBE.TENT.GENERIC = "多久没睡个好觉了？"  --帐篷
DESCRIBE.TENT.BURNT = "没东西作铺盖了."  --帐篷
DESCRIBE.TURF_SNAKESKINFLOOR = "时髦的叙述."  --蛇皮地毯
DESCRIBE.TREASURECHEST.GENERIC = "这是我有趣的皮箱!"  --宝箱
DESCRIBE.TREASURECHEST.BURNT = "箱子被烧毁了."  --宝箱
DESCRIBE.PLANT_NORMAL.GENERIC = "枝繁叶茂啊!"  --农作物
DESCRIBE.PLANT_NORMAL.READY = "嗯.准备收获了"  --农作物
DESCRIBE.PLANT_NORMAL.GROWING = "啊!它长得真慢!"  --农作物
DESCRIBE.PLANT_NORMAL.WITHERED = "它被热死了."  --农作物
DESCRIBE.TWISTER = "必须找好掩体再设计."  --豹卷风
DESCRIBE.ONEMANBAND = "小圆可以用这个参加超级女声"  --独奏乐器
DESCRIBE.POMEGRANATE_SEEDS = "它是一颗梨果种子."  --石榴种子
DESCRIBE.TELEPORTATO_SW_BASE = "我觉得它缺失了一些零件."  --木制平台
DESCRIBE.ROCK_CHARCOAL = "做成火药的必需品."  --煤矿
DESCRIBE.PARROT_PIRATE = "我试试不吃带名字的东西."  --
DESCRIBE.SEASHELL = "跟小圆一起捡贝壳的时光……"  --贝壳
DESCRIBE.TIDALPOOL = "潮汐留下的一个池塘."  --潮水池
DESCRIBE.TRINKET_18 = "一个逝去纪元的遗物!"  --古老的花瓶
DESCRIBE.TURF_ASH = "灰色的地皮"  --灰色的地皮
DESCRIBE.TRUNKVEST_SUMMER = "穿这样的衣服是不是有些随性了"  --夏日背心
DESCRIBE.PURPLEGEM = "魔力很强"  --紫宝石
DESCRIBE.PORTAL_SHIPWRECKED = "它坏了."  --出故障的新奇旅途
DESCRIBE.TOPHAT = "戴上这个的话，小圆会不会喜欢呢……"  --高礼帽
DESCRIBE.TELEPORTATO_SW_CRANK = "我奇怪这是用来做什么的."  --长满草的零件
DESCRIBE.TELEPORTATO_SW_BOX = "这看起来像某个东西的一部分."  --螺丝状零件
DESCRIBE.SPEAR = "相当古老的武器"  --长矛
DESCRIBE.SWEET_POTATO_SEEDS = "属于我的植物块茎."  --甘薯种子
DESCRIBE.PERD = "杀鸡焉用冲锋枪"  --雄火鸡
DESCRIBE.PHLEGM = "看着好恶心."  --Phlegm
DESCRIBE.SLURTLE_SHELLPIECES = "没有答案的谜题"  --破碎的背壳
DESCRIBE.SPIDERHAT = "我是女王……为何我有点享受这种感觉？"  --蜘蛛帽
DESCRIBE.TURF_MEADOW = "草甸风情地皮."  --草甸地皮
DESCRIBE.STINGER = "看起来很锋利!"  --蜂刺
DESCRIBE.OX_FLUTE = "它在滴?"  --滴水长管
DESCRIBE.TURF_GRASS = "一块土地"  --长草草皮
DESCRIBE.TRINKET_17 = "还有一个在哪?"  --旧靴子
DESCRIBE.RAWLING = "少废话"  --罗林
DESCRIBE.PACKIM_FISHBONE = "你跟得上我的步伐吗？"  --鱼骨
DESCRIBE.SHARK_FIN = "小圆建议我不要吃."  --鱼翅
DESCRIBE.PUMPKIN = "把它做成马车去接小圆吧"  --南瓜
DESCRIBE.SAND = "时间的奥秘蕴含其中"  --沙子
DESCRIBE.POOP = "为了蔬菜，忍一忍吧"  --便便
DESCRIBE.OCTOPUSCHEST = "抠门."  --章鱼箱子
DESCRIBE.OCTOPUSKING = "听说这里可以交易军火？"  --海盗章鱼
DESCRIBE.TRINKET_19 = "湿润的大脑.从来没有听说过..."  --脑云丸
DESCRIBE.SANDBAGSMALL = "不做成沙漏真浪费."  --沙袋
DESCRIBE.TRINKET_4 = "它一定是某种宗教制品"  --地精
DESCRIBE.TUNACAN = "这个罐头是哪儿来的?"  --金枪鱼罐头
DESCRIBE.PIGKING = "卖不卖军火？"  --猪王
DESCRIBE.PALMLEAF_HUT = "阴凉,棒棒的阴凉."  --椰叶小屋
DESCRIBE.TELEPORTATO_SW_POTATO = "是育碧家的，腾讯家的，还是V社的？"  --木制土豆零件
DESCRIBE.REDBARREL = "为什么我没法把里面的火药拿出来"  --火药桶
DESCRIBE.SEEDS_COOKED = "我把它们所有的活力都榨了出来!"  --烤种子
DESCRIBE.SEAGULL_WATER = "再叫我就开枪了"  --海鸥
DESCRIBE.OBSIDIANCOCONADE = "威力已经超过了现代的手榴弹"  --十胜石炸弹
DESCRIBE.SHARKITTENSPAWNER.GENERIC = "是那砂桩在打呼噜吗?"  --
DESCRIBE.SHARKITTENSPAWNER.INACTIVE = "这是一大堆沙子."  --
DESCRIBE.SHARK_GILLS = "防水性很好，适合做子弹袋."  --鲨鱼鳃
DESCRIBE.SHARKITTEN = "我对你的皮很感兴趣"  --猫鲨
DESCRIBE.SHARX = "这肉是给小圆的，滚开！"  --海狗
DESCRIBE.TURF_CARPETFLOOR = "出人意料的刺耳"  --地毯地板
DESCRIBE.TRINKET_7 = "我没有时间游戏和享乐!"  --球与奖杯
DESCRIBE.SURFNTURF = "我晓美焰就算……真香！"  --海鲜肉坪
DESCRIBE.TRINKET_1 = "它们都融合在一起了"  --融化的大理石
DESCRIBE.ORANGESTAFF = "我已经习惯于劳碌了."  --懒惰的探索者
DESCRIBE.ROCK_OBSIDIAN = "请它吃雷管"  --十胜石岩
DESCRIBE.TAFFY = "我一颗，小圆一颗~"  --太妃糖
DESCRIBE.SCORCHED_SKELETON = "哦,好可怕."  --
DESCRIBE.TRAP = "为了节省子弹……"  --陷阱
DESCRIBE.PIRATIHATITATOR.GENERIC = "扮演海盗吗？我的枪似乎太现代了."  --魔法海盗帽
DESCRIBE.PIRATIHATITATOR.BURNT = "火烧一把可不能解决命名问题啊..."  --魔法海盗帽
DESCRIBE.TELESCOPE = "这个不是瞄准镜..."  --望远镜
DESCRIBE.TRAWLNET = "除了网没别的."  --拖网
DESCRIBE.TROPICAL_FISH = "这鱼长得真有热带风情."  --热带鱼
DESCRIBE.SNAKE_FIRE = "那条蛇在燃烧吗?"  --Fire Snake
DESCRIBE.SWEET_POTATO = "看上去很好吃!"  --甘薯
DESCRIBE.RABBIT.GENERIC = "按说兔子应该不爱吃胡萝卜……"  --兔子
DESCRIBE.RABBIT.HELD = "可以直接吃，也可以做成耳罩……"  --兔子
DESCRIBE.SEAWEED_COOKED = "小圆，你尝尝我的手艺."  --烤海带
DESCRIBE.TRAILMIX = "丰盛纯天然的零食."  --水果杂烩
DESCRIBE.TURF_ROAD = "匆忙修饰的鹅卵石."  --卵石路
DESCRIBE.SLURTLE = "用枪很难击败它"  --蜗龟
DESCRIBE.SPORE_SMALL = "它在到处飘~~"  --
DESCRIBE.TREECLUMP = "就像有人不允许我去任何地方一样."  --
DESCRIBE.TRINKET_23 = "某个人失信于他的诺言."  --破碎的音频编码设备
DESCRIBE.PARROT = "跟我学：小圆天下第一！"  --鹦鹉
DESCRIBE.SEAGULL = "去!找别的陆地待着去!"  --海鸥
DESCRIBE.TURF_MARSH = "一块土地"  --沼泽草皮
DESCRIBE.PEACOCK = "站住，把毛交出来."  --孔雀
DESCRIBE.TOUCAN = "我不能抓到他."  --大嘴鸟
DESCRIBE.SNAKEDEN.BURNT = "我觉得我本能预防它的."  --藤蔓丛
DESCRIBE.SNAKEDEN.CHOPPED = "接招吧,大自然!"  --藤蔓丛
DESCRIBE.SNAKEDEN.GENERIC = "全是藤蔓!"  --藤蔓丛
DESCRIBE.SNAKEDEN.BURNING = "哎呀."  --藤蔓丛
DESCRIBE.SIESTAHUT.GENERIC = "睡午觉是不是太奢侈了"  --简易小木棚
DESCRIBE.SIESTAHUT.BURNT = "现在没什么树荫."  --简易小木棚
DESCRIBE.SPEAR_OBSIDIAN = "就算有魔力它也不过是一杆长矛."  --十胜石矛
DESCRIBE.SPEAR_POISON = "更像土著人了"  --毒矛
DESCRIBE.TENTACLE_PILLAR_HOLE = "似乎很臭,但值得探索."  --
DESCRIBE.SLURTLEHOLE = "一个令人想说“呕”的巢穴。"  --蜗龟土堆
DESCRIBE.SEASACK = "理想的子弹袋."  --海上麻袋
DESCRIBE.STALAGMITE_TALL_MED = "石头,石头,石头,石头......"  --
DESCRIBE.RAINCOAT = "保持干燥，别让子弹变哑弹"  --雨衣
DESCRIBE.TALLBIRDNEST.GENERIC = "那真是不一般的蛋!"  --高脚鸟巢穴
DESCRIBE.TALLBIRDNEST.PICKED = "巢是空的"  --高脚鸟巢穴
DESCRIBE.SANDHILL = "你最好别进我鞋子里."  --沙堆
DESCRIBE.TIGEREYE = "还看我不？"  --虎鲨之眼
DESCRIBE.PUMPKIN_LANTERN = "能做成马车吗……"  --南瓜灯
DESCRIBE.OBSIDIAN_WORKBENCH = "我感觉自己的灵感被激发了."  --十胜石工作台
DESCRIBE.TRINKET_8 = "很好.满足了我所有的需求……不是那种需求"  --硬化橡胶塞
DESCRIBE.PETALS = "可惜小圆不在花丛中等着我"  --花瓣
DESCRIBE.SNURTLE = "他不算很恶心,但还是恶心"  --黏糊虫
DESCRIBE.SPOILED_FOOD = "不能吃了"  --腐烂食物
DESCRIBE.TURF_CAVE = "又是一种新地形"  --鸟粪草地
DESCRIBE.SMALLBIRD.GENERIC = "原来刚出生的时候长成这样"  --小高鸟
DESCRIBE.SMALLBIRD.HUNGRY = "它看起来饿了"  --小高鸟
DESCRIBE.SMALLBIRD.STARVING = "它一定很饥饿"  --小高鸟
DESCRIBE.TRUNK_SUMMER = "一个轻松轻快的行李箱"  --红色象鼻
DESCRIBE.REEDS.GENERIC = "一簇芦苇"  --芦苇
DESCRIBE.REEDS.PICKED = "我采摘了所有有用的芦苇"  --芦苇
DESCRIBE.REEDS.BURNING = "这烧的真旺!"  --芦苇
DESCRIBE.TROPICALFAN = "狂风之中子弹的命中率会下降."  --热带风扇
DESCRIBE.STATUEGLOMMER.GENERIC = "不确定这是什么."  --格罗姆的雕像
DESCRIBE.STATUEGLOMMER.EMPTY = "我打烂了它.以科学的名义."  --格罗姆的雕像
DESCRIBE.RESURRECTIONSTONE = "没用的，如果魔力耗尽了，这块石头也救不了我."  --试金石
DESCRIBE.OBSIDIANAXE = "用的时候要小心一点……"  --十胜石斧
DESCRIBE.SEAWEED = "小圆说这个很有营养"  --海带
DESCRIBE.SPIDER_HIDER = "你太丑了，会吓到小圆的"  --洞穴蜘蛛
DESCRIBE.POISONHOLE = "有毒，不要在这里作战."  --毒洞
DESCRIBE.POMEGRANATE = "它看起来好像外星人的大脑内部"  --石榴
DESCRIBE.ROOK_NIGHTMARE = "真可怕!"  --损坏的战车
DESCRIBE.SNAKESKIN = "很结实，可以作皮带."  --蛇皮
DESCRIBE.TRINKET_14 = "这玩意让我毛骨悚然..."  --巫毒娃娃
DESCRIBE.STUNGRAY = "有剧毒，远距离击杀为上."  --恶臭魔鬼鱼
DESCRIBE.TURF_BEACH = "充满沙子的地面."  --海滩地皮
DESCRIBE.TURBINE_BLADES = "看起来只是一个叶片，但是充满了魔力"  --涡轮叶片
DESCRIBE.TRUNK_COOKED = "不知怎的比以前更像鼻子了."  --烤熟象鼻
DESCRIBE.TURF_DIRT = "一块土地"  --污垢草皮
DESCRIBE.PALMTREE.BURNT = "我希望我可以阻止它."  --椰子树
DESCRIBE.PALMTREE.CHOPPED = "还能利用一下"  --椰子树
DESCRIBE.PALMTREE.GENERIC = "好炎热."  --椰子树
DESCRIBE.PALMTREE.BURNING = "烧炭."  --椰子树
DESCRIBE.TRIDENT = "比狙击枪还猛烈"  --三叉戟
DESCRIBE.RUINS_BAT = "这东西可真重."  --铥矿棒
DESCRIBE.SNAKE_POISON = "小圆小心！哦我自己也该小心"  --毒蛇
DESCRIBE.SLOTMACHINE = "卖不卖子弹？"  --老虎机
DESCRIBE.SEWING_KIT = "如果小圆在的话……不，不能麻烦她"  --缝纫工具包
DESCRIBE.SEAWEED_PLANTED = "这是在这地方获得食物的一种途径咯?"  --海带
DESCRIBE.STALAGMITE = "我看它就是块石头"  --石笋
DESCRIBE.SANDBAG = "躲在掩体后面射击."  --沙袋
DESCRIBE.SANDBAG_ITEM = "沙子科技,运作."  --沙袋
DESCRIBE.RAINBOWJELLYFISH_DEAD = "电击不能复活它，我试过了。"  --死彩虹水母
DESCRIBE.ROWBOAT = "想带小圆看看海景."  --划艇
DESCRIBE.RAFT = "只适合应急……."  --竹筏
DESCRIBE.PIRATEHAT = "把船上的军火……货物交出来"  --海盗帽
DESCRIBE.OX = "这些生物看起来还能讲点理."  --水牛
DESCRIBE.RESEARCHLAB4.GENERIC = "虽然有魔法，但是不能帮我净化灵魂宝石"  --魔法帽子
DESCRIBE.RESEARCHLAB4.BURNT = "就算一把火烧了我也还得给它命名."  --魔法帽子
DESCRIBE.TALLBIRDEGG_COOKED = "一个人吃太奢侈了，得给小圆也尝尝."  --油煎高脚鸟蛋
DESCRIBE.SLURPERPELT = "看起来全部都是不同的死法."  --
DESCRIBE.OBSIDIANFIREPIT.GENERIC = "这个火山坑是更多火的导体."  --十胜石火堆
DESCRIBE.OBSIDIANFIREPIT.OUT = "至少我还可以重新开始."  --十胜石火堆
DESCRIBE.OBSIDIANFIREPIT.EMBERS = "在出门之前,我应该把火给熄灭了."  --十胜石火堆
DESCRIBE.OBSIDIANFIREPIT.HIGH = "它有一个好东西,那就是火!"  --十胜石火堆
DESCRIBE.OBSIDIANFIREPIT.LOW = "火势慢慢下降了."  --十胜石火堆
DESCRIBE.OBSIDIANFIREPIT.NORMAL = "这是我至今为止最好的发明."  --十胜石火堆
DESCRIBE.RELIC.GENERIC = "远古家庭用品."  --废墟
DESCRIBE.RELIC.BROKEN = "这里没什么能做的事情."  --废墟
DESCRIBE.TRINKET_2 = "你有什么规划?"  --假卡祖笛
DESCRIBE.PUMPKIN_COOKED = "还能做成马车吗?"  --热南瓜
DESCRIBE.SLURPER = "你还想吸我吗？"  --缀食者
DESCRIBE.STALAGMITE_TALL = "石头,石头,石头,石头......"  --
DESCRIBE.ROCK_LIGHT.GENERIC = "一个陈旧的熔岩坑."  --火山坑
DESCRIBE.ROCK_LIGHT.OUT = "看起来很脆弱."  --火山坑
DESCRIBE.ROCK_LIGHT.LOW = "快要灭了吗"  --火山坑
DESCRIBE.ROCK_LIGHT.NORMAL = "好看又舒服"  --火山坑
DESCRIBE.PALMLEAF = "小圆跳草裙舞……我在想什么呢."  --椰树叶
DESCRIBE.SAIL_STICK = "有点浪费魔力."  --帆棍
DESCRIBE.SPIDERHOLE = "它外面盖满了蛛网"  --蛛网岩
DESCRIBE.TENTACLESPIKE = "它又尖又黏"  --触手尖刺
DESCRIBE.TIDAL_PLANT = "看啊.一株植物."  --植物
DESCRIBE.SEATRAP = "会有一只船炮，啊不龙虾进来吗？"  --海洋陷阱
DESCRIBE.ORANGEGEM = "是一颗橙色宝石."  --橙宝石
DESCRIBE.SAND_CASTLE.GENERIC = "就像蛋壳一样，是个沙雕"  --沙雕
DESCRIBE.SAND_CASTLE.SAND = "蛋壳非说自己就是这个沙雕"  --沙雕
DESCRIBE.STATUEMAXWELL = "真的凸显出了他的个性."  --麦斯威尔雕像
DESCRIBE.OBSIDIANSPEARGUN = "威力很强，但是别烫到自己."  --十胜石矛枪
DESCRIBE.SPEARGUN_POISON = "这可是涂了毒的……."  --毒矛枪
DESCRIBE.OBSIDIANMACHETE = "摸起来很烫."  --十胜石砍刀
DESCRIBE.RATATOUILLE = "为了维生素，吃吧"  --蔬菜杂烩
DESCRIBE.PIGHOUSE.FULL = "开门，查水表"  --猪人房
DESCRIBE.PIGHOUSE.BURNT = "让你再蹦跶!猪!"  --猪人房
DESCRIBE.PIGHOUSE.LIGHTSOUT = "快点开门,查水表!我知道你在家!"  --猪人房
DESCRIBE.PIGHOUSE.GENERIC = "这些猪的房子真高档"  --猪人房
DESCRIBE.ROCK_ICE_MELTED = "在它结冰之前没什么用."  --融化的迷你冰川
DESCRIBE.TURF_MUD = "又是一种新地形"  --泥泞草地
DESCRIBE.SHARKFINSOUP = "这是鲨鱼做成的!"  --鱼翅汤
DESCRIBE.SEAFOODGUMBO = "小圆好像没喝过这个."  --海鲜汤
DESCRIBE.THULECITE_PIECES = "一些更小的厚厚的铥矿石."  --铥矿石碎片
DESCRIBE.ROBIN.GENERIC = "这意味着冬天过去了吗?"  --红雀
DESCRIBE.ROBIN.HELD = "拿去给小圆看看？"  --红雀
DESCRIBE.RESEARCHLAB2.GENERIC = "它甚至比上一个更科学了!"  --炼金术引擎
DESCRIBE.RESEARCHLAB2.BURNT = "丰富的科技没能保证它的存活."  --炼金术引擎
DESCRIBE.STUFFEDEGGPLANT = "暖暖的，像小圆炖的汤"  --香酥茄盒
DESCRIBE.SUNKEN_BOAT_TRINKET_4 = "科学!"  --沃尔特海
DESCRIBE.SLURTLEHAT = "好像可以减轻被爆头的概率"  --背壳头盔
DESCRIBE.SUNKEN_BOAT_TRINKET_3 = "看起来有点沉闷."  --浸泡过的蜡烛
DESCRIBE.SUNKEN_BOAT_TRINKET_2 = "我需要的只是一个压缩机器!"  --玩具船
DESCRIBE.SUNKEN_BOAT_TRINKET_1 = "某种形式的乐器."  --六分仪
DESCRIBE.SUNKEN_BOAT_BURNT = "它甚至比以前更适合."  --
DESCRIBE.TRINKET_12 = "我不知道应该如何处理干燥的触手"  --干瘪触手
DESCRIBE.SHADOWSKITTISH_WATER = "呀!"  --
DESCRIBE.PIKE_SKULL = "哎哟."  --
DESCRIBE.ROCK_MOON = "那个石头是从月亮上来的."  --
DESCRIBE.TURF_UNDERROCK = "又是一种新地形"  --洞穴石地
DESCRIBE.TAR_POOL = "如果能在上面造个油井的话……但是没有内燃机啊"  --焦油
DESCRIBE.ROBOT_PUPPET = "它被困住了!"  --
DESCRIBE.TRINKET_5 = "不幸的是,它太小了没法让我从此逃脱"  --小型火箭飞船
DESCRIBE.SPORE_MEDIUM = "它在到处飘~~"  --
DESCRIBE.TRINKET_9 = "我本人更喜欢拉链"  --不匹配的钮扣
DESCRIBE.RESEARCHLAB.GENERIC = "或许叫成魔法机器更科学一些"  --科学机器
DESCRIBE.RESEARCHLAB.BURNT = "没法拿它做研究了."  --科学机器
DESCRIBE.SLURPER_PELT = "它一直吸我，只能这样了."  --缀食者之皮
DESCRIBE.TURF_SANDY = "又一种地面地形."  --
DESCRIBE.SPAT = "一个易怒的动物."  --Ewecus
DESCRIBE.TENTACLE_GARDEN = "又一个泥坑."  --大触手
DESCRIBE.TRUNK_WINTER = "不知为何，感觉这鼻子很耐寒"  --蓝色象鼻
DESCRIBE.SHARK_TEETHHAT = "真正的王冠会刻在灵魂宝石上."  --鲨齿王冠
DESCRIBE.TRINKET_6 = "它们运送电力的日子结束了"  --破烂电线
DESCRIBE.TRINKET_3 = "结点被困住了.永久性的"  --歌德结
DESCRIBE.PEROGIES = "我都忘了里面放了些什么"  --饺子
DESCRIBE.TRINKET_11 = "他轻声地跟我说美丽的谎言"  --半躺机器人
DESCRIBE.SWEETPOTATOSOUFFLE = "去小圆家过夜的时候不可多吃."  --薯蛋奶酥
DESCRIBE.SPIDER_DROPPER = "写给自己：不要往上看。"  --穴居悬蛛
DESCRIBE.SKULLCHEST = "我不确定我想不想打开它."  --骷髅箱
DESCRIBE.TRAP_TEETH = "真是糟糕的意外"  --狗牙陷阱
DESCRIBE.TORCH = "驱赶黑夜的东西"  --火炬
DESCRIBE.TUMBLEWEED = "里面有一个弹夹，我确信."  --风滚草
DESCRIBE.TENTACLESPOTS = "我想这些是它的生殖器"  --斑点触手皮
DESCRIBE.PIGTORCH = "看上去挺惬意"  --猪头火炬
DESCRIBE.TURKEYDINNER = "万圣节到了，跟小圆一起吧"  --火鸡正餐
DESCRIBE.TELESTAFF = "它可以为我揭示整个世界."  --传送魔杖
DESCRIBE.PAPYRUS = "劣质的纸张."  --莎草纸
DESCRIBE.TELEPORTATO_RING = "一枚可以聚集空间能量的戒指"  --环状零件
DESCRIBE.SEASHELL_BEACHED = "这一枚可以给小圆……."  --贝壳
DESCRIBE.ORANGEAMULET = "传送很有用."  --懒惰的强盗
DESCRIBE.SKELETON = "不是死于枪伤，与我无关。"  --骨架
DESCRIBE.TELEPORTATO_BOX = "这或许会控制整个宇宙的极性"  --盒状零件
DESCRIBE.PRIMEAPE = "如果你们够聪明的话，别惹我."  --猿
DESCRIBE.TALLBIRDEGG_CRACKED.GENERIC = "看起来它正在孵化!"  --孵化的高脚鸟蛋
DESCRIBE.TALLBIRDEGG_CRACKED.HOT = "蛋也会出汗?"  --孵化的高脚鸟蛋
DESCRIBE.TALLBIRDEGG_CRACKED.COLD = "是它在颤抖还是我在颤抖?"  --孵化的高脚鸟蛋
DESCRIBE.TALLBIRDEGG_CRACKED.SHORT = "它马上就该孵化了"  --孵化的高脚鸟蛋
DESCRIBE.TALLBIRDEGG_CRACKED.LONG = "我感觉这需要一些时间......"  --孵化的高脚鸟蛋
DESCRIBE.TALLBIRDEGG = "它会孵化吗?"  --高脚鸟蛋
DESCRIBE.STRAWHAT = "给小圆也做一顶如何。"  --草帽
DESCRIBE.STATUEHARP = "我的头怎么了?"  --直立雕像
DESCRIBE.TIGERSHARK = "考虑清楚，你还有家人，真的要跟我作对？"  --虎鲨
DESCRIBE.SPIDER_WARRIOR.GENERIC = "还好小圆不在"  --蜘蛛战士
DESCRIBE.SPIDER_WARRIOR.SLEEPING = "我应当保持距离"  --蜘蛛战士
DESCRIBE.SPIDER_WARRIOR.DEAD = "自不量力。"  --蜘蛛战士
DESCRIBE.TURF_VOLCANO = "火山风情地皮."  --火山地皮
DESCRIBE.STAFFLIGHT = "那貌似非常危险."  --矮星
DESCRIBE.SWEET_POTATO_PLANTED = "不太适合我，尤其是去小圆家过夜的时候"  --甘薯
DESCRIBE.SPIDEREGGSACK = "我希望这些不要在我的口袋里孵化"  --蜘蛛卵
DESCRIBE.SPIDERDEN = "真粘!"  --蜘蛛巢
DESCRIBE.TAR = "我必须用手拿着它吗？"  --焦油
DESCRIBE.TENTACLE = "听说那是魔法少女的好朋友……你以为我会信吗？"  --触手
DESCRIBE.SMALLMEAT_DRIED = "不去考虑来源的话还是很好吃的"  --小块肉干
DESCRIBE.SMALLMEAT = "这肉……以前我是不会吃的"  --小肉块
DESCRIBE.PLANTMEAT_COOKED = "至少现在暖和了."  --煮熟的多叶肉
DESCRIBE.SKELETON_PLAYER = "他死总比...等会儿!"  --骨架
DESCRIBE.TELEPORTATO_CRANK = "强壮到足以应付最危险的实验"  --曲柄状零件
DESCRIBE.PIGGYBACK = "太不灵活了，不是理想的装备"  --小猪包
DESCRIBE.SILK = "它来自蜘蛛的屁股"  --蜘蛛网
DESCRIBE.SHOVEL = "不是标准的工兵铲，只能挖地"  --铲子
DESCRIBE.PRIMEAPEBARREL = "这帮家伙总想偷我的弹药."  --猿猴小屋
DESCRIBE.RESEARCHLAB5 = "海洋科技！"  --海洋实验室
DESCRIBE.SANITYROCK.INACTIVE = "它的剩余部分到哪里去了?"  --方尖碑
DESCRIBE.SANITYROCK.ACTIVE = "那石头看起来太奇怪了!"  --方尖碑
DESCRIBE.ROTTENEGG = "离拥有火药又近了一步"  --烂鸡蛋
DESCRIBE.TURF_DESERTDIRT = "肮脏的地皮."  --沙地
DESCRIBE.ROPE = "一些短绳"  --绳索
DESCRIBE.ROOK = "洗劫了城堡!"  --发条战车
DESCRIBE.THATCHPACK = "太劣质了，不适合小圆."  --茅草包
DESCRIBE.PIGSKIN = "很结实，功能丰富"  --猪皮
DESCRIBE.SNAKEOIL = "标签上写的是……完全无害。"  --蛇油
DESCRIBE.RED_CAP_COOKED = "现在不同了......"  --烤红蘑菇
DESCRIBE.REDGEM = "它闪着温暖的光"  --红宝石
DESCRIBE.RAZOR = "我用不上"  --剃刀
DESCRIBE.PUMPKINCOOKIE = "圣诞节的美食"  --南瓜饼
DESCRIBE.PIGMAN.GENERIC = "似乎拥有一定理性"  --猪人
DESCRIBE.PIGMAN.FOLLOWER = "协助我是很睿智的选择"  --猪人
DESCRIBE.PIGMAN.WEREPIG = "你看起来在挑衅我？"  --猪人
DESCRIBE.PIGMAN.GUARD = "你应该对我放尊重点"  --猪人
DESCRIBE.PIGMAN.DEAD = "只有我能活下来吗"  --猪人
DESCRIBE.SWEET_POTATO_COOKED = "看起来更好吃了!"  --烤甘薯
DESCRIBE.SPIDERGLAND = "简单处理一下伤口吧"  --蜘蛛腺体
DESCRIBE.STALAGMITE_TALL_FULL = "石头,石头,石头,石头......"  --
DESCRIBE.PANFLUTE = "趁小圆不在，我先练一练"  --排箫
DESCRIBE.TWISTER_SEAL = "所以你在祈求我放过你？."  --海豹
DESCRIBE.TRINKET_16 = "什么风把这玩意吹到这儿来了?"  --号码牌
DESCRIBE.PACKIM = "看来吃鱼是你的天性."  --帕克白格斯
DESCRIBE.SOLOFISH = "你跑不掉的."  --狗鱼
DESCRIBE.SPOILED_FISH = "不能吃了，做点别的事吧."  --变质的鱼
DESCRIBE.POMEGRANATE_COOKED = "真能这么吃吗？"  --石榴片
DESCRIBE.ROCKS = "造个军火库吧"  --岩石
DESCRIBE.SWIMMINGHORROR = "是你可怕，还是我的枪可怕？"  --游动的恐惧
DESCRIBE.TELEPORTATO_BASE.GENERIC = "这好像是跟另一个世界的连接点!"  --传送机底座
DESCRIBE.TELEPORTATO_BASE.ACTIVE = "马上就能回到小圆身边了吗？"  --传送机底座
DESCRIBE.TELEPORTATO_BASE.LOCKED = "小圆，再等等我……"  --传送机底座
DESCRIBE.TELEPORTATO_BASE.PARTIAL = "快乐,那个发明即将完成!"  --传送机底座
DESCRIBE.TURF_SWAMP = "沼泽风情地皮."  --沼泽地皮
DESCRIBE.TELEBASE.VALID = "已经准备好出发了."  --传送核心
DESCRIBE.TELEBASE.GEMS = "我需要更多地紫色宝石."  --传送核心
DESCRIBE.TAR_EXTRACTOR.LOWFUEL = "我得给它添加点燃料。"  --焦油提取器
DESCRIBE.TAR_EXTRACTOR.ON = "就要有油了。"  --焦油提取器
DESCRIBE.TAR_EXTRACTOR.OFF = "忘了按开关了吗"  --焦油提取器
DESCRIBE.RABBITHOLE.GENERIC = "那一定通向兔子王国"  --兔子窝
DESCRIBE.RABBITHOLE.SPRING = "怎么塌了？你们在里面干了什么？"  --兔子窝
DESCRIBE.SPIDER_SPITTER = "嘴巴放干净点"  --喷吐蜘蛛
DESCRIBE.STALAGMITE_FULL = "我看它就是块石头"  --
DESCRIBE.TELEPORTATO_SW_RING = "看起来我能利用这东西."  --戒指状零件
DESCRIBE.TRINKET_13 = "这东西是什么材质的?"  --橘子汽水
DESCRIBE.TRINKET_15 = "不可思议!这把吉他居然会缩水!"  --四弦琴
DESCRIBE.PIGHEAD.GENERIC = "看起来像是给野兽的供奉品"  --猪人头
DESCRIBE.PIGHEAD.BURNT = "嘎嘣脆."  --猪人头
DESCRIBE.PIGTENT = "闻起来像烟肉"  --
DESCRIBE.RESEARCHLAB3.GENERIC = "好强的魔力反应"  --暗影操纵仪
DESCRIBE.RESEARCHLAB3.BURNT = "魔力反应没了"  --暗影操纵仪
DESCRIBE.SEAWEED_DRIED = "咸的!"  --晾干的海带
DESCRIBE.TRANSISTOR = "大型武器的重要组成部件"  --电器元件
DESCRIBE.QUACKENBEAK = "我得说，我应该可以用它钻点什么。"  --呱肯海妖的喙
DESCRIBE.SUNKBOAT = "在那儿它对我来说没什么用处!"  --沉船
DESCRIBE.POND = "我看不到底"  --池塘
DESCRIBE.TURF_FUNGUS_GREEN = "绿色真菌地皮."  --菌类草地
DESCRIBE.TURF_DECIDUOUS = "又是一种新地形"  --季节性草地
DESCRIBE.TURF_ROCKY = "一块土地"  --岩石草皮
DESCRIBE.STALAGMITE_LOW = "我看它就是块石头"  --
DESCRIBE.SPORE_TALL_INV = "我可以在我的口袋里留一点光."  --
-------opqrst--------	
DESCRIBE.WORMLIGHT_PLANT = "看起来挺安全的."  --
DESCRIBE.WIND_CONCH = "现在我决定问问神奇海螺"  --呼啸海螺
DESCRIBE.WALRUSHAT = "戴上这个，我更像一名士兵了"  --贝雷帽
DESCRIBE.WALL_ENFORCEDLIMESTONE_ITEM = "我必须在水里建造它。"  --海堤
DESCRIBE.WALRUS_CAMP.EMPTY = "敌方狙击手已被我击毙，还挺香的"  --海象巢穴
DESCRIBE.WALRUS_CAMP.GENERIC = "它里面好像温暖又舒适"  --海象巢穴
DESCRIBE.WATERCHEST = "子弹放进去会不会受潮啊"  --海底阀箱
DESCRIBE.WRECK = "可怜的小船."  --残骸
DESCRIBE.WALL_MOONROCK = "古怪又光滑！"  --
DESCRIBE.WILDBOREHEAD = "和它长得一样难闻."  --野猪头
DESCRIBE.UNIMPLEMENTED = "貌似还完成呢!可能还是很危险."  --
DESCRIBE.UNAGI = "做成寿司给小圆吃吧"  --鳗鱼
DESCRIBE.WINTEROMETER.GENERIC = "无论春夏秋冬，我们变身后的衣服都是一套"  --温度测量器
DESCRIBE.WINTEROMETER.BURNT = "它屈指可数的生命到头了."  --温度测量器
DESCRIBE.WALL_STONE_ITEM = "它们让我有安全感"  --石墙
DESCRIBE.WALL_ENFORCEDLIMESTONE = "我用好东西建造了它。"  --海堤
DESCRIBE.WALL_MOONROCK_ITEM = "非常轻,但是出乎意料的粗糙."  --
DESCRIBE.WHALE_WHITE = "子弹打不透这家伙吧"  --白鲸
DESCRIBE.WOODLEGSSAIL = "典型的海盗航行."  --
DESCRIBE.WOODLEGSBOAT = "适合饭桶的飞船."  --“海腿号”
DESCRIBE.WHALE_TRACK = "鲸,呀!"  --
DESCRIBE.WATERYGRAVE = "就算钓到子弹也没法用了吧"  --水墓
DESCRIBE.VOLCANO_ALTAR_TOWER = "好吓人啊!"  --
DESCRIBE.WALL_RUINS = "元古城墙的碎片."  --铥矿墙
DESCRIBE.VOLCANO_SHRUB = "这个不能当炭用了."  --烧焦的灰树
DESCRIBE.WALRUS = "比比枪法吗？"  --海象
DESCRIBE.UMBRELLA = "好久没跟小圆一起撑伞了"  --雨伞
DESCRIBE.WILBUR_CROWN = "真是一副猴样."  --旧王冠
DESCRIBE.WORM.PLANT = "危险的气息！"  --深渊蠕虫
DESCRIBE.WORM.DIRT = "在地下，很难命中……"  --深渊蠕虫
DESCRIBE.WORM.WORM = "威胁性堪比使魔！"  --深渊蠕虫
DESCRIBE.WATERMELON_SEEDS = "它是一个瓜子."  --西瓜种子
DESCRIBE.WALL_WOOD.GENERIC = "尖的!"  --木墙
DESCRIBE.WALL_WOOD.BURNT = "烧没了!"  --木墙
DESCRIBE.WILDBOREGUARD = "它在保护什么?是弹药库吗？"  --野猪守卫
DESCRIBE.YELLOWGEM = "这颗宝石是黄色的."  --黄宝石
DESCRIBE.WOODLEGSHAT = "或许能让我明白那把枪的结构……"  --幸运帽
DESCRIBE.VOLCANO_EXIT = "呼……凉快了一些"  --火山
DESCRIBE.WATERMELON_COOKED = "温润多汁!"  --烤西瓜
DESCRIBE.WILDBOREHOUSE = "多么无聊的房子."  --荒野小屋
DESCRIBE.WILDBORE = "用子弹也很难跟他讲道理"  --野猪
DESCRIBE.WILBUR_UNLOCK = "他看起来很有钱."  --潮湿的猴子
DESCRIBE.YELLOWSTAFF = "我在一个棒子上镶嵌了一颗宝石."  --唤星魔杖
DESCRIBE.WHALE_CARCASS_WHITE = "送他颗炸弹尝尝会如何？"  --白鲸尸体
DESCRIBE.WETGOOP = "对不起小圆，我这次又做坏了."  --湿腻焦糊
DESCRIBE.VOLCANO = "这东西的威力比枪械大多了"  --火山
DESCRIBE.WALRUS_TUSK = "这算是一枚勋章吧"  --海象牙
DESCRIBE.YELLOWAMULET = "摸起来很暖和."  --魔力之光
DESCRIBE.WAFFLES = "下一块是小圆的"  --华夫饼
DESCRIBE.WHALE_BUBBLES = "像找魔女一样找到它……."  --可疑的泡泡
DESCRIBE.WALLYINTRO_DEBRIS = "一艘破船的一部分."  --残骸
DESCRIBE.WHIP = "没有什么能像噪音一样让人安心."  --
DESCRIBE.VINE = "也许我能用它绑点什么."  --藤蔓
DESCRIBE.WOODLEGS_KEY1 = "某种东西,某个地方一定被锁着了."  --骨制钥匙
DESCRIBE.WOODLEGS_KEY3 = "这是把钥匙."  --铁制钥匙
DESCRIBE.WOODLEGS_KEY2 = "这钥匙大概能打开什么东西."  --金制钥匙
DESCRIBE.WALL_LIMESTONE_ITEM = "如果我能把它放下了它能更有用."  --石灰石墙
DESCRIBE.WATERMELON = "小圆，这里的西瓜好便宜！"  --西瓜
DESCRIBE.WHALE_CARCASS_BLUE = "直接炸开……如何？."  --蓝鲸尸体
DESCRIBE.VOLCANO_ALTAR_BROKEN = "额,这不会有问题,是吗?"  --
DESCRIBE.VOLCANO_ALTAR.GENERIC = "满足了？."  --火山祭坛
DESCRIBE.VOLCANO_ALTAR.OPEN = "你是这方的神明吗？"  --火山祭坛
DESCRIBE.WEBBERSKULL = "可怜的小东西...该为他举办个体面的葬礼."  --韦伯的头颅
DESCRIBE.WALL_LIMESTONE = "结实."  --石灰石墙
DESCRIBE.WALL_RUINS_ITEM = "一片历史的碎片."  --铥矿墙
DESCRIBE.WOODLEGS_CAGE = "看起来，这个牢笼被加了相当多的锁啊."  --伍德莱格的笼子
DESCRIBE.WATERCROCODOG = "你和我一样冰冷。"  --蓝色鳄狗
DESCRIBE.VENOMGLAND = "闭上眼，咬住牙，为了解毒……"  --毒腺
DESCRIBE.WORMHOLE_LIMITED = "啊,那东西看起来比平常更糟糕"  --
DESCRIBE.WORMHOLE.GENERIC = "我要跳进去吗……"  --虫洞
DESCRIBE.WORMHOLE.OPEN = "跳进去的话会不会有危险……"  --虫洞
DESCRIBE.WATERMELONHAT = "黏糊糊的，很不舒服."  --时尚西瓜帽
DESCRIBE.WASPHIVE = "小圆，别靠近那里"  --杀人蜂巢
DESCRIBE.WARG = "杀死它恐怕需要很多子弹."  --座狼
DESCRIBE.WALL_HAY.GENERIC = "嗯.看来只能那样了"  --干草墙
DESCRIBE.WALL_HAY.BURNT = "那样不会有任何好处."  --干草墙
DESCRIBE.WALL_STONE = "这堵墙真不错."  --石墙
DESCRIBE.WALL_HAY_ITEM = "这个看上去不像是个好主意"  --干草墙
DESCRIBE.WATERMELONICLE = "我一根，小圆一根"  --西瓜冰
DESCRIBE.WHALE_BLUE = "这头鲸有情感问题."  --蓝鲸
DESCRIBE.VOLCANOSTAFF = "标签上说「放到儿童接触不到的地方.」"  --火山魔杖
DESCRIBE.WINTERHAT = "小圆应该需要一个"  --寒冬帽
DESCRIBE.WALL_WOOD_ITEM = "木桩!"  --木墙
DESCRIBE.WORMLIGHT_LESSER = "有点皱."  --
DESCRIBE.WORMLIGHT = "会让我闪耀起来？"  --发光浆果

----ham----

DESCRIBE.DECO_ROUND = "足够稳定."   --圆柱
DESCRIBE.DECO_LAMP_GOTHIC = "一盏精心设计的灯."   --哥特灯
DESCRIBE.DECO_WOOD = "足够稳固."   --被刨平的木柱
DESCRIBE.DECO_PLANTHOLDER_WIP = "生长工作仍在进行中."   --半成品种植盆
DESCRIBE.CHICKEN.GENERIC = "它是一只小鸡"   --鸡
DESCRIBE.CHICKEN.SLEEPING = "它出故障了."   --鸡
DESCRIBE.CHICKEN.DEAD = "确定是死了无疑了."   --鸡
DESCRIBE.DECO_PLANTHOLDER_DRACEANA = "用一种奇特的方式种植一种奇特的植物."   --龙血植物种植盆
DESCRIBE.BUNDLEWRAP = "Wrapping things up should make them easier to carry."   --Bundling Wrap
DESCRIBE.GHOST_SAILOR = "我猜你死于火绳枪"   --水手怨魂
DESCRIBE.CLAWPALMTREE_SAPLING = "软软的，但是也能烧炭"   --棕榈爪树苗
DESCRIBE.DUNGBEETLE.GENERIC = "她滚得很带劲儿."   --圣甲虫
DESCRIBE.DUNGBEETLE.SLEEPING = "她累坏了."   --圣甲虫
DESCRIBE.DUNGBEETLE.UNDUNGED = "她需要把她的宝贝便便聚集起来."   --圣甲虫
DESCRIBE.DUNGBEETLE.DEAD = "虫为翔亡."   --圣甲虫
DESCRIBE.DECO_PLANTHOLDER_PITCHERS = "一株会生长的吊灯!"   --猪笼草种植盆
DESCRIBE.GASCLOUD = "小圆，戴上口罩……她没在这，太好了."   --毒雾
DESCRIBE.DECO_WALLORNAMENT_PHOTO = "那孩子是谁？"   --照片
DESCRIBE.LEATHER = "任何天气都适合穿戴的皮革."
DESCRIBE.DECO_LAMP_2FRINGES = "买一送一."   --双条纹灯
DESCRIBE.DECO_ANTIQUITIES_WALLFISH = "这就是香味的来源."   --美味的鱼挂饰
DESCRIBE.DECO_LAMP_DOWNBRIDGE = "花哨的灯."   --地下灯
DESCRIBE.CUTNETTLE = "可以作为药材使用."   --荨麻
DESCRIBE.DECO_RUINS_BEAM_ROOM_BLUE = "它支撑着屋顶."   --平凡的柱子
DESCRIBE.IRON = "炼制之后可以自己铸造枪管"   --铁矿石
DESCRIBE.DECO_WALLORNAMENT_EMBROIDERY_HOOP = "多么温馨."   --绣花圈
DESCRIBE.DECO_LAMP_SPOOL = "朴素的灯."   --线轴灯
DESCRIBE.ASPARAGUS_SEEDS = "它是芦笋种子。"   --芦笋种子
DESCRIBE.DEFLATED_BALLOON_BASKET = "一个彻底的废物。"   --柳条篮
DESCRIBE.LOTUS = "小圆躺在里面."   --睡莲
DESCRIBE.INTERIOR_FLOOR_PLAID_TILE = "完全是地板."   --石地板
DESCRIBE.BRAMBLESPIKE = "一团纠缠在一起的尖东西"   --荆棘
DESCRIBE.DECO_MILLINERY = "增加了稳定性."   --女帽柱
DESCRIBE.INTERIOR_FLOOR_SHEET_METAL = "一块可以铺的地板."   --金属地板
DESCRIBE.ANTMAN_WARRIOR_EGG = "应该在它孵化之前……"   --蚂蚁战士卵
DESCRIBE.DECO_PLANTHOLDER_XEROGRAPHICA = "以一种有趣的方式保存一株有趣的植物."   --空气凤梨种植盆
DESCRIBE.ARMOR_METALPLATE = "相当结实，但是太沉了"   --锡甲
DESCRIBE.DECO_TABLE_CRATE = "我可以在上面放一些东西."   --板条桌
DESCRIBE.FROGLEGS_POISON_COOKED = "小圆别吃，让杏子试毒"   --烤箭毒蛙腿
DESCRIBE.CORKCHEST = "害虫保护剂."   --软木桶
DESCRIBE.INTERIOR_WALL_SUNFLOWER = "漂亮的贴在墙上的纸."   --向日葵墙纸
DESCRIBE.ASPARAGUS_PLANTED = "我应该采摘它们."   --芦笋苗
DESCRIBE.DECO_PLANTHOLDER_ZZ = "一个花式植物的花盆."   --金钱树种植盆
DESCRIBE.BALLPEIN_HAMMER = "我也要当考古学家？"   --圆头锤
DESCRIBE.BATHAT = "帽子,它是由蝙蝠做成的."   --整流罩
DESCRIBE.DECO_CHAIR_LOUNGE = "我可以坐在上面."   --休息椅
DESCRIBE.DECO_LAMP_CANDELABRA = "一盏有趣的灯."   --烛台灯
DESCRIBE.ANTSUIT = "小圆，我是你的小蚂蚁~."   --蚁甲
DESCRIBE.DECO_LAMP_GLASS = "精心设计的的灯."   --玻璃灯
DESCRIBE.DUNGBALL = "确确实实的便便."   --粪球
DESCRIBE.DECO_CHAIR_STUFFED = "舒适的椅子."   --填充椅
DESCRIBE.DECO_CHAIR_MASSAGER = "我信不过它."   --信使椅
DESCRIBE.ASPARAGUS_COOKED = "科学告诉我这对我有好处."   --煮熟的芦笋
DESCRIBE.BIGFISHINGROD = "我要一根大棒子来抓条大鱼。"
DESCRIBE.BASEFAN = "碧海蓝天吹吹风~."   --转动的风扇
DESCRIBE.ALOE_PLANTED = "一种用途广泛的植物."   --芦会苗
DESCRIBE.FEIJOADA = "我晓美焰就算饿死……"   --八宝饭
DESCRIBE.LOTUS_FLOWER_COOKED = "一道美味佳肴."   --烤莲藕
DESCRIBE.MINISIGN.GENERIC = "I could draw better than that!"   --Mini Sign
DESCRIBE.MINISIGN.UNDRAWN = "We should draw something on there."   --Mini Sign
DESCRIBE.MINISIGN_ITEM = "It's not much use like this. We should place it."   --Mini Sign
DESCRIBE.CHITIN = "可以做成防弹衣吗？"   --甲壳质
DESCRIBE.CITY_LAMP.GENERIC = "普通的火.不涉及科学."   --路灯
DESCRIBE.CITY_LAMP.ON = "灯灭了."   --路灯
DESCRIBE.FENCE = "It's just a wood fence."   --Wood Fence
DESCRIBE.DEFLATED_BALLOON = "我的热气球爆炸了。"   --泄气的气球
DESCRIBE.DECO_WALLORNAMENT_CAPE = "有点戏剧性."   --斗篷
DESCRIBE.DECO_LAMP_ORB = "做工精良的灯"   --天体灯
DESCRIBE.KEY_TO_CITY = "我是国王，小圆是王后，你们记住了"   --城镇之钥
DESCRIBE.DECO_WALLORNAMENT_NO_SMOKING = "科学表明它有害健康."   --禁止吸烟
DESCRIBE.APOKALYPSE_HERALD = "你是……魔兽吗？"   --古代先驱
DESCRIBE.BLUNDERBUSS = "真是相当落后的火器……精度居然比我的枪高？"   --火枪
DESCRIBE.DECO_LAMP_BELLSHADE = "一盏花哨的灯."   --钟罩灯
DESCRIBE.DECO_CHAIR_CLASSIC = "我可以坐在上面."   --古典椅
DESCRIBE.DECO_PLANTHOLDER_FERN = "一株垂吊植物."   --蕨类植物种植盆
DESCRIBE.ANTMASKHAT = "小圆，如果你喜欢我就一直戴着"   --蚁盔
DESCRIBE.HIPPO_ANTLER = "这应该有一些用处。"   --河马角
DESCRIBE.DUG_NETTLE = "必须把它种出来……阿嚏"   --荨麻簇
DESCRIBE.ARMOR_WEEVOLE = "这其实是……它的皮."   --虫壳披风
DESCRIBE.DECO_LAMP_HOOFSPA = "精致的灯."   --花式灯
DESCRIBE.LAWNORNAMENT.GENERIC = "一点装饰."   --草坪装饰
DESCRIBE.LAWNORNAMENT.BURNT = "好吧，它现在毁了."   --草坪装饰
DESCRIBE.LAWNORNAMENT.BURNING = "带上那个，免费装修！"   --草坪装饰
DESCRIBE.ASPARAGUSSOUP = "是这么煮的吧，小圆？"   --芦笋汤
DESCRIBE.DEED = "有个小家，可惜没有小圆"   --房契
DESCRIBE.DECO_WALLORNAMENT_WREATH = "哇，那个很棒."   --花环
DESCRIBE.FIRECRACKERS = "Filled with explosion science!"   --Firecrackers
DESCRIBE.ASPARAGUS = "一种蔬菜."   --芦笋
DESCRIBE.FEATHERPENCIL = "The feather increases the scientific properties of the writing."   --Feather Pencil
DESCRIBE.FENCE_GATE = "It opens. And closes sometimes, too."   --Wood Gate
DESCRIBE.FENCE_ITEM = "All we need to build a nice, sturdy fence."   --Wood Fence
DESCRIBE.BRUSH = "I bet the beefalo really like this."   --Brush
DESCRIBE.ALOE = "科学又营养."   --芦会
DESCRIBE.CITY_HAMMER = "拆掉可能成为敌方掩体的东西"   --拆迁锤
DESCRIBE.BONESTAFF = "比传统意义上的冷冻枪好用多了"   --泥蛇骨杖
DESCRIBE.DECO_WALLORNAMENT_GEARS_ART = "很有科技范儿."   --齿轮艺术品
DESCRIBE.ANTLER = "我多希望它能带我去找小圆"   --鹏之号角
DESCRIBE.BILL_QUILL = "真无聊。"   --鸭嘴豪猪刺
DESCRIBE.CAVE_EXIT_ROC = "它堵住了一些东西。"   --石塞
DESCRIBE.DECO_PLANTHOLDER_FERNSTAND = "一种奇特的方式来保持一个无聊的植物."   --蕨类植物种植盆
DESCRIBE.ALOE_SEEDS = "它是一个芦荟种子。"   --芦荟种子
DESCRIBE.NETTLELOSANGE = "无害的幼芽."   --荨麻卷
DESCRIBE.ANTQUEEN_THRONE = "必要的时候可以爆破掉"   --石笋王座
DESCRIBE.ANTQUEEN_CHAMBERS = "一个银色的庭园……是错觉吧"   --蚁后宫殿
DESCRIBE.BANDITHAT = "偷军火相当方便"   --强盗帽
DESCRIBE.GUMMY_CAKE = "有嚼劲，像糖果一样."   --木糖蛋糕
DESCRIBE.HARDSHELL_TACOS = "闭上眼睛，享用佳肴."   --硬壳玉米饼
DESCRIBE.APORKALYPSE_CLOCK = "圆环之理终将审判我……我在说什么啊？."   --末日时厉
DESCRIBE.METALPLATEHAT = "这头盔太不方便了."   --花哨的头盔
DESCRIBE.BANDITMAP = "你一定私藏了不少军火！"   --小偷藏匿地图
DESCRIBE.CORK_BAT = "威力不小，但是太不结实了"   --软木棒
DESCRIBE.BUGREPELLENT = "接招吧,虫子们!"   --驱虫剂
DESCRIBE.ANTCOMBHOME = "大概有一个连的部队."   --蚁巢
DESCRIBE.FENCE_GATE_ITEM = "All we need to build a nice, sturdy gate."   --Wood Gate
DESCRIBE.NETTLE.WITHERED = "这东西到底该怎么种呢"   --荨麻藤
DESCRIBE.NETTLE.DEFAULT = "这植物强烈的气味清理了我的鼻腔."   --荨麻藤
DESCRIBE.NETTLE.EMPTY = "我确定它还会长出来."   --荨麻藤
DESCRIBE.NETTLE.MOIST = "它看起来既湿润又快乐。"   --荨麻藤
DESCRIBE.DECO_PLANTHOLDER_PLANTPET = "它就像一只生长的宠物!"   --盆栽种植盆
DESCRIBE.DECO_CHAISE = "花式后躺椅."   --花式躺椅
DESCRIBE.DECO_MARBLE = "在原基础上增加了稳定性."   --发光大理石灯
DESCRIBE.GOLDPAN = "自己淘金要花多长时间啊"   --淘金盘
DESCRIBE.MAGNIFYING_GLASS = "显然不可能改装成瞄准镜"   --放大镜
DESCRIBE.DISGUISEHAT = "说，你是猪"   --猪面具
DESCRIBE.DECO_CHAIR_FOOTREST = "歇脚的好地方."   --踏板
DESCRIBE.ANCIENT_ROBOT_HEAD = "你是被什么东西炸成这样的？"   --废铁机器人
DESCRIBE.DECO_MARBLE_CORNERBEAM = "相比之前更稳定了."
DESCRIBE.ANCIENT_ROBOT_LEG = "你的动力系统很奇怪"   --废铁机器人
DESCRIBE.ANCIENT_ROBOT_CLAW = "手部没有装备火器？"   --废铁机器人
DESCRIBE.ANCIENT_ROBOT_RIBS = "所有的铁矿都是我的."   --废铁机器人
DESCRIBE.BAT_HIDE = "它为何跟猪皮如此相似……"   --猪皮？
DESCRIBE.HOGUSPORKUSATOR = "太丑了，但是有用"   --石猪引擎
DESCRIBE.CANDLEHAT = "下次戴上这个给小圆过生日吧"   --软木蜡烛帽
DESCRIBE.CORK = "不太适合做成握把."   --软木
DESCRIBE.FEATHER_THUNDER = "做成电击枪？太不现实了。"   --闪电羽毛
DESCRIBE.ABIGAIL = "啊，她有一个可爱的小蝴蝶结。"   --阿比盖尔
DESCRIBE.CLAWPALMTREE = "不能做成握把的树，没什么价值."   --棕榈爪树
DESCRIBE.INTERIOR_FLOOR_WOOD = "完全是地板."   --木质地板
DESCRIBE.FLOWER_RAINFOREST = "有危险的气息."   --奇异的花
DESCRIBE.BURR_SAPLING = "它看起来很顽强."   --雨林树苗
DESCRIBE.BANDITTREASURE = "让我看看有没有弹药……"   --秘密营地
DESCRIBE.DECO_PLANTHOLDER_DISHGARDEN = "一种有趣的种植植物的方式."   --菜园植物种植盆
DESCRIBE.DECO_PLANTHOLDER_FANCY = "很花哨."   --花俏植物种植盆
DESCRIBE.DECO_PLANTHOLDER_ORCHID = "用一种特别的方式种植一株特别的植物."   --兰花种植盆
DESCRIBE.DECO_LAMP_2UPTURNS = "买一送一."   --双重转灯
DESCRIBE.DECO_WOOD_CORNERBEAM = "增加了些许稳定性."
DESCRIBE.DECO_WALLORNAMENT_BLACK_CAT = "这代表着好运,还是霉运?"   --黑猫
DESCRIBE.DECO_WALLORNAMENT_PERIODIC_TABLE = "我自制炸药的时候看了几十遍"   --元素周期表
DESCRIBE.DECO_WALLORNAMENT_HUNT = "被长矛刺穿了."   --狩猎
DESCRIBE.DECO_WALLORNAMENT_AXE = "我有一把斧子要磨"   --斧子
DESCRIBE.DECO_WALLORNAMENT_MOSAIC = "哇，那个很棒."   --镶嵌工艺品
DESCRIBE.DECO_WALLORNAMENT_FULLLENGTH_MIRROR = "打扮一下才好去见小圆."   --穿衣镜
DESCRIBE.DECO_ANTIQUITIES_BEEFALO = "它看起来不开心了."   --皮弗娄牛挂饰
DESCRIBE.INTERIOR_FLOOR_MARBLE = "这是地板."   --大理石地板
DESCRIBE.DECO_TABLE_RAW = "有趣的装饰..."   --半成品桌
DESCRIBE.DECO_TABLE_BANKER = "我可以在那里完成一些工作."   --硬木桌
DESCRIBE.DECO_PLANTHOLDER_MARBLE = "用一种奇特的方式种植一种奇特的植物."   --大理石豆种植盆
DESCRIBE.DECO_PLANTHOLDER_TRAPS = "它们看起来饿了."   --捕蝇草种植盆
DESCRIBE.GNAT = "用枪械很难收拾掉它们."   --虫群
DESCRIBE.DECO_PLANTHOLDER_TERRARIUM = "植物笼箱."   --玻璃种植盆
DESCRIBE.DECO_PLANTHOLDER_PALM = "用一种特别的方式种植植物."   --棕榈树种植盆
DESCRIBE.DECO_PLANTHOLDER_BIRDCAGE = "一种奇特的植物保存方式."   --基本植物种植盆
DESCRIBE.DECO_PLANTHOLDER_PHILODENDRON = "以一种特别的方式种植植物."   --喜林于种植盆
DESCRIBE.DECO_LAMP_ADJUSTABLE = "一盏实用的灯."   --可调整灯
DESCRIBE.DECO_PLANTHOLDER_BASIC = "一株盆栽."   --基本植物种植盆
DESCRIBE.GNATMOUND = "要是里面能挖出子弹就好了."   --虫丘
DESCRIBE.DECO_LAMP_RIGHTANGLES = "一盏精致的灯."   --直角灯
DESCRIBE.DECO_LAMP_EDISON = "这个可以装个灯罩."   --爱迪生灯
DESCRIBE.DECO_LAMP_UPTURN = "做工精良的灯"   --翻转灯
DESCRIBE.DECO_LAMP_CRYSTALS = "奇特的灯."   --水晶灯
DESCRIBE.DECO_LAMP_ELIZABETHAN = "一盏老式的花灯."   --伊丽莎白灯
DESCRIBE.DECO_LAMP_CERAMIC = "一个花哨的灯."   --陶瓷灯
DESCRIBE.DECO_LAMP_2EMBROIDERED = "一盏有趣的灯."   --双纹花灯
DESCRIBE.DECO_LAMP_STAINGLASS = "漂亮的灯."   --彩色玻璃灯
DESCRIBE.DECO_CHAIR_OTTOMAN = "座位.踏板.奥斯曼椅功能齐全."   --奥斯曼椅
DESCRIBE.DECO_CHAIR_HORNED = "钉子椅."   --有角的椅子
DESCRIBE.DECO_CHAIR_BENCH = "上面可以坐很多人."   --长凳
DESCRIBE.DECO_CHAIR_CORNER = "上面可以坐人."   --角椅
DESCRIBE.INTERIOR_WALL_CHECKERED = "一大堆有格子花纹的贴在墙上的东西."   --格子墙纸
DESCRIBE.INTERIOR_WALL_FLORAL = "一些漂亮的贴在墙上的东西."   --碎花墙纸
DESCRIBE.INTERIOR_WALL_HARLEQUIN = "漂亮的贴在墙上的纸."   --小丑墙纸
DESCRIBE.INTERIOR_WALL_WOOD = "一捆木头."   --木栅栏
DESCRIBE.HEDGE.GENERIC = "打工是不可能打工的."   --树篱
DESCRIBE.HEDGE.SHAVEABLE = "这辈子是不可能打工的."   --树篱
DESCRIBE.HEDGE.BURNT = "很高兴它结束了."   --树篱
DESCRIBE.HEDGE.BURNING = "它在燃烧."   --树篱
DESCRIBE.INTERIOR_FLOOR_CHECK = "完全是地板."   --格子地板
DESCRIBE.MANDRAKEHOUSE = "它看起来...充满了奇怪的尖叫声."   --曼德拉丘
DESCRIBE.MANDRAKEMAN = "别惹我，不然你会叫得更凄惨."   --曼德拉精
DESCRIBE.ANT_CAVE_LANTERN = "在存在黑暗的地方提供光明."   --灯
DESCRIBE.BILL.GENERIC = "一架带刺的旋转炮塔."   --鸭嘴豪猪
DESCRIBE.BILL.SLEEPING = "炮塔暂时熄火了."   --鸭嘴豪猪
DESCRIBE.BILL.DEAD = "炮塔被我拔掉了."   --鸭嘴豪猪
DESCRIBE.GASMASKHAT = "暂时不怕毒气了."   --防毒面具
DESCRIBE.ALOE_COOKED = "我把它烤熟了!"   --煮熟的芦会
DESCRIBE.GOLD_DUST = "淘出金子也很难买到军火啊."   --砂金
DESCRIBE.DISARMING_KIT = "该用正确的工具解决问题"   --陷阱拆除工具
DESCRIBE.LIFEPLANT = "显然喜欢孤芳自赏."   --魔法花
DESCRIBE.DECO_RUINS_FOUNTAIN = "你能让我看得小圆吗"   --许愿井
DESCRIBE.CLIPPINGS = "打工是……算了，真香."   --碎叶
DESCRIBE.JELLYBUG_COOKED = "我确定它比看上去好吃."   --烤豆虫
DESCRIBE.JELLYBUG = "豆子.长着腿."   --豆虫
DESCRIBE.HIPPOPOTAMOOSE = "皮厚堪比防弹衣."   --鹿角河马
DESCRIBE.DECO_CAVE_BEAM_ROOM = "如果爆破掉这根柱子……."   --不重要的岩柱
DESCRIBE.DECO_RUINS_BEAM_ROOM = "要不要爆破掉这根柱子呢."   --平凡的柱子
DESCRIBE.KINGFISHER.GENERIC = "多么尖利的鸟喙！"   --翠鸟
DESCRIBE.KINGFISHER.SLEEPING = "在睡梦中."   --翠鸟
DESCRIBE.KINGFISHER.DEAD = "死了."   --翠鸟
DESCRIBE.FROGLEGS_POISON = "没法涂到子弹上"   --箭毒蛙腿
DESCRIBE.LOTUS_FLOWER = "里面躺着小圆……好吧，不可能."   --睡莲花
DESCRIBE.ANTHILL = "有一个营的蚂蚁部队."   --蚁窝
DESCRIBE.DECO_CHAIR_ROCKING = "那张椅子在摇动!"   --摇椅
DESCRIBE.LILYPAD = "它充满了科学.我能证明."   --睡莲叶
DESCRIBE.MEAN_FLYTRAP.GENERIC = "极具攻击性，速战速决"   --利齿幼苗
DESCRIBE.MEAN_FLYTRAP.SLEEPING = "安睡吧，恐怖的植物."   --利齿幼苗
DESCRIBE.MEAN_FLYTRAP.DEAD = "别想吃我."   --利齿幼苗
DESCRIBE.ADULT_FLYTRAP.GENERIC = "事先声明，魔法少女是不好吃的."   --捕蝇草
DESCRIBE.ADULT_FLYTRAP.SLEEPING = "嘘..它在睡觉."   --捕蝇草
DESCRIBE.ADULT_FLYTRAP.DEAD = "你非要用生命来验证我的发言吗"   --捕蝇草
DESCRIBE.GRABBING_VINE = "经常悬挂在周围."   --爬藤
DESCRIBE.HANGING_VINE = "经常悬挂在周围."   --悬藤
DESCRIBE.GLOWFLY.GENERIC = "飞舞的流光."   --萤火虫
DESCRIBE.GLOWFLY.COCOON = "对虫子来说温暖又舒适."   --萤火虫
DESCRIBE.GLOWFLY.SLEEPING = "睡得很沉."   --萤火虫
DESCRIBE.GLOWFLY.DEAD = "光芒永远地熄灭了."   --萤火虫
DESCRIBE.HALBERD = "不是我的风格，但是感觉很帅."   --战戟
DESCRIBE.DUNGPILE.GENERIC = "那是一个粪堆."   --粪堆
DESCRIBE.DUNGPILE.PICKED = "便便，还是便便."   --粪堆
DESCRIBE.ANTMAN.GENERIC = "好大一只虫子!"
DESCRIBE.ANTMAN.SLEEPING = "睡去的虫子将继续睡下去."
DESCRIBE.ANTMAN.DEAD = "消灭."
DESCRIBE.BURR = "有小生命在里面,我知道的!"   --丛林毛刺
DESCRIBE.DECO_TABLE_DIY = "非常基本."   --手工桌
DESCRIBE.DECO_TABLE_CHESS = "检查与配对."   --象棋桌
DESCRIBE.DECO_LAMP_FRINGE = "很有趣的灯."   --条纹灯
DESCRIBE.CORKBOAT = "便携式载具，但是没法装下我和小圆."   --碗状软木舟
DESCRIBE.GRASS_TALL.GENERIC = "很难用手来采集."   --高草丛
DESCRIBE.GRASS_TALL.PICKED = "看起来我把它们全采集完了."   --高草丛
DESCRIBE.GRASS_TALL.BURNING = "一株起火的草！"   --高草丛
DESCRIBE.ANTQUEEN = "The Queen regn-ant."   --蚁后
DESCRIBE.DECO_CAVE_BAT_BURROW = "闻起来像是有一百万只大蝙蝠，但是一个魔女都没有."   --幽灵洞
DESCRIBE.BUNDLE = "Our supplies are in there!"   --Bundled Supplies
DESCRIBE.DECO_PLANTHOLDER_BONSAI = "一种种植植物的奇特方法."   --盆景植物种植盆
DESCRIBE.ALLOY = "这个质量……或许可以铸造枪管"   --合金
DESCRIBE.BEESWAX = "保鲜能力很强，用来保存子弹也不错"   --Beeswax
DESCRIBE.ICEDTEA = "还是冰茶更好喝，小圆一定也是这么想的."   --冰茶
DESCRIBE.DECO_TABLE_ROUND = "这是一张圆桌."   --圆桌
DESCRIBE.RELIC_4.GENERIC = "A regal relic."   --蓝色母猪
DESCRIBE.RELIC_4.SUNKEN = "Something fishy down there."   --蓝色母猪
DESCRIBE.SUNKEN_RELIC = "他和鱼一起睡觉。"   --沉落的物品
DESCRIBE.PIG_SCEPTER = "代表身份的宝物，但是不能换成军火"   --权杖
DESCRIBE.PUGALISK_TRAP_DOOR = "额，这看起来相当不吉利。"   --不祥的雕塑
DESCRIBE.RUG_PORCUPUSS = "有人把动物尸体扔在地上。"   --鸭嘴兽地毯
DESCRIBE.RAINFORESTTREE_ROT = "病态生长。"   --生病的雨林树
DESCRIBE.ROC_NEST_DEBRIS4 = "他在一堆棍子中间。"   --风化的树枝
DESCRIBE.SLUGBUG_COOKED = "这东西一定不是这么吃的。"   --烤蛞蝓
DESCRIBE.ROYAL_GALLERY = "花俏的可以和玻璃相比较。"   --皇家画廊展览
DESCRIBE.WINDOW_ROUND_BURLAP = "一点也不高级。"   --麻布窗帘
DESCRIBE.SADDLE_WAR = "The only problem is the saddle sores."   --War Saddle
DESCRIBE.SNAKE_BONE = "我只是拿你一点水，何必送我这么多骨头"   --泥蛇的骨骼
DESCRIBE.PANGOLDEN = "把水放下，那是我的."   --淘金兽
DESCRIBE.PIGMAN_MAYOR.GENERIC = "以后坐在那里的会是我."   --镇长
DESCRIBE.PIGMAN_MAYOR.SLEEPING = "典型的市长.在工作时睡觉."   --镇长
DESCRIBE.TEATREE_NUT_COOKED = "小圆来尝尝茶树种子……啊，她真的不在"   --烤熟茶树种子
DESCRIBE.SHELVES_HATTREE = "一个用来挂你帽子的地方。"   --衣帽架
DESCRIBE.PIGMAN_HATMAKER.GENERIC = "向你致敬，帽匠."
DESCRIBE.PIGMAN_HATMAKER.SLEEPING = "向任何能睡得这么安稳的人致敬."
DESCRIBE.PIGMAN_MINER.GENERIC = "挖出来硝石却不卖给我."   --矿工
DESCRIBE.PIGMAN_MINER.SLEEPING = "你到底把硝石藏哪了."   --矿工
DESCRIBE.TUBER_CROP = "我记得这是有毒的."   --块茎
DESCRIBE.PITHHAT = "简单高效。"   --木帽
DESCRIBE.TURF_PIGRUINS = "这是一块地皮."   --遗迹地皮
DESCRIBE.PIG_RUINS_SPEAR_TRAP = "我想知道里面藏着什么样的奇迹？"   --装饰孔？
DESCRIBE.WINDOW_TALL = "一扇很高的窗户。"   --椭圆玻璃窗
DESCRIBE.PLAYER_HOUSE_TURRET_CRAFT = "建造一个合情合理的住所。"   --角塔配套家具
DESCRIBE.TURF_RAINFOREST = "这是一块地皮."   --雨林地皮
DESCRIBE.SWINGING_LIGHT_TOPHAT = "有人把他们的帽子遗落在这里了."   --高礼帽灯
DESCRIBE.PUGALISK_CORPSE = "石化中。"   --僵硬的骨头
DESCRIBE.PLAYER_HOUSE_COTTAGE = "建造一个迷你住所。"
DESCRIBE.PLAYER_HOUSE_GOTHIC_CRAFT = "建造一个符合你个性的房子。"   --哥特式家具
DESCRIBE.RUINS_ARTICHOKE = "这是一个很大的洋蓟。"   --古老的雕像
DESCRIBE.PLAYERHOUSE_CITY.BURNT = "说不定是毁于煤气事故。"   --歪斜的小木屋
DESCRIBE.PLAYERHOUSE_CITY.FORSALE = "这样的房子没法做我和小圆的婚房"   --歪斜的小木屋
DESCRIBE.PLAYERHOUSE_CITY.SOLD = "甜蜜之家。"   --歪斜的小木屋
DESCRIBE.PARROT_BLUE.GENERIC = "一只天蓝色的鸟."   --鹦鹉
DESCRIBE.PARROT_BLUE.SLEEPING = "它只是在休息."   --鹦鹉
DESCRIBE.PARROT_BLUE.DEAD = "曾经是只鹦鹉."   --鹦鹉
DESCRIBE.TEATREE = "我的弹药是不是被藏到这里了？."   --茶树
DESCRIBE.TUBERTREE = "不，这玩意真的不能吃."   --块茎树
DESCRIBE.PIGMAN_FARMER.GENERIC = "我掏枪会吓到他的."   --农民
DESCRIBE.PIGMAN_FARMER.SLEEPING = "有点吵."   --农民
DESCRIBE.STEAMEDHAMSANDWICH = "汉堡……不长这样吧。"   --蒸火腿三明治
DESCRIBE.PORKLAND_INTRO_SUITCASE = "我不想拖着那件行李到处走。"   --样式单调的行李箱
DESCRIBE.TURF_FOUNDATION = "一些漂亮的鹅卵石组合在一起."   --平整的石制地面
DESCRIBE.WALL_PIG_RUINS = "这是一堵古老的墙."   --古代墙壁
DESCRIBE.SHELVES_CINDERBLOCKS = "它在某个地方可能会派上用场。"   --砖砌书架
DESCRIBE.PIG_SHOP_GENERAL.GENERIC = "小圆，我买点东西给你吃啊。"   --猪和小猪的杂货店
DESCRIBE.PIG_SHOP_GENERAL.BURNING = "那家商店着火了！"   --猪和小猪的杂货店
DESCRIBE.SHELVES_CRATES = "它在某个地方可能会派上用场。"   --板条架
DESCRIBE.PIG_RUINS_SPEAR_TRAP_TRIGGERED = "是的。那些看起来非常致命、"   --肮脏的钉坑
DESCRIBE.PUGALISK_RUINS_PILLAR = "很不稳定"   --摇摇欲坠的支柱
DESCRIBE.PIG_COIN = "买不到子弹"   --猪皮币
DESCRIBE.PIGMAN_BEAUTICIAN.GENERIC = "我不需要美容……吧"   --美容师
DESCRIBE.PIGMAN_BEAUTICIAN.SLEEPING = "她在睡她的美容觉."   --美容师
DESCRIBE.ROC_NEST_DEBRIS2 = "坚持住，大树，坚持。"   --风化的树枝
DESCRIBE.SMASHINGPOT = "没人会把子弹藏在里面吧"   --古代瓦罐
DESCRIBE.PIG_SHOP_PRODUCE.GENERIC = "里面有新鲜的农产品。"   --小镇杂货店
DESCRIBE.PIG_SHOP_PRODUCE.BURNING = "食物着火了！"   --小镇杂货店
DESCRIBE.SECURITYCONTRACT = "我也有自己的使魔了？"   --安保合同
DESCRIBE.RABID_BEETLE.GENERIC = "看起来很疯狂。"   --狂热的甲虫
DESCRIBE.RABID_BEETLE.SLEEPING = "它正在熟睡。"   --狂热的甲虫
DESCRIBE.RABID_BEETLE.DEAD = "总算搞定了。"   --狂热的甲虫
DESCRIBE.RUG_METAL = "我最好测试一下它的金属性能。"   --金属地毯
DESCRIBE.SADDLE_RACE = "This saddle really flies!"   --Glossamer Saddle
DESCRIBE.WAXPAPER = "如我所料，保鲜性能极佳"   --Wax Paper
DESCRIBE.PIGCROWNHAT = "我的王冠会戴在灵魂宝石上……我在想什么."   --王冠
DESCRIBE.PLAYER_HOUSE_TUDOR = "建造一个简单的住所。"
DESCRIBE.PIG_RUINS_TORCH_WALL = "几根棍子或木头能让它亮起来。"   --壁炉
DESCRIBE.PEEKHEN.GENERIC = "它们甚至是相同的物种？"   --偷窥鸡
DESCRIBE.PEEKHEN.SLEEPING = "它在蛰伏."   --偷窥鸡
DESCRIBE.PEEKHEN.DEAD = "了无生机."   --偷窥鸡
DESCRIBE.REEDS_WATER = "水生芦苇。"   --芦苇
DESCRIBE.PLAYER_HOUSE_MANOR_CRAFT = "建造一个大型住所。"   --庄园配套家具
DESCRIBE.SHELVES_MARBLE = "用来放东西的地方。"   --大理石架
DESCRIBE.SHELVES_FRIDGE = "这说不通。"   --冰箱
DESCRIBE.SWINGING_LIGHT_CHANDALIER_CANDLES = "一盏精致的吊灯."   --蜡烛灯
DESCRIBE.PIGGHOST = "从科学上来说完全不可能."   --远古之魄
DESCRIBE.PIG_QUEEN = "她看起来很专横."   --猪人女王
DESCRIBE.OINC10 = "可以买点火药自制子弹？"   --十字呼噜币
DESCRIBE.RUG_CRIME = "杀人凶手。"   --不法者的地毯
DESCRIBE.TURF_GASJUNGLE = "这是一块地皮."   --沼气丛林地皮
DESCRIBE.SWINGING_LIGHT_ROPE_1 = "它可以加添一些装饰."   --绳索吊灯
DESCRIBE.SWINGING_LIGHT_FLORAL_BULB = "精致的灯泡."   --玻璃花灯
DESCRIBE.PIGEON.GENERIC = "你认识东乡美森吗？."   --鸽子
DESCRIBE.PIGEON.SLEEPING = "它在想着乃木园子."   --鸽子
DESCRIBE.PIGEON.DEAD = "它会成为勇者部的一员."   --鸽子
DESCRIBE.PHEROMONESTONE = "战争需要更多情报"   --信息素石
DESCRIBE.PLAYER_HOUSE_VILLA_CRAFT = "建造一个相当大的住所。"   --别墅配套家具
DESCRIBE.PLAYER_HOUSE_BRICK_CRAFT = "建造一个砖砌房子。"   --砖房配套家具
DESCRIBE.OINC100 = "就算有这么多钱，还是买不到子弹"   --百角呼噜币
DESCRIBE.TOPIARY = "想想看，这位艺术家只能用自己的蹄子工作."   --杂乱的植物
DESCRIBE.PIGHOUSE_CITY.GENERIC = "既是一座房子，又是一个家."   --城镇房屋
DESCRIBE.PIGHOUSE_CITY.BURNING = "那房子着火了！"   --城镇房屋
DESCRIBE.SPICYVEGSTINGER = "这个能把小圆灌醉吗"   --辛辣鸡尾酒
DESCRIBE.SALTLICK = "How many licks does it take to get to the center?"   --Saltlick
DESCRIBE.SADDLE_BASIC = "That'll allow the mounting of some smelly animal."   --Saddle
DESCRIBE.SNAKE_AMPHIBIOUS = "像我一样孤独潜行"   --毒蛇
DESCRIBE.PLAYER_HOUSE_COTTAGE_CRAFT = "建造一个迷你住所。"   --小屋配套家具
DESCRIBE.PIGMAN_BANKER.GENERIC = "有钱人."   --银行家
DESCRIBE.PIGMAN_BANKER.SLEEPING = "我见识到银行家的工作方式了."   --银行家
DESCRIBE.PIG_RUINS_SPEAR_TRAP_BROKEN = "你伤不到我"   --破损的钉坑
DESCRIBE.PIG_LATIN_1 = "它上面写着\"埃特雷伊瑞斯费\"."   --一些奇怪的猪的涂鸦
DESCRIBE.RUG_RECTANGLE = "它涵盖了很多地方。"   --大地毯
DESCRIBE.RUG_SQUARE = "算是广场吧。"   --方形地毯
DESCRIBE.RELIC_5.GENERIC = "我宣布，这是小圆的了 "   --宝石松露
DESCRIBE.RELIC_5.SUNKEN = "I found something."   --宝石松露
DESCRIBE.PIG_SHOP_ARCANE.GENERIC = "这可能让我眼前一亮。"   --飞猪 神秘商店
DESCRIBE.PIG_SHOP_ARCANE.BURNING = "知识正在燃烧！"   --飞猪 神秘商店
DESCRIBE.ROC_NEST_EGG2 = "那究竟是什么蛋？"   --石化的蛋
DESCRIBE.RADISH_PLANTED = "他想躲起来。"   --萝卜
DESCRIBE.REDLANTERN = "This lantern feels more special than the others."
DESCRIBE.RUG_CATCOON = "地板上有一个死去的动物。"   --浣猫地毯
DESCRIBE.ROC_NEST_HOUSE = "有人在家吗？"   --饱经风霜的房子
DESCRIBE.SADDLEHORN = "This could take a saddle off."   --Saddlehorn
DESCRIBE.SWINGING_LIGHT_BASIC_BULB = "看起来相当伤心。"   --诡异电灯
DESCRIBE.RUG_OCTAGON = "这是一个地毯。"   --八角地毯
DESCRIBE.TURF_PAINTED = "It's a chunk of ground."   --Painted Sand Turf
DESCRIBE.TURF_BEARD_HAIR = "它是一大块地皮。"   --胡须地皮
DESCRIBE.PORKLAND_INTRO_FLAGS = "它可能引发了一些危险的信号。"   --没有用的彩旗
DESCRIBE.PORKLAND_INTRO_TRUNK = "我就把它放在这里吧。"   --样式单调的行李箱
DESCRIBE.PORKLAND_INTRO_BALLOON = "我的热气球爆炸了。"   --泄气的气球
DESCRIBE.PORKLAND_INTRO_BASKET = "一个彻底的废物。"   --柳条篮
DESCRIBE.RUG_HEDGEHOG = "我可以踩扁你！"   --刺猬地毯
DESCRIBE.RADISH_SEEDS = "它是一个萝卜种子。"   --萝卜种子
DESCRIBE.WALLCRACK_RUINS = "有人毁掉了那些废墟."   --可疑的裂痕
DESCRIBE.SHELVES_GLASS = "用来放东西的地方。"   --玻璃架
DESCRIBE.TRINKET_GIFTSHOP_4 = "罐头里的喜剧."   --整蛊玩具
DESCRIBE.SPRINKLER = "别让枪械受潮了"   --洒水器
DESCRIBE.PEAGAWK_BUSH = "看！一丛鸢尾灌木."   --眨眼的灌木丛
DESCRIBE.PIGMAN_STOREOWNER.GENERIC = "今天你还是没有上货子弹吗？"   --店长
DESCRIBE.PIGMAN_STOREOWNER.SLEEPING = "那不可能舒服."   --店长
DESCRIBE.ROC_NEST_DEBRIS3 = "那些棍子搅和在一起。"   --风化的树枝
DESCRIBE.ROC_NEST_DEBRIS1 = "一个棘手的情况。"   --风化的树枝
DESCRIBE.VAMPIREBATCAVE = "吸血鬼的巢穴."   --蝙蝠地穴
DESCRIBE.TRINKET_GIFTSHOP_3 = "说 \"希望你也在这里.\" "   --皇室明信片
DESCRIBE.TRINKET_GIFTSHOP_1 = "我或许可以用它换些东西."   --玛法拉法女王
DESCRIBE.WATERDROP = "你觉得它是水吗?"   --魔力泉水
DESCRIBE.SHEARS = "剪不断麻美的丝带"   --剪刀
DESCRIBE.SMELTER = "希望炼出来的钢质量能合格"   --炼铁炉
DESCRIBE.PEDESTAL_KEY = "皇家的钥匙."   --皇家画廊钥匙
DESCRIBE.TUBER_BLOOM_CROP_COOKED = "我应该把花也一起煮了吗?"   --烤熟的块茎树花
DESCRIBE.TUBER_CROP_COOKED = "我想知道它是不是仍然存在着毒性?"   --烤熟的树茎
DESCRIBE.TUBER_BLOOM_CROP = "成熟了"   --块茎树花
DESCRIBE.ROC_ROBIN_EGG = "冰冷的石头。"   --岩蛋
DESCRIBE.ROC_NEST_EGG4 = "蛋碎了....."   --石化的蛋
DESCRIBE.ROC_NEST_EGG3 = "那让我紧张的吃了个蛋。"   --石化的蛋
DESCRIBE.ROC_NEST_EGG1 = "就是蛋壳让我说这么多奇怪的话"   --石化的蛋
DESCRIBE.ROC_NEST_RUSTY_LAMP = "破破烂烂又锈迹不堪。"   --生锈的街灯
DESCRIBE.ROC_LEG = "一条巨腿。"   --巨型知更鸟的脚
DESCRIBE.ROC_NEST_BUSH = "看起来很疲倦。"   --风化的灌木丛
DESCRIBE.PIKO_ORANGE = "离我的枪械远一点。"   --橙色松鼠
DESCRIBE.ROC_NEST_TREE1 = "科学说这是一棵树。"   --风化的树木
DESCRIBE.PORKLAND_INTRO = "我已经开始讨厌那家伙了"   --麦斯避役
DESCRIBE.ROC_TAIL = "大限将至。"   --巨型知更鸟的尾巴
DESCRIBE.ROC_HEAD = "真想给他来一梭子"   --巨型知更鸟的头
DESCRIBE.ROC_NEST_TRUNK = "是什么打破了这里的宁静?"   --风化的树桩
DESCRIBE.POG = "这家伙拥有好奇心，行动力和可怕的种群数量"   --帕格狐狸
DESCRIBE.PORKLAND_EXIT = "看起来这就是出路了！"   --天空之椅
DESCRIBE.PORKLAND_ENTRANCE = "良好的家庭娱乐方式。"   --天空之椅
DESCRIBE.SEDIMENTPUDDLE = "淘金池。"   --闪光的水坑
DESCRIBE.THUNDERBIRDNEST = "你的铁会变成我的枪"   --雷鸟巢
DESCRIBE.WEEVOLE_CARAPACE = "我得小心这个甲壳."   --象鼻鼠虫壳
DESCRIBE.THUNDERHAT = "拒绝接受天谴"   --雷电帽
DESCRIBE.THUNDERBIRD = "你还有更多的铁吗"   --雷鸟
DESCRIBE.PLAYER_HOUSE_TURRET = "建造一个合情合理的住所。"
DESCRIBE.PLAYER_HOUSE_GOTHIC = "建造一个符合你个性的房子。"
DESCRIBE.PLAYER_HOUSE_VILLA = "建造一个相当大的住所。"
DESCRIBE.ROCK_FLIPPABLE = "你永远也不知道会在石头下面发现什么。"   --小石板
DESCRIBE.RUG_WORMHOLE = "只是一个复制品。"   --虫洞地毯
DESCRIBE.SHELVES_PALLET = "它在某些地方可能会派上用场。"   --托盘架
DESCRIBE.SHELVES_PIPE = "用来挂东西的地方。"   --水管架
DESCRIBE.SHELVES_HOOKS = "一个用来挂东西的地方。"   --挂钩架
DESCRIBE.SHELVES_AFRAME = "用来放东西的地方"   --A型架
DESCRIBE.SHELVES_WALLMOUNT = "用来放东西的地方。"   --墙上置物架
DESCRIBE.SHELVES_INDUSTRIAL = "多功能。"   --工业货架
DESCRIBE.SHELVES_HUTCH = "用来放东西的地方。"   --储物架
DESCRIBE.SHELVES_LADDER = "当梯子用很不错。"   --梯架
DESCRIBE.SHELVES_MIDCENTURY = "用来放东西的地方。"   --玻璃柜
DESCRIBE.SHELVES_WOOD = "用来放东西的地方。"   --木刻书架
DESCRIBE.RUG_TILES = "几何图形。"   --足球地毯
DESCRIBE.RADISH = "它看起来像萝卜。"   --萝卜
DESCRIBE.RUG_NAILBED = "我想他们做到了。"   --钉床地毯
DESCRIBE.RUG_BEARD = "那是我的面包吗？"   --胡须地毯
DESCRIBE.RUG_BRAID = "这是一个地毯。"   --编织地毯
DESCRIBE.SHELVES_BASIC = "最基本的。"   --书架
DESCRIBE.RUG_WEB = "哦，我们编织的网真乱。"   --网状地毯
DESCRIBE.RUG_RUBBERMAT = "对实验有帮助。"   --橡胶地毯
DESCRIBE.RUG_SWIRL = "原地打转。"   --漩涡地毯
DESCRIBE.RUG_HOOFPRINT = "有个动物经过这里？还是仅仅一个装饰？"   --蹄印地毯
DESCRIBE.RUG_OVAL = "这是一个地毯。"   --椭圆地毯
DESCRIBE.RUG_ROUND = "我感觉有人在监视我。"   --圆地毯
DESCRIBE.TREE_PILLAR = "为我营造了安静的环境"   --大树藤
DESCRIBE.SWINGING_LIGHT_BASIC_METAL = "非常实用。"   --金属电灯
DESCRIBE.SWINGING_LIGHT_PENDANT_CHERRIES = "一盏精致的灯."   --樱桃灯
DESCRIBE.SWINGING_LIGHT_ROPE_2 = "一对无聊的灯."   --双绳吊灯
DESCRIBE.SWINGING_LIGHT_FLORAL_BLOOMER = "一盏精致的吊灯."   --花灯
DESCRIBE.TURF_PLAINS = "It's a chunk of ground."   --Wild Plains Turf
DESCRIBE.WINDOW_TALL_CURTAIN = "一扇很高的窗户。"   --椭圆玻璃窗帘
DESCRIBE.WINDOW_LARGE_SQUARE = "一扇窗。"   --方形窗户
DESCRIBE.WINDOW_SMALL_PEAKED = "一扇窗。"   --椭圆拱窗
DESCRIBE.WINDOW_ROUND_CURTAINS_NAILS = "很奇特的窗户。"   --圆形窗户
DESCRIBE.PUGALISK_SKULL = "一个失去知觉的头盖骨。"   --泥蛇头骨
DESCRIBE.PIGHOUSE_MINE.GENERIC = "我对这里的硝石很感兴趣."   --采石场小屋
DESCRIBE.PIGHOUSE_MINE.BURNING = "这座矿井着火了！"   --采石场小屋
DESCRIBE.SLUGBUG = "这东西或许有自己的吃法"   --糖蛞蝓
DESCRIBE.SHELVES_ADJUSTABLE = "用来放东西的地方。"   --活动架
DESCRIBE.SWINGING_LIGHT_DERBY = "有人把他们的帽子遗落在这里了."   --帽灯
DESCRIBE.PEAGAWKFEATHERHAT = "看！我是一只鸟！"   --孔雀帽
DESCRIBE.PIGBANDIT = "我有权直接击毙你"   --蒙面猪人
DESCRIBE.PLAYER_HOUSE_BRICK = "建造一个砖砌房子。"
DESCRIBE.TURF_COBBLEROAD = "一些漂亮的鹅卵石组合在一起."   --卵石路地皮
DESCRIBE.TURF_FIELDS = "这是一块地皮."   --耕地地皮
DESCRIBE.PIG_PALACE = "恢弘壮丽."   --宫殿
DESCRIBE.TURF_MOSS = "这是一块地皮."   --沼泽地皮
DESCRIBE.TURF_LAWN = "这是一块地皮."   --装饰草坪
DESCRIBE.VAMPIREBAT.GENERIC = "难以命中，需要智取."   --吸血蝙蝠
DESCRIBE.VAMPIREBAT.SLEEPING = "希望它不要再飞起来."   --吸血蝙蝠
DESCRIBE.VAMPIREBAT.DEAD = "我觉得更安全一点了."   --吸血蝙蝠
DESCRIBE.ROC_NEST_TREE2 = "树巢。"   --风化的树木
DESCRIBE.PROP_DOOR = "这是一个推拉门。"   --门
DESCRIBE.ROCK_ANTCAVE = "这是块石头。"   --钟乳石
DESCRIBE.RADISH_COOKED = "我想知道这是否能让它变得更好吃。"   --熟萝卜
DESCRIBE.PIG_RUINS_PRESSURE_PLATE = "哼...我应该避免踩在那上面."   --可疑的石头
DESCRIBE.PIG_RUINS_DART_TRAP = "我希望它不是那么引人注目."   --引人注目的雕像
DESCRIBE.TEATREE_NUT = "你好，树宝宝."   --茶树种子
DESCRIBE.TEA = "麻美比较喜欢热茶"   --茶
DESCRIBE.PUGALISK_FOUNTAIN = "但是它无法拯救我"   --不老泉
DESCRIBE.SNAKEBONESOUP = "买泉送汤，你的骨头还是挺香的"   --骨头汤
DESCRIBE.PUGALISK = "为了泉水送掉性命，不值得"   --泥蛇
DESCRIBE.OINC = "好像不能买到子弹"   --呼噜币
DESCRIBE.PIG_RUINS_ARTICHOKE = "长满了洋蓟."   --残破的雕像
DESCRIBE.PIG_RUINS_HEAD = "我好像在某次轮回中恶补过考古知识"   --残破的面容
DESCRIBE.PIG_RUINS_TORCH = "几根棍子或木头能让它亮起来。"   --破损的火盆
DESCRIBE.TURF_DEEPRAINFOREST = "这是一块地皮."   --热带雨林地皮
DESCRIBE.RELIC_3.GENERIC = "看起来很值钱。"   --遗迹碎片
DESCRIBE.RELIC_3.SUNKEN = "我得把它捞出来。"   --遗迹碎片
DESCRIBE.RELIC_2.GENERIC = "远古文化的遗迹。"   --遗失的图腾
DESCRIBE.RELIC_2.SUNKEN = "沉没在历史遗迹下的绿色东西。"   --遗失的图腾
DESCRIBE.RELIC_1.GENERIC = "无法估价的历史。"   --遗失的神像
DESCRIBE.RELIC_1.SUNKEN = "远古垃圾。"   --遗失的神像
DESCRIBE.PIKO.GENERIC = "不要碰我的弹药，懂吗。"   --松鼠
DESCRIBE.PIKO.SLEEPING = "可能梦见了树。"   --松鼠
DESCRIBE.PIKO.DEAD = "咎由自取。"   --松鼠
DESCRIBE.PEAGAWKFEATHER_PRISM = "我还以为是魔女的东西."   --发光的孔雀羽毛
DESCRIBE.PEAGAWKFEATHER = "真想给小圆看看."   --孔雀羽毛
DESCRIBE.PEAGAWK.GENERIC = "站住，把毛交出来，不然我就开枪了！"   --傻孔雀
DESCRIBE.PEAGAWK.SLEEPING = "非要我自己摘毛吗."   --傻孔雀
DESCRIBE.PEAGAWK.DEAD = "本来想给你留个腿的，何必呢."   --傻孔雀
DESCRIBE.SCORPION.GENERIC = "不会让你伤到小圆的。"   --毒蝎
DESCRIBE.SCORPION.SLEEPING = "现在是碾碎它的最好时机。"   --毒蝎
DESCRIBE.SCORPION.DEAD = "其他的蝎子最好长点记性。"   --毒蝎
DESCRIBE.SNAPDRAGON.GENERIC = "好吧，我不支持你。"   --金鱼草
DESCRIBE.SNAPDRAGON.SLEEPING = "不活泼了。"   --金鱼草
DESCRIBE.SNAPDRAGON.DEAD = "它毫无疑问的死了。"   --金鱼草
DESCRIBE.PIG_RUINS_EXIT = "要不要先回去补给一下？"   --废墟入口
DESCRIBE.PIG_RUINS_ENTRANCE.GENERIC = "要做好万全准备再进去."   --废墟入口
DESCRIBE.PIG_RUINS_ENTRANCE.LOCKED = "用火药当钥匙如何"   --废墟入口
DESCRIBE.RUIN_GIANT_HEAD = "这是进步的一种方式。"   --巨大的雕像
DESCRIBE.RAINFORESTTREE.GENERIC = "一颗热带树。"   --雨林树
DESCRIBE.RAINFORESTTREE.CHOPPED = "不确定它是什么，我被难住了。"   --雨林树
DESCRIBE.RAINFORESTTREE.BURNT = "烧掉了。"   --雨林树
DESCRIBE.RAINFORESTTREE.BURNING = "你也可以变成炭"   --雨林树
DESCRIBE.SPIDER_MONKEY_NEST = "我不想看是什么东西住在那里。"
DESCRIBE.SPIDER_MONKEY.GENERIC = "恐怕用狙击枪都难以一击致命"   --蛛猩
DESCRIBE.SPIDER_MONKEY.SLEEPING = "我不想吵醒它。"   --蛛猩
DESCRIBE.SPIDER_MONKEY.DEAD = "浪费子弹"   --蛛猩
DESCRIBE.PIG_SHOP_ACADEMY.GENERIC = "你们应该是懂行情的吧"   --小镇学会
DESCRIBE.PIG_SHOP_ACADEMY.BURNING = "博物馆着火了！"   --小镇学会
DESCRIBE.PIG_SHOP_HATSHOP.GENERIC = "给小圆买一顶帽子如何？"   --母猪耳 
DESCRIBE.PIG_SHOP_HATSHOP.BURNING = "帽子着火了！"   --母猪耳 帽店
DESCRIBE.TEATREE_SAPLING = "它有些过于微小了."   --茶树苗
DESCRIBE.PIG_SHOP_HOOFSPA.GENERIC = "下次带小圆一起来"   --卷尾泥浆水疗店
DESCRIBE.PIG_SHOP_HOOFSPA.BURNING = "那家疗养店着火了！"   --卷尾泥浆水疗店
DESCRIBE.PIG_SHOP_FLORIST.GENERIC = "给小圆买一束花"   --母猪小姐的花卉店
DESCRIBE.PIG_SHOP_FLORIST.BURNING = "鲜花正在燃烧！"   --母猪小姐的花卉店
DESCRIBE.RECONSTRUCTION_PROJECT.RUBBLE = "会有更好的日子的。"
DESCRIBE.RECONSTRUCTION_PROJECT.SCAFFOLD = "这可以刷上一层油漆。"
DESCRIBE.PIGMAN_HUNTER.GENERIC = "你的枪械实在是不行"
DESCRIBE.PIGMAN_HUNTER.SLEEPING = "不合格的猎手."
DESCRIBE.PIGMAN_PROFESSOR.GENERIC = "你是怎么活到现在的？"
DESCRIBE.PIGMAN_PROFESSOR.SLEEPING = "老年人睡得很多."
DESCRIBE.PIGMAN_ERUDITE.GENERIC = "你好像懂魔法？"
DESCRIBE.PIGMAN_ERUDITE.SLEEPING = "好吧，那是储存噩梦燃料的一种方式."
DESCRIBE.PIGMAN_FLORIST.GENERIC = "有适合送给小圆的花吗"   --花农
DESCRIBE.PIGMAN_FLORIST.SLEEPING = "难道她不会更喜欢一张花床吗？"   --花农
DESCRIBE.PIGMAN_MECHANIC.GENERIC = "修理先生."   --工人
DESCRIBE.PIGMAN_MECHANIC.SLEEPING = "他在休息."   --工人
DESCRIBE.PIGMAN_COLLECTOR.GENERIC = "你收藏枪械吗？"   --收藏家
DESCRIBE.PIGMAN_COLLECTOR.SLEEPING = "他在打盹."   --收藏家
DESCRIBE.WINDOW_LARGE_SQUARE_CURTAIN = "让阳光照进来。"   --大方形窗帘
DESCRIBE.ZEB.GENERIC = "世界不是非黑即白的。"   --斑马
DESCRIBE.ZEB.SLEEPING = "午休时间！"   --斑马
DESCRIBE.ZEB.DEAD = "死亡"   --斑马
DESCRIBE.WARDROBE.GENERIC = "可以储存一些军火"
DESCRIBE.WARDROBE.BURNT = "那个已经落伍了。"   --烧焦的
DESCRIBE.WARDROBE.BURNING = "烧！烧！烧！"
DESCRIBE.WEEVOLE = "哟!"   --象鼻鼠虫
DESCRIBE.ROC_NEST_BRANCH1 = "有什么大家伙把它搬到这里了。"   --风化的树枝
DESCRIBE.PIG_SHOP_WEAPONS.GENERIC = "怎么不卖c4？"   --野猪獠牙 武器店
DESCRIBE.PIG_SHOP_WEAPONS.BURNING = "会不会爆炸？"   --野猪獠牙 武器店
DESCRIBE.VENUS_STALK = "或许可以用作火绳……太落后了"   --捕蝇草根
DESCRIBE.PLAYER_HOUSE_TUDOR_CRAFT = "建造一个简单的住所。"   --都铎配套家具
DESCRIBE.RUG_FUR = "有人把动物尸体扔在地上。"   --毛皮地毯
DESCRIBE.SWINGING_LIGHT_FLORAL_SCALLOP = "一盏精致的吊灯."   --美丽花灯
DESCRIBE.PORKLAND_INTRO_SANDBAG = "这好像也能做成掩体。"   --沙袋
DESCRIBE.PIGMAN_ROYALGUARD.GENERIC = "这里有没有禁枪令？"   --皇家守卫
DESCRIBE.PIGMAN_ROYALGUARD.SLEEPING = "你又没有军火，睡着了也没区别"   --皇家守卫
DESCRIBE.PIGHOUSE_FARM.GENERIC = "它们过着平和的生活."   --农场小屋
DESCRIBE.PIGHOUSE_FARM.BURNING = "那座农场着火了！"   --农场小屋
DESCRIBE.PIG_RUINS_CREEPING_VINES = "令人毛骨悚然的爬虫."   --藤蔓
DESCRIBE.WALKINGSTICK = "盗取军火的重要装备"   --潜行手杖
DESCRIBE.PLAYER_HOUSE_MANOR = "建造一个大型住所。"
DESCRIBE.ROC_NEST_BRANCH2 = "也许他在扩张。"   --风化的树枝
DESCRIBE.SPIDER_MONKEY_TREE = "木头做的。"   --布满蛛网的树
DESCRIBE.PIG_GUARD_TOWER.GENERIC = "盗取军火的障碍"   --观望塔
DESCRIBE.PIG_GUARD_TOWER.BURNING = "这座塔着火了！"   --观望塔

return speech
