--MANUTSAWEE SKILL TEXT...

GLOBAL.TUNING.MANUTSAWEESKILLSPEECH = {

--Skill (1)
	SKILL1START = "技一 准备!\n󰀈: ",
	SKILL1ATTACK = "来呀！",
	
--Skill (2)
	SKILL2START = "技二 准备！\n󰀈: ",
	SKILL2ATTACK = "笨蛋！",
	
--Skill (3)
	SKILL3START = "技三 准备！\n󰀈: ",
	SKILL3ATTACK = "猪头!",

--Skill (4)
	SKILL4START = "技四 准备！\n󰀈: ",
	SKILL4ATTACK = "去死！",

--Skill (5)
	SKILL5START = "技五 准备！\n󰀈: ",
	SKILL5ATTACK = "安息吧！",

--Skill (6)
	SKILL6START = "技六 准备！\n󰀈: ",
	SKILL6ATTACK = "结束了！",

	
--Skill (7)
	SKILL7START = "技七 准备！\n󰀈: ",
	SKILL7ATTACK = "必杀！",

}
--item
--Scarf
STRINGS.NAMES.M_SCARF = "黑围巾"
STRINGS.RECIPE_DESC.M_SCARF = "黑围巾。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.M_SCARF = "冬天来的时候会很好。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.M_SCARF = "让你的内心温暖而模糊。外面也一样。"

--maid
STRINGS.NAMES.MAID_HB = "头饰三合一"
STRINGS.RECIPE_DESC.MAID_HB = "女仆头带，忍者头带，鬼面罩。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MAID_HB = "看起来不错。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.MAID_HB = "这太可爱了。"

--foxmask
STRINGS.NAMES.M_FOXMASK = "狐狸面具"
STRINGS.RECIPE_DESC.M_FOXMASK = "狐狸面具！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.M_FOXMASK = "多漂亮的面具啊！."
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.M_FOXMASK = "现在我是一只狐狸！。"

--samurai helmet general
STRINGS.NAMES.MKABUTO = "星兜"
STRINGS.RECIPE_DESC.MKABUTO = "武士的头盔。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MKABUTO = "这样我就安全了。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.MKABUTO = "我是武士。"

--samurai helmet troop
STRINGS.NAMES.MKABUTO2 = "月兜"
STRINGS.RECIPE_DESC.MKABUTO2 = "古代武士的头盔。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MKABUTO2 = "这应该可以保证我的安全。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.MKABUTO2 = "我是武士。"

--miko
STRINGS.NAMES.MMIKO_ARMOR = "巫女长袍"
STRINGS.RECIPE_DESC.MMIKO_ARMOR = "搭配巫女皮肤的长袍"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MMIKO_ARMOR = "不适合我。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.MMIKO_ARMOR = "这件长袍适合巫女服装。"

--memoryfruit
STRINGS.NAMES.MFRUIT = "路易斯的记忆果实"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MFRUIT = "水果？"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.MFRUIT = "恢复记忆。"

----------------------------------------------------------------------------------
--ingot
--normal
STRINGS.NAMES.MINGOT = "神秘的铸块"
STRINGS.RECIPE_DESC.MINGOT = "可以加热"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MINGOT = "这是什么？"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.MINGOT = "把它放入火里之后再用锤子敲打。"
--hot
STRINGS.NAMES.HMINGOT = "烧红的铸块"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HMINGOT = "非常热！"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.HMINGOT = "就是现在！用锤子一直敲打它！"
--shape
STRINGS.NAMES.KATANABODY = "武士刀模具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KATANABODY = "那又怎样？"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.KATANABODY = "用绳子包裹并磨快。"

----------------------------------weapon
--harakiri
STRINGS.NAMES.HARAKIRI = "切腹刀"
STRINGS.RECIPE_DESC.HARAKIRI = "为你的错误付出代价。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HARAKIRI = "这把刀看起来很好。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.HARAKIRI = "为了荣誉！。"

--woodsword shinai
STRINGS.NAMES.SHINAI = "竹刀"
STRINGS.RECIPE_DESC.SHINAI = "用来练习剑术。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHINAI = "这有用吗？"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.SHINAI = "我可以训练我的剑术等级 󰀍 用这个！ "

--katana
STRINGS.NAMES.MKATANA = "武士刀"
STRINGS.RECIPE_DESC.MKATANA = "日本刀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MKATANA = "这是一把剑。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.MKATANA = "这是一把武士刀。"

--Naginata
STRINGS.NAMES.MNAGINATA = "薙刀"
STRINGS.RECIPE_DESC.MNAGINATA = "这是一种日本刀。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MNAGINATA = "这把刀看起来不一样。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.MNAGINATA = "长~刀~~~"

--yari
STRINGS.NAMES.YARI = "亚里"
STRINGS.RECIPE_DESC.YARI = "这是日本长矛。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YARI = "这把矛看起来不一样。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.YARI = "它在大范围穿刺和砍杀方面都非常出色！"

--blade
STRINGS.NAMES.KATANABLADE = "雷切的刀刃"
STRINGS.RECIPE_DESC.KATANABLADE = "锋利的武士刀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KATANABLADE = "没有剑柄可以用吗？"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.KATANABLADE = "我可以不用剑柄。"

--nihiru
STRINGS.NAMES.HITOKIRI = "血印 · 雷切"
STRINGS.RECIPE_DESC.HITOKIRI = "嗜血刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HITOKIRI = "多奇怪的剑啊。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.HITOKIRI = "这会让我生气的。"

STRINGS.NAMES.HITOKIRI2 = "真 · 血印 · 雷切"
STRINGS.RECIPE_DESC.HITOKIRI2 = "真 · 嗜血刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HITOKIRI2 = "多奇怪的剑啊。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.HITOKIRI2 = "这会让我生气的。"

--ssakura
STRINGS.NAMES.KOSHIRAE = "苍龙 · 雷切"
STRINGS.RECIPE_DESC.KOSHIRAE = "上帝的错误。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KOSHIRAE = "多漂亮的剑啊！"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.KOSHIRAE = "一把甚至可以杀死神的剑。"

STRINGS.NAMES.KOSHIRAE2 = "真 · 苍龙 · 雷切"
STRINGS.RECIPE_DESC.KOSHIRAE2 = "真 · 巨兽杀手！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KOSHIRAE2 = "多漂亮的剑啊。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.KOSHIRAE2 = "大小不重要。"

--shirasaya
STRINGS.NAMES.SHIRASAYA = "魔刃 · 雷切"
STRINGS.RECIPE_DESC.SHIRASAYA = "魔刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHIRASAYA = "多漂亮的剑啊。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.SHIRASAYA = "来吧，我会杀了你们所有人……恶魔！"

STRINGS.NAMES.SHIRASAYA2 = "真 · 魔刃 · 雷切"
STRINGS.RECIPE_DESC.SHIRASAYA2 = "真 · 魔刃"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHIRASAYA2 = "多漂亮的剑啊。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.SHIRASAYA2 = "来吧，我会杀了你们所有人……恶魔！"

--raikiri
STRINGS.NAMES.RAIKIRI = "雷切"
STRINGS.RECIPE_DESC.RAIKIRI = "它叫闪电切割机(雷切)。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAIKIRI = "多漂亮的剑啊！"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.RAIKIRI = "我美丽的雷切，这是我家族的珍宝。"

STRINGS.NAMES.RAIKIRI2 = "真 · 雷切"
STRINGS.RECIPE_DESC.RAIKIRI2 = "它叫真 · 雷切"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.RAIKIRI2 = "这把剑看起来很危险，别碰它。"
STRINGS.CHARACTERS.MANUTSAWEE.DESCRIBE.RAIKIRI2 = "我美丽的雷切，曾经用来劈一道闪电。"