name = "M. louis（汉化）"
description = "不要修改这个作品。 \n但是你可以修复这个bug或者重新加载更强大的版本。\nManutsawee太长了 改为M. louis\n[教程]为修改后的角色制作自定义皮肤！作者：Hornete\n以上为作者介绍\n\n汉化：富萝莉"
author = "#ffffff 汉化：富萝莉"
version = "2023.4.28" 
forumthread = ""

api_version = 10
priority = -1

dst_compatible = true

dont_starve_compatible = false
reign_of_giants_compatible = false
shipwrecked_compatible = false

all_clients_require_mod = true 

icon_atlas = "modicon.xml"
icon = "modicon.tex"

server_filter_tags = {
"character",
}


local function Header(title)
	return { name = "", label = title, hover = "", options = { {description = "", data = false}, }, default = false, }
end

local function Space()
	return { name = "", label = "", hover = "", options = { {description = "", data = false}, }, default = false, }
end


configuration_options = {	
		
        Header("设定"),
    {
        name = "manutsaweestartitem",
        label = "初始武器",
        hover = "选择开始用的武器",
        options =
        {
            {description="两手空空", data = 0},
            {description="竹刀", data = 1}, 
            {description="雷切", data = 2},            
            {description="简易 · 雷切", data = 3},            
            {description="苍龙 · 雷切", data = 4},           
            {description="雷切的刀刃", data = 5},          
            {description="血印 · 雷切", data = 6},  
        },
        default = 0,
    },	
    {
        name = "manutsaweenidle",
        label = "空闲动画",
        hover = "Wilson",
        options =
        {
            {description="关", data = false},
            {description="开", data = true},            
        },
        default = false,
    },
    {
        name = "manutsaweensmall",
        label = "娇小人物",
        hover = "比其他初始角色小？",
        options =
        {
            {description="Off", data = false},
            {description="On", data = true},            
        },
        default = false,
    },  
		Space(),
        Header("童子军技能"),
    {
        name = "manutsaweetent",
        label = "可移动帐篷",
        hover = "",
        options =
        {
            {description="Off", data = false},
            {description="On", data = true},            
        },
        default = false,
    },
	{
        name = "manutsaweenstick",
        label = "弹弓可用",
        hover = "",
        options =
        {
            {description="Off", data = false},
            {description="On", data = true},            
        },
        default = false,
    },	
		Space(),
		Header("角色基础值设定"),
	{
        name = "manutsaweehunger",
        label = "饥饿值 󰀎",
        hover = "设定值",
        options =
        {
			{description="50", data = 50},
			{description="60", data = 60},
			{description="70", data = 70},
            {description="80", data = 80},
            {description="90", data = 90},
            {description="100", data = 100},
            {description="110", data = 110},
            {description="120", data = 120},
            {description="130", data = 130},
            {description="140", data = 140},
            {description="150", data = 150},
            {description="160", data = 160},
            {description="170", data = 170},
            {description="180", data = 180},
            {description="190", data = 190},
            {description="200", data = 200},
            {description="210", data = 210},
            {description="220", data = 220},
            {description="230", data = 230},
            {description="240", data = 240},
            {description="250", data = 250},
            {description="300", data = 300},
                   
        },
        default = 150,
    },
	{
        name = "manutsaweehealth",
        label = "生命值 󰀍",
        hover = "设定值",
        options =
        {
            {description="50", data = 50},
			{description="60", data = 60},
			{description="70", data = 70},
            {description="80", data = 80},
            {description="90", data = 90},
            {description="100", data = 100},
            {description="110", data = 110},
            {description="120", data = 120},
            {description="130", data = 130},
            {description="140", data = 140},
            {description="150", data = 150},
            {description="160", data = 160},
            {description="170", data = 170},
            {description="180", data = 180},
            {description="190", data = 190},
            {description="200", data = 200},
            {description="210", data = 210},
            {description="220", data = 220},
            {description="230", data = 230},
            {description="240", data = 240},
            {description="250", data = 250},
            {description="300", data = 300},
                      
        },
        default = 200,
    },
	{
        name = "manutsaweesanity",
        label = "理智值 󰀓",
        hover = "设定值",
        options =
        {	
			{description="50", data = 50},
			{description="60", data = 60},
			{description="70", data = 70},
            {description="80", data = 80},
            {description="90", data = 90},
            {description="100", data = 100},
            {description="110", data = 110},
            {description="120", data = 120},
            {description="130", data = 130},
            {description="140", data = 140},
            {description="150", data = 150},
            {description="160", data = 160},
            {description="170", data = 170},
            {description="180", data = 180},
            {description="190", data = 190},
            {description="200", data = 200},
            {description="210", data = 210},
            {description="220", data = 220},
            {description="230", data = 230},
            {description="240", data = 240},
            {description="250", data = 250},
            {description="300", data = 300},
                   
        },
        default = 200,
    },
	{
        name = "manutsaweehungermax",
        label = "升级后饥饿增加",
        hover = "",
        options =
        {
            {description="0", data = 0},
            {description="10", data = 1},
			{description="20", data = 2},
			{description="30", data = 3},
            {description="40", data = 4},
            {description="50", data = 5},           
            {description="60", data = 6},           
            {description="70", data = 7},           
            {description="80", data = 8},           
            {description="90", data = 9},           
            {description="100", data = 10},         
            {description="110", data = 11},         
            {description="120", data = 12},         
            {description="130", data = 13},         
            {description="140", data = 14},         
            {description="150", data = 15},         
            {description="160", data = 16},         
            {description="170", data = 17},         
            {description="180", data = 18},         
            {description="190", data = 19},         
            {description="200", data = 20},         
                      
        },
        default = 0,
    },
	{
        name = "manutsaweehealthmax",
        label = "升级后血量增加",
        hover = "",
        options =
        {
            {description="0", data = 0},
            {description="10", data = 1},
			{description="20", data = 2},
			{description="30", data = 3},
            {description="40", data = 4},
            {description="50", data = 5},           
            {description="60", data = 6},           
            {description="70", data = 7},           
            {description="80", data = 8},           
            {description="90", data = 9},           
            {description="100", data = 10},         
            {description="110", data = 11},         
            {description="120", data = 12},         
            {description="130", data = 13},         
            {description="140", data = 14},         
            {description="150", data = 15},         
            {description="160", data = 16},         
            {description="170", data = 17},         
            {description="180", data = 18},         
            {description="190", data = 19},         
            {description="200", data = 20},               
                      
        },
        default = 0,
    },
	{
        name = "manutsaweesanitymax",
        label = "升级后理智增加",
        hover = "",
        options =
        {
            {description="0", data = 0},
            {description="10", data = 1},
			{description="20", data = 2},
			{description="30", data = 3},
            {description="40", data = 4},
            {description="50", data = 5},           
            {description="60", data = 6},           
            {description="70", data = 7},           
            {description="80", data = 8},           
            {description="90", data = 9},           
            {description="100", data = 10},         
            {description="110", data = 11},         
            {description="120", data = 12},         
            {description="130", data = 13},         
            {description="140", data = 14},         
            {description="150", data = 15},         
            {description="160", data = 16},         
            {description="170", data = 17},         
            {description="180", data = 18},         
            {description="190", data = 19},         
            {description="200", data = 20},                
                      
        },
        default = 0,
    },
	{
        name = "manutsaweemindmax",
        label = "升级后技能点增加󰀈",
        hover = "升级后技能点增加",
        options =
        {            
            {description="2", data = 2},          
            {description="3", data = 3},   
            {description="4", data = 4},   
            {description="5", data = 5},   
            {description="6", data = 6},   
            {description="7", data = 7},   
            {description="8", data = 8},   
            {description="9", data = 9},   
            {description="10", data = 10}, 
            {description="15", data = 15},
            {description="20", data = 20},
        },
        default = 2,
    },
	{
        name = "manutsaweemindregenrate",
        label = "心灵󰀈 恢复最大的一半/秒 ",
        hover = "心灵再生。",
        options =
        {   
			{description="10", data = 10},   
            {description="20", data = 20},   
            {description="30", data = 30},   
            {description="60", data = 60},   
            {description="90", data = 90},   
            {description="120", data = 120},   
            {description="150", data = 150},   
            {description="180", data = 180},   
            {description="210", data = 210},   
            {description="240", data = 240},   
            {description="270", data = 270},   
            {description="300", data = 300},  
            {description="360", data = 360},  
            {description="420", data = 420},
        },
        default = 300,
    },	
	{
        name = "manutsaweemindregen",
        label = "技能点回复 / 攻击次数 ",
        hover = "心灵回复/用武士刀攻击。",
        options =
        {           
            {description="4", data = 4},           
            {description="6", data = 6},             
            {description="8", data = 8},            
            {description="10", data = 10},   
            {description="12", data = 12},              
            {description="14", data = 14},   
            {description="16", data = 16},
            {description="18", data = 18},
            {description="20", data = 20},
        },
        default = 10,
    },
    {
        name = "mscridmg",
        label = "暴击倍数",
        hover = "暴击倍数",
        options =
        {           
            {description="默认110%", data = 0.1},          
            {description="2", data = 2},          
            {description="2.5", data = 2.5},       
            {description="5", data = 5},            
        },
        default = 0.1,
    },
	----------------------------------------------------------
        Space(),
        Header("自定义武器伤害"),
    {
        name = "manutsaweekatanadmg",
        label = "设置中阶武士刀伤害",
        hover = "中阶武士刀伤害",
        options =
        {
            {description="42", data = 42.5},
            {description="45", data = 45},
            {description="55", data = 55},
            {description="60", data = 60},
            {description="68", data = 68},
            {description="75", data = 75},
            {description="82", data = 82},
            {description="90", data = 90},
            {description="100", data = 100},
            {description="110", data = 110},
            {description="120", data = 120},
            {description="150", data = 150},
            {description="200", data = 200},
            {description="300", data = 300},
            {description="500", data = 500},
            {description="1000", data = 1000},       
        },
        default = 68,
    },
    {
        name = "manutsaweekatana2dmg",
        label = "设置高阶武士刀伤害",
        hover = "高阶武士刀伤害",
        options =
        {
            {description="42", data = 42.5},
            {description="45", data = 45},
            {description="55", data = 55},
            {description="60", data = 60},
            {description="68", data = 68},
            {description="75", data = 75},
            {description="82", data = 82},
            {description="90", data = 90},
            {description="100", data = 100},
            {description="110", data = 110},
            {description="120", data = 120},
            {description="150", data = 150},
            {description="200", data = 200},
            {description="300", data = 300},
            {description="500", data = 500},
            {description="1000", data = 1000},
            
                   
        },
        default = 82,
    },	
        {
        name = "manutsaweespeardmg",
        label = "设置长矛伤害",
        hover = "亚里和薙刀",
        options =
        {
            {description="42", data = 42.5},
            {description="45", data = 45},
            {description="55", data = 55},
            {description="60", data = 60},
            {description="68", data = 68},
            {description="75", data = 75},
            {description="82", data = 82},
            {description="90", data = 90},
            {description="100", data = 100},
            {description="110", data = 110},
            {description="120", data = 120},
            {description="150", data = 150},
            {description="200", data = 200},
            {description="300", data = 300},
            {description="500", data = 500},
            {description="1000", data = 1000},
            
                   
        },
        default = 42.5,
    },
-----------------------------------------------------------------------------
        Space(),
        Header("定制剑术"),
    {
        name = "manutsaweekexpmtp",
        label = "剑术经验获取倍率",
        hover = "快速剑术经验增益。",
        options =
        {
            {description="No", data = 1},
            {description="x2", data = 2},          
            {description="x3", data = 3},
            {description="x4", data = 4},   
            {description="x5", data = 5},   
        },
        default = 1,
    },
	{
        name = "manutsaweemaster",
         label = "设定初始剑术等级",
        hover = "在开始时设置剑术等级。",
        options =
        {
            {description="(Off)", data = false},
            {description="On", data = true},            
        },
        default = false,
    },
    {
        name = "manutsaweemastervalue",
        label = "初始剑术等级",
        hover = "设置剑术等级。",
        options =
        {
            {description="1", data = 1},
            {description="2", data = 2},          
            {description="3", data = 3},   
            {description="4", data = 4},   
            {description="5", data = 5},            
            {description="6", data = 6},            
            {description="7", data = 7},            
            {description="8", data = 8},            
            {description="9", data = 9},           
            {description="10", data = 10},           
        },
        default = 1,
    },
		
		Space(),
        Header("技能开关 󰀈"),
    {
        name = "manutsaweeskill",
        label = "技能 󰀈",
        hover = "打开或关闭角色技能。",
        options =
        {
            {description="Off", data = false},
            {description="On", data = true},            
        },
        default = true,
	},
	Space(),
	{
        name = "mkeyskill1",
        label = "技能1",
        hover = "技能1",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 114,
    },
	{
        name = "mkeyskill2",
        label = "技能2",
        hover = "技能2",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 99,
    },	
	
	{
        name = "mkeyskill3",
        label = "技能3",
        hover = "技能3",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 116,
    },
	
	{
        name = "mkeyskillcounteratk",
        label = "反击与招架",
        hover = "最佳时机反击&如果不是最佳时机反击就招架",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 122,
    },
	{
        name = "mkeyquicksheath",
        label = "快速收拔刀",
        hover = "快速收拔刀",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 120,
    },
	{
        name = "mkeyskillcancel",
        label = "取消技能准备",
        hover = "取消所有技能",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 118,
    },
		Space(),
	{
        name = "mscdct",
        label = "技能一冷却时间（秒）",
        hover = "设置技能冷却时间",
        options =
        {
            {description="0.5", data = .5},
            {description="1", data = 1},
            {description="2", data = 2},
            {description="3", data = 3},
            {description="4", data = 4},
            {description="5", data = 5},
            {description="10", data = 10},
            {description="Default(20)", data = 20},          
            {description="30", data = 30},   
            {description="40", data = 40},   
            {description="50", data = 50},            
            {description="60", data = 60},            
            {description="120", data = 120},            
            {description="180", data = 180},            
            {description="240", data = 240},          
            {description="300", data = 300},         
            {description="360", data = 360},         
        },
        default = 20,
    },
	{
        name = "mscd1",
        label = "技能二冷却时间（秒）",
        hover = "设置技能冷却时间",
        options =
        {
			{description="5", data = 5},
            {description="10", data = 10},
            {description="20", data = 20},          
            {description="30", data = 30},
            {description="40", data = 40}, 
			{description="Default(45)", data = 45},  
            {description="50", data = 50},            
            {description="60", data = 60},            
            {description="120", data = 120},            
            {description="180", data = 180},            
            {description="240", data = 240},          
            {description="300", data = 300},         
            {description="360", data = 360},         
        },
        default = 45,
    },
	{
        name = "mscd2",
        label = "技能三冷却时间（秒）",
        hover = "设置技能冷却时间",
        options =
        {
			{description="5", data = 5},
            {description="10", data = 10},
            {description="20", data = 20},          
            {description="30", data = 30},   
            {description="40", data = 40},
			 {description="Default(45)", data = 45},  
            {description="50", data = 50},            
            {description="60", data = 60},            
            {description="120", data = 120},            
            {description="180", data = 180},            
            {description="240", data = 240},          
            {description="300", data = 300},         
            {description="360", data = 360},         
        },
        default = 45,
    },
	{
        name = "mscd3",
        label = "技能四冷却时间（秒）",
        hover = "设置技能四冷却时间",
        options =
        {
			{description="5", data = 5},
            {description="10", data = 10},
            {description="20", data = 20},          
            {description="30", data = 30},   
            {description="40", data = 40},  
            {description="Default(45)", data = 45},  
            {description="50", data = 50},            
            {description="60", data = 60},            
            {description="120", data = 120},            
            {description="180", data = 180},            
            {description="240", data = 240},          
            {description="300", data = 300},         
            {description="360", data = 360},         
        },
        default = 45,
    },
	{
        name = "mscdt2",
        label = "技能五冷却时间（秒）",
        hover = "设置技能五冷却时间。",
        options =
        {              
            {description="50", data = 50},            
            {description="60", data = 60},            
            {description="Default(90)", data = 90},            
            {description="120", data = 120},            
            {description="150", data = 150},            
            {description="180", data = 180},            
            {description="240", data = 240},          
            {description="300", data = 300},         
            {description="360", data = 360},         
        },
        default = 90,
    },
	{
        name = "mscdt3",
        label = "技能六冷却时间（秒）",
        hover = "设置技能六冷却时间",
        options =
        {      
            {description="90", data = 90},          
            {description="120", data = 120},           
            {description="150", data = 150},           
            {description="180", data = 180},            
            {description="Default(210)", data = 210},        
            {description="240", data = 240},        
            {description="300", data = 300},         
            {description="360", data = 360},         
        },
        default = 210,
    },
            Space(),
            Header("其他设定 󰀮"),   
        {
        name = "glasses",
        label = "摘戴眼镜 󰀅",
        hover = "戴眼镜。",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 111,
    },
	
	{
        name = "Hairs",
        label = "改变发型 󰀖",
        hover = "这是改变发型的关键。",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 108,
    },	
			
	{
        name = "levelcheck",
        label = "查看等级 󰀙",
        hover = "这是显示级别的关键用途。",
        options =
        {
            {description="TAB", data = 9},
            {description="KP_PERIOD", data = 266},
            {description="KP_DIVIDE", data = 267},
            {description="KP_MULTIPLY", data = 268},
            {description="KP_MINUS", data = 269},
            {description="KP_PLUS", data = 270},
            {description="KP_ENTER", data = 271},
            {description="KP_EQUALS", data = 272},
            {description="MINUS", data = 45},
            {description="EQUALS", data = 61},
            {description="SPACE", data = 32},
            {description="ENTER", data = 13},
            {description="ESCAPE", data = 27},
            {description="HOME", data = 278},
            {description="INSERT", data = 277},
            {description="DELETE", data = 127},
            {description="END", data   = 279},
            {description="PAUSE", data = 19},
            {description="PRINT", data = 316},
            {description="CAPSLOCK", data = 301},
            {description="SCROLLOCK", data = 302},
            {description="RSHIFT", data = 303}, -- use SHIFT instead
            {description="LSHIFT", data = 304}, -- use SHIFT instead
            {description="RCTRL", data = 305}, -- use CTRL instead
            {description="LCTRL", data = 306}, -- use CTRL instead
            {description="RALT", data = 307}, -- use ALT instead
            {description="LALT", data = 308}, -- use ALT instead
            {description="ALT", data = 400},
            {description="CTRL", data = 401},
            {description="SHIFT", data = 402},
            {description="BACKSPACE", data = 8},
            {description="PERIOD", data = 46},
            {description="SLASH", data = 47},
            {description="LEFTBRACKET", data     = 91},
            {description="BACKSLASH", data     = 92},
            {description="RIGHTBRACKET", data = 93},
            {description="TILDE", data = 96},
            {description="A", data = 97},
            {description="B", data = 98},
            {description="C", data = 99},
            {description="D", data = 100},
            {description="E", data = 101},
            {description="F", data = 102},
            {description="G", data = 103},
            {description="H", data = 104},
            {description="I", data = 105},
            {description="J", data = 106},
            {description="K", data = 107},
            {description="L", data = 108},
            {description="M", data = 109},
            {description="N", data = 110},
            {description="O", data = 111},
            {description="P", data = 112},
            {description="Q", data = 113},
            {description="R", data = 114},
            {description="S", data = 115},
            {description="T", data = 116},
            {description="U", data = 117},
            {description="V", data = 118},
            {description="W", data = 119},
            {description="X", data = 120},
            {description="Y", data = 121},
            {description="Z", data = 122},
            {description="F1", data = 282},
            {description="F2", data = 283},
            {description="F3", data = 284},
            {description="F4", data = 285},
            {description="F5", data = 286},
            {description="F6", data = 287},
            {description="F7", data = 288},
            {description="F8", data = 289},
            {description="F9", data = 290},
            {description="F10", data = 291},
            {description="F11", data = 292},
            {description="F12", data = 293},
 
            {description="UP", data = 273},
            {description="DOWN", data = 274},
            {description="RIGHT", data = 275},
            {description="LEFT", data = 276},
            {description="PAGEUP", data = 280},
            {description="PAGEDOWN", data = 281},
 
            {description="0", data = 48},
            {description="1", data = 49},
            {description="2", data = 50},
            {description="3", data = 51},
            {description="4", data = 52},
            {description="5", data = 53},
            {description="6", data = 54},
            {description="7", data = 55},
            {description="8", data = 56},
            {description="9", data = 57},
        },
        default = 112,
    },
	Space(),
}