GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})
--这里是所有的介绍相关的，RECIPE是配方上的话，CHARACTERS是检查语句

STRINGS.NAMES.TZ_JRBY = "烬染不夜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_JRBY = "看那满天星火，愿此刻永恒"

STRINGS.NAMES.TA_WZK_ARMOR = "王之铠 : 浩瀚"
STRINGS.RECIPE_DESC.TA_WZK_ARMOR = "王之浩瀚，可容万物\n需要【明亮10】帝王结晶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TA_WZK_ARMOR = "太强了！"
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.BUILD.NOPUGALISK_CRYSTAL = "未找到【明亮10】帝王结晶"

STRINGS.NAMES.TZ_TRUTHBASKETBALL = "星际之鲲：真理篮球"
STRINGS.RECIPE_DESC.TZ_TRUTHBASKETBALL = "爱坤打开星际之门，用真理篮球协助召唤者统治永恒大陆"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_TRUTHBASKETBALL = "当!当!当!当!"

STRINGS.NAMES.TZ_COIN = "宝藏硬币"
STRINGS.RECIPE_DESC.TZ_COIN = "会有怪兽喜欢吃这个么？"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_COIN = "再摇一次！"

STRINGS.NAMES.TZ_DROGENBOX = "神秘古代器皿"
STRINGS.RECIPE_DESC.TZ_DROGENBOX = "神秘国度贮存食物的器皿"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_DROGENBOX = "我喜欢这个冰箱！"

STRINGS.NAMES.ZHANLI = "科学鲲与魔法篮球"
STRINGS.RECIPE_DESC.ZHANLI = "NBA形象大使已经突破科学和魔法的限制"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ZHANLI = "当！当！当！当！"

STRINGS.NAMES.TZ_HLMJ = "狐灵面具"
STRINGS.RECIPE_DESC.TZ_HLMJ = "戴上面具变成肥桃花"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_HLMJ = "大狐狸！"

STRINGS.NAMES.TZ_ECYBALLOONSPEED = "二次元气球"
STRINGS.RECIPE_DESC.TZ_ECYBALLOONSPEED = "二次元气球！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_ECYBALLOONSPEED = "二次元气球"

STRINGS.NAMES.TZ_ICEBALL = "雪球投掷游戏"
STRINGS.RECIPE_DESC.TZ_ICEBALL = "来打雪仗吧！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_ICEBALL = "看看哪个憨批被冻住了"

STRINGS.NAMES.TZXX_MNQ = "嗷石"
STRINGS.RECIPE_DESC.TZXX_MNQ = "要睡觉的都出去，我要修仙了！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZXX_MNQ = "灵狐人开启修炼之路的神石"

STRINGS.NAMES.TZ_LING_SMALL = "赎灵"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_LING_SMALL = "生物被灵狐族极限秘术救赎后的产物"

STRINGS.NAMES.TZ_LING_NOLMAL = "赎灵"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_LING_NOLMAL = "生物被灵狐族极限秘术救赎后的产物"

STRINGS.NAMES.TZ_LING_BIG = "赎灵"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_LING_BIG = "生物被灵狐族极限秘术救赎后的产物"

STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.TZ_XX_MNQ = { NOXX = "已经开启修仙之路了"}

STRINGS.NAMES.TZ_ELONG_BOX = "饿龙幼崽"
STRINGS.RECIPE_DESC.TZ_ELONG_BOX = "放心，它很听话，不会偷吃的"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_ELONG_BOX = "一口一个阿平酱！"

STRINGS.NAMES.TZ_FH_OWNERS = {
	PRE_INDEX = "眷属：",
}

STRINGS.NAMES.TZ_FHSPTS = "番号审判天使"
STRINGS.RECIPE_DESC.TZ_FHSPTS = "无所不能，舍弃情感，手持义理之人"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHSPTS = "我，作为御神座审判长，要对你实施审判"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHSPTS = "神御座审判长猫猫"

STRINGS.NAMES.TZ_FHZLZ = "番号再临者"
STRINGS.RECIPE_DESC.TZ_FHZLZ = "再次降临这个世界"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHZLZ = "世界寂灭，转世再临"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHZLZ = "沐还是云?"
STRINGS.ACTIONS.CASTAOE.TZ_FHZLZ = "咸鱼突刺"

STRINGS.NAMES.TZ_FHZC = "番号仲裁"
STRINGS.RECIPE_DESC.TZ_FHZC = "一剑霜寒十四州"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHZC = "四海八荒，为吾独尊"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHZC = "尘世闲游的仲裁者断弦"

STRINGS.NAMES.TZ_FHFT = "番号否天"
STRINGS.RECIPE_DESC.TZ_FHFT = "奉劝年轻人多嗷呜呜呜qaq"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHFT = "跳舞是有威力的！"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHFT = "小鳄鱼"

STRINGS.NAMES.TZ_FHFT_GIFT = "大魔王的青睐"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHFT_GIFT = "大魔王的青睐"

STRINGS.NAMES.TZ_FHBM = "番号薄暝"
STRINGS.RECIPE_DESC.TZ_FHBM = "我们终将战胜黄昏的黑暗，直面黎明的光辉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHBM = "我乃死，我乃生，我为暗，我亦为光"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHBM = "世界的调律者＊樱歌梦语"
STRINGS.ACTIONS.CASTAOE.TZ_FHBM = "瞬移"

STRINGS.NAMES.TZ_FHGX = "番号归墟"
STRINGS.RECIPE_DESC.TZ_FHGX = "有大壑焉，实惟无底之谷"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHGX = "其下无底，名曰归墟"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHGX = "归墟"

STRINGS.NAMES.TZ_FH_FISHGIRL = "番号鱼妞的眷恋"
STRINGS.RECIPE_DESC.TZ_FH_FISHGIRL = "思念是海的泡沫，无人知晓"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_FISHGIRL = "我为何对你如此迷恋"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_FISHGIRL = "lucky鱼仔"

STRINGS.NAMES.TZ_FH_NX = "番号凝心"
STRINGS.RECIPE_DESC.TZ_FH_NX = "皓月清凉，山河过往。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_NX = "唯你是青山、是琳琅、是独绝。"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_NX = "麻酱"

STRINGS.NAMES.TZ_FH_HF = "番号化凡"
STRINGS.RECIPE_DESC.TZ_FH_HF = "此番执念，只为相见"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_HF = "回首凡尘不做仙"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_HF = "依山"

STRINGS.NAMES.TZ_FH_LY = "番号两仪"
STRINGS.RECIPE_DESC.TZ_FH_LY = "?¿?......!"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_LY = "饿死了，这个能吃吗......好硬，好苦"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_LY = "Schleim"

STRINGS.NAMES.TZ_FH_NS = "番号海洋女神的祝福"
STRINGS.RECIPE_DESC.TZ_FH_NS = "钦慕之人赠送的命运信物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_NS = "蕴藏着强大的魔法"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_NS = "空空"

STRINGS.NAMES.TZ_FHDX = "番号谪仙"
STRINGS.RECIPE_DESC.TZ_FHDX = "仙气凝三岭，和风扇八荒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHDX = "仙气凝三岭，和风扇八荒"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHDX = "天命大大"

STRINGS.NAMES.TZ_FHYM = "番号夜幕"
STRINGS.RECIPE_DESC.TZ_FHYM = "夜幕所至，诸神黄昏"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHYM = "夜幕降临"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHYM = "际遇"

STRINGS.NAMES.TZ_FH_YS = "番号忆思"
STRINGS.RECIPE_DESC.TZ_FH_YS = "我曾发誓要保护她，成为她的翼，即使没有契约，这份誓约也不会改变。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_YS = "我已习惯每个傍晚去想她。"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_YS = "胖虎酱c"

STRINGS.NAMES.TZ_FHMT = "番号魔饕"
STRINGS.NAMES.TZ_FHMT_BUFF = "魔饕"
STRINGS.RECIPE_DESC.TZ_FHMT = "笑嗷八荒，食遍四海"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FHMT = "唯有美食不可辜负！"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FHMT = "知非"

STRINGS.NAMES.TZ_FH_YOU = "番号游"
STRINGS.RECIPE_DESC.TZ_FH_YOU = ""
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_YOU = "你还在，是吗?"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_YOU = "Jerry"

STRINGS.NAMES.TZ_FH_ML = "番号魔临"
STRINGS.RECIPE_DESC.TZ_FH_ML = "此身之劫 沉珂经年"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_ML = "宁为玉碎 不为瓦全"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_ML = "阿平从小就很可爱"

STRINGS.NAMES.TZ_FH_JHZ = "番号汲魂者"
STRINGS.RECIPE_DESC.TZ_FH_JHZ = "独挂饰盎然，万劫亦重生。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_JHZ = "历战的智慧。"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_JHZ = "雾雨爱丽丝"

STRINGS.NAMES.TZ_FH_XHWS = "番号羲和望舒"
STRINGS.RECIPE_DESC.TZ_FH_XHWS = "琼华铸剑长老一脉历经三代，集天地奇珍、耗毕生心血铸成。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_XHWS = "琼华白日飞升，真乃灵狐修仙利器。"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_XHWS = "Royian"

STRINGS.NAMES.TZ_FH_FL = "番号风雷"
STRINGS.RECIPE_DESC.TZ_FH_FL = "同时拥有风与电的力量，但是看起来有点透风"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_FL = "透风了"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_FL = "红茶加冰"

STRINGS.NAMES.TZ_FH_HT = "番号黑天"
STRINGS.RECIPE_DESC.TZ_FH_HT = "小心被黑暗的力量吞噬"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FH_HT = "可不能让叮铃知道。"
STRINGS.NAMES.TZ_FH_OWNERS.TZ_FH_HT = "文"
----------------------
STRINGS.NAMES.TAIZHEN = "太真"
STRINGS.CHARACTER_TITLES.taizhen = "灵狐傀儡师太真"
STRINGS.CHARACTER_NAMES.taizhen = "太真"
STRINGS.CHARACTER_DESCRIPTIONS.taizhen = "*是一只可爱的灵狐\n*噩梦燃料对他来说很重要 \n*受到撒嘛坂町的庇护"
STRINGS.CHARACTER_QUOTES.taizhen = "\"主人会让太真一直陪在身边吗？\""

STRINGS.NAMES.TZ_SPIRITUALISM = "三元勾玉拨浪鼓"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_SPIRITUALISM = "咚咚咚！"

STRINGS.NAMES.TZ_MALIBAG = "麻哩麻哩包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_MALIBAG = "嘛哩嘛哩哄！"

STRINGS.NAMES.TZ_ENCHANTER = "番号盛宴"
STRINGS.RECIPE_DESC.TZ_ENCHANTER = "能够呼唤暗影生物的神奇法器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_ENCHANTER = "尾气超标"
--change 2019-05-15 
STRINGS.NAMES.TZ_ENCHANTER_YELLOW = "番号盛宴-饿龙"
STRINGS.RECIPE_DESC.TZ_ENCHANTER_YELLOW = "能够呼唤暗影生物的神奇法器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_ENCHANTER_YELLOW = "尾气超标"
--change 
STRINGS.NAMES.TZ_YEXINGZHE = "番号月蚀"
STRINGS.RECIPE_DESC.TZ_YEXINGZHE = "兼顾防守的作战道具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_YEXINGZHE = "掌控光和影的强大武器！"

STRINGS.NAMES.TZ_YEXINGZHE_PURPLE = "番号月蚀•大帝机神霸王"
STRINGS.RECIPE_DESC.TZ_YEXINGZHE_PURPLE = "合体！我们是光的英雄！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_YEXINGZHE_PURPLE = "合体！我们是光的英雄！"

STRINGS.NAMES.TZ_YEZHAO = "番号照夜"
STRINGS.RECIPE_DESC.TZ_YEZHAO = "法力无边的暗影器具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_YEZHAO = "第二个月亮"

STRINGS.NAMES.TZ_YEZHAO_PINK = "番号照夜•爱神"
STRINGS.RECIPE_DESC.TZ_YEZHAO_PINK = "番号照夜•爱神"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_YEZHAO_PINK = "爱心~爱心~"

STRINGS.NAMES.LOSTCHESTER_BUILDER = "暗影贮藏者"
STRINGS.RECIPE_DESC.LOSTCHESTER_BUILDER = "聘请一位拎包的人也不错"
STRINGS.NAMES.LOSTCHESTER = "暗影贮藏者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOSTCHESTER = "你的包包能够再大一点儿吗"
STRINGS.NAMES.LOSTCHESTER_GAI = "暗影搬运者"
STRINGS.NAMES.LOSTCHESTER_GAI_BUILDER = STRINGS.NAMES.LOSTCHESTER_GAI
STRINGS.RECIPE_DESC.LOSTCHESTER_GAI_BUILDER = "需要撒麻值上限大于400"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOSTCHESTER_GAI = "太真也要变成闪电侠！"

STRINGS.NAMES.LOSTUMBRELLA_BUILDER= "暗影保护者"
STRINGS.RECIPE_DESC.LOSTUMBRELLA_BUILDER = "少晒太阳，让自己变白一点"
STRINGS.NAMES.LOSTUMBRELLA= "暗影保护者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOSTUMBRELLA = "影子做的伞可以防雨吗"
STRINGS.NAMES.LOSTUMBRELLA_GAI= "暗影警示者"
STRINGS.NAMES.LOSTUMBRELLA_GAI_BUILDER = STRINGS.NAMES.LOSTUMBRELLA_GAI
STRINGS.RECIPE_DESC.LOSTUMBRELLA_GAI_BUILDER = "需要撒麻值上限大于400"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOSTUMBRELLA_GAI = "真香警告！"

STRINGS.NAMES.LOSTEARTH_BUILDER = "暗影释放者"
STRINGS.RECIPE_DESC.LOSTEARTH_BUILDER = "长夜漫漫，总会有人引路的"
STRINGS.NAMES.LOSTEARTH = "暗影释放者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOSTEARTH = "红红火火恍恍惚惚"
STRINGS.NAMES.LOSTEARTH_GAI = "暗影摆渡者"
STRINGS.NAMES.LOSTEARTH_GAI_BUILDER = STRINGS.NAMES.LOSTEARTH_GAI
STRINGS.RECIPE_DESC.LOSTEARTH_GAI_BUILDER = "需要撒麻值上限大于400"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOSTEARTH_GAI = "快看看收集了多少灵魂"

STRINGS.NAMES.LOSTFIGHT_BUILDER = "暗影投射者"
STRINGS.RECIPE_DESC.LOSTFIGHT_BUILDER = "奢侈的暗影盛宴！"
STRINGS.NAMES.LOSTFIGHT= "暗影投射者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOSTFIGHT = "蕴含巨大的暗影能量"
STRINGS.NAMES.LOSTFIGHT_GAI= "暗影驱逐者"
STRINGS.NAMES.LOSTFIGHT_GAI_BUILDER = STRINGS.NAMES.LOSTFIGHT_GAI
STRINGS.RECIPE_DESC.LOSTFIGHT_GAI_BUILDER = "需要撒麻值上限大于400"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LOSTFIGHT_GAI = "与我并肩作战"

STRINGS.NAMES.TZ_EVIL_TEACHER = "邪心教典【织影】"
STRINGS.RECIPE_DESC.TZ_EVIL_TEACHER = "真想看看Mr.Dark写的原作"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_EVIL_TEACHER = "根据《邪心教典》改编的一系列书籍"

STRINGS.NAMES.TZ_EVIL_TEACHER_SUPER = "邪心教典超越之书"
STRINGS.RECIPE_DESC.TZ_EVIL_TEACHER_SUPER = "邪心教典超越之书"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_EVIL_TEACHER_SUPER = "邪心教典超越之书"

STRINGS.NAMES.TZ_BOOK_SURPASSING = "邪心教典超越之书"
STRINGS.RECIPE_DESC.TZ_BOOK_SURPASSING = "邪心教典超越之书"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_BOOK_SURPASSING = "邪心教典超越之书"

STRINGS.NAMES.TZ_NIGHTMARE1 = "爬行小影怪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_NIGHTMARE1 = "服从于我吧！"

STRINGS.NAMES.TZ_NIGHTMARE2 = "尖喙小影怪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_NIGHTMARE2 = "服从于我吧！"


STRINGS.NAMES.TZ_CREATURE1 = "梦噬怪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_CREATURE1 = "服从于我吧！"

STRINGS.NAMES.TZ_CREATURE2 = "梦魇怪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_CREATURE2 = "服从于我吧！"

STRINGS.NAMES.PANGBALLOONS_EMPTY = "胖白熊星朵"
STRINGS.RECIPE_DESC.PANGBALLOONS_EMPTY = "能吹出发出彩光的熊型外观气球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PANGBALLOONS_EMPTY = "一起来吹气球吧！"

STRINGS.NAMES.TZ_LONGYA = "龙牙"
STRINGS.RECIPE_DESC.TZ_LONGYA = "锋利的骨牙所制，有极高的攻击力"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_LONGYA = "恐龙的利牙！"

STRINGS.NAMES.TZ_LUOBOSTAFF = "萝卜即正义"
STRINGS.RECIPE_DESC.TZ_LUOBOSTAFF = "突如其来的正义让人惊喜不已"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_LUOBOSTAFF = "正义是什么，能吃吗？"

STRINGS.NAMES.TZ_LIANG = "恐吓加热炉"
STRINGS.RECIPE_DESC.TZ_LIANG = "别老露出一副要吃人的样子！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_LIANG = "吼吼吼！"

STRINGS.NAMES.TURF_TZTURFA = "兔毛地毯"
STRINGS.RECIPE_DESC.TURF_TZTURFA = "软软的哟"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TZTURFA = "兔叽什么的最可爱啦"

STRINGS.NAMES.TZ_SPEAR = "威尔逊武器"
STRINGS.RECIPE_DESC.TZ_SPEAR = "拿人打架是什么样的体验？"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_SPEAR = "你还好吗？"

STRINGS.NAMES.TZ_WHITEWING = "守护之翼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_WHITEWING = "来自蜂女王的守护"

STRINGS.NAMES.TZ_DELIVERY = "蜗牛的微型时空"
STRINGS.RECIPE_DESC.TZ_DELIVERY = "已经无法用科学来解释"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_DELIVERY = "下一站会是哪儿呢"

STRINGS.NAMES.TZ_PACKBOX = "超级包裹"
STRINGS.RECIPE_DESC.TZ_PACKBOX = "搬家拆家，必备神器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_PACKBOX = "能装下一个世界吗？"

STRINGS.NAMES.TZ_ICESWORD = "图勒凛风"
STRINGS.RECIPE_DESC.TZ_ICESWORD = "光拿着就能感受到刺骨的寒冷"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_ICESWORD = "好冷！"

STRINGS.NAMES.TZ_FIRESWORD = "图勒热火"
STRINGS.RECIPE_DESC.TZ_FIRESWORD = "岩浆一般炎热！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FIRESWORD = "真烫手！"

STRINGS.NAMES.TZ_TFSWORD = "讨伐大剑"
STRINGS.RECIPE_DESC.TZ_TFSWORD = "快人一步"--"强者才能驾驭它的力量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_TFSWORD = "给自身灌注远古的暗影力量"

STRINGS.NAMES.TZ_CANNEDTNT = "化学饮料"
STRINGS.RECIPE_DESC.TZ_CANNEDTNT = "喝前摇一摇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_CANNEDTNT= "是摇，还是不摇？"

STRINGS.NAMES.TZ_MIEMIEBACK = "小羊背包"
STRINGS.RECIPE_DESC.TZ_MIEMIEBACK = "可爱的小羊背包"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_MIEMIEBACK = "咩咩咩"

STRINGS.NAMES.TZ_SWORDCEMETERY = "受侵蚀的神秘祭坛"
STRINGS.RECIPE_DESC.TZ_SWORDCEMETERY = "它解开了更强大的力量"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_SWORDCEMETERY = "这是什么植物"

STRINGS.NAMES.TAIZHEN_COSPLAYBLUE = "葬爱小学时装包"
STRINGS.RECIPE_DESC.TAIZHEN_COSPLAYBLUE = "氪金，使你变得更强！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAIZHEN_COSPLAYBLUE = "杀马特家族"

STRINGS.NAMES.TAIZHEN_COSPLAYYELLOW = "饿龙时装包"
STRINGS.RECIPE_DESC.TAIZHEN_COSPLAYYELLOW = "氪金，使你变得更强！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAIZHEN_COSPLAYYELLOW = "嗷～嗷!"
--change 2019-05-16
STRINGS.NAMES.TAIZHEN_COSPLAYYELLOWPRO = "饿龙时装包Pro版"
STRINGS.RECIPE_DESC.TAIZHEN_COSPLAYYELLOWPRO = "氪金，使你变得更强！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAIZHEN_COSPLAYYELLOWPRO = "大恐龙！"


STRINGS.NAMES.TAIZHEN_COSPLAYPINK = "爱神时装包"
STRINGS.RECIPE_DESC.TAIZHEN_COSPLAYPINK = "氪金，使你变得更强！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAIZHEN_COSPLAYPINK = "裙子一穿，粉毛一戴，太真是女孩子"

STRINGS.NAMES.TAIZHEN_COSPLAYPURPLE = "机神时装包"
STRINGS.RECIPE_DESC.TAIZHEN_COSPLAYPURPLE = "氪金，使你变得更强！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAIZHEN_COSPLAYPURPLE = "去称霸宇宙吧！"

STRINGS.NAMES.TZ_DARK_COOKPOT = "超越：暗影釜"
STRINGS.RECIPE_DESC.TZ_DARK_COOKPOT = "这是超越：暗影釜！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_DARK_COOKPOT = "这是超越：暗影釜！"

--change
STRINGS.NAMES.TAIZHEN_COSPLAYBLACK = "逐暗浪客时装包"
STRINGS.RECIPE_DESC.TAIZHEN_COSPLAYBLACK = "氪金，使你变得更强！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAIZHEN_COSPLAYBLACK = "释放强大的暗影能量吧！"

STRINGS.NAMES.TZ_STAFF = "替身布偶"
STRINGS.RECIPE_DESC.TZ_STAFF = "难逃不了挨揍的命运"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_STAFF = "需要太真也给主人做一个吗？"

STRINGS.NAMES.TZ_TUJI = "维森莫·拉莫帅"
STRINGS.RECIPE_DESC.TZ_TUJI = "要多用微笑来面对生活"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_TUJI = "杰克已经走了，你现在的主人是我"

STRINGS.NAMES.TZ_MACHINE = "勇者斗恶龙"
STRINGS.RECIPE_DESC.TZ_MACHINE = "勇敢者的游戏第一代"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_MACHINE = "石头做的龙没什么好怕的"

STRINGS.NAMES.TZ_PI = "MAX石质音响"
STRINGS.RECIPE_DESC.TZ_PI = "MAX高音质，你值得拥有"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_PI = "哥是江南style"

STRINGS.NAMES.TZ_FEIDIE = "来自火星"
STRINGS.RECIPE_DESC.TZ_FEIDIE = "氪金，使你变得更强！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_FEIDIE = "远方来的朋友，火星的风景好吗？"

STRINGS.NAMES.TZ_CD1 = "碟片"
STRINGS.RECIPE_DESC.TZ_CD1 = "彩虹原声经典音乐，如临仙境"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_CD1 = "可以吃吗"

STRINGS.NAMES.TZ_KJBOOK = "在恐惧之上"
STRINGS.RECIPE_DESC.TZ_KJBOOK = "呼唤黑暗深渊的邪恶生物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_KJBOOK = "可怕~"

STRINGS.NAMES.TZ_TENTACLE = "暗影触手"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_TENTACLE = "那是来自深渊的朋友"

STRINGS.NAMES.TZ_DEATHBOOK = "邪心教典【魇】"
STRINGS.RECIPE_DESC.TZ_DEATHBOOK = "一本不时发出哀嚎声的书"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_DEATHBOOK = "主人快让太真阅读这本书吧！"

STRINGS.NAMES.TZ_IMAGE= "替身人偶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_IMAGE = "那货不是太真"

STRINGS.NAMES.TZ_UNKNOWM = "未知物品δ"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_UNKNOWM = "肉体就算风干，灵魂也不会枯萎"

STRINGS.NAMES.TZ_UNKNOWN = "未知物品λ "
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_UNKNOWN = "快快把这做成书籍"

STRINGS.NAMES.TZ_UNKNOWF = "未知物品β"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_UNKNOWF = "由火红的灵魂铸造"

STRINGS.NAMES.TZ_WAFERCHOCOLATE = "非常粮食"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_WAFERCHOCOLATE = "横扫饥饿!"

STRINGS.NAMES.TZ_ICECREAM = "奇异甜食"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_ICECREAM = "那么大甜筒!"

STRINGS.NAMES.TZ_LUOBO = "大萝卜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_LUOBO = "你好，萝卜先生!"

STRINGS.NAMES.DOYDOYSAMA = "撒麻坂町拟化状态"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DOYDOYSAMA = "那是我内心的独白！"
STRINGS.NAMES.SHARKITTENSAMA = "撒麻坂町拟化状态"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHARKITTENSAMA = "那是我内心的独白！"
STRINGS.NAMES.CRABSAMA = "撒麻坂町拟化状态"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CRABSAMA = "那是我内心的独白！"
STRINGS.NAMES.CROCODOGSAMA = "撒麻坂町拟化状态"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CROCODOGSAMA = "那是我内心的独白！"

STRINGS.NAMES.TZ_UNKNOWK = "未知物品α"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_UNKNOWK = "凝聚了寒冰的灵魂"

STRINGS.NAMES.PANGBAIXIONG = "胖白熊"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PANGBAIXIONG = "大白熊，白又白"


STRINGS.NAMES.QDPANGBAIXIONG = "庆典气球"
STRINGS.RECIPE_DESC.QDPANGBAIXIONG = "举行庆典用的巨大彩色气球"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.QDPANGBAIXIONG = "上次在奥兹曼市举行庆典时买的"

STRINGS.NAMES.TZ_DOUBLES = "转生布偶"
STRINGS.RECIPE_DESC.TZ_DOUBLES = "多给自己一次机会"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_DOUBLES = "再也不怕翻车啦！"


STRINGS.NAMES.TZ_PILLS = "大进化药"
STRINGS.RECIPE_DESC.TZ_PILLS = "强效药物，谨慎使用！"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_PILLS = "天哪，要吃药吗..."

STRINGS.NAMES.TZ_YANJING = "太阳镜"
STRINGS.RECIPE_DESC.TZ_YANJING = "时尚的眼镜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_YANJING = "这能挡光吗？！"


STRINGS.NAMES.TZ_PYTHON_SUMMON_ROCKET = "盖亚：和平祈愿星"
STRINGS.RECIPE_DESC.TZ_PYTHON_SUMMON_ROCKET = "盖亚：和平祈愿星"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_PYTHON_SUMMON_ROCKET = "盖亚：和平祈愿星"

STRINGS.NAMES.TZ_PYTHON_SUMMON_FALLEN = "帝王承载器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_PYTHON_SUMMON_FALLEN = "帝王承载器"

STRINGS.NAMES.TZ_PUGALISK = "泰西欧斯：机神"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_PUGALISK = "我们真的能打败它吗？"

STRINGS.NAMES.TZ_PUGALISK_CRYSTAL = "帝王结晶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_PUGALISK_CRYSTAL = "帝王结晶"


STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.BUILD.HASLOSY= "人偶已达到上限"
STRINGS.CHARACTERS.GENERIC.ACTIONFAIL.WONIUTELESCROLL={
										HASCHUANSONGCD = "暂时好像不能使用",
										}

STRINGS.PEIFANGEVIL = "邪心教义"
STRINGS.PEIFANGMENG = "太真太真"
STRINGS.PEIFANGJIAN = "神秘祭坛"
STRINGS.TZRENZHEN ="认真系列"
STRINGS.XIAOGUSHIFA = "施法"
STRINGS.PANGBAIXIONGCHUI = "吹"
STRINGS.WUNIUCHUANSONG = "传送"
STRINGS.TZDABAOWEIZHI = "未知的打包物体"
STRINGS.TZPACK = "打包"
STRINGS.TZUNPACK = "拆开"
STRINGS.TZICESWORD = "修复"
STRINGS.TZTNTER = "摇一摇"
STRINGS.TZCOSPLAY = "换装"
STRINGS.TZSTAFF = "施法"
STRINGS.TZBLINK = "移行"
STRINGS.TZREAD = "阅读"
STRINGS.TZTURNON ="套住"
STRINGS.TZTURNOFF = "松开"
STRINGS.TZ_YEXINGCHA = "插座"
STRINGS.NOYEXINGZHE = "黑影的力量使我感到恐惧"
STRINGS.LUOBO7 = "女士们，先生们"
STRINGS.LUOBO6 = "很高兴见到各位"
STRINGS.LUOBO5 = "下面开始爆炸倒计时"
STRINGS.LUOBO4 = "五"
STRINGS.LUOBO3 = "四"
STRINGS.LUOBO2 = "一"
STRINGS.LUOBO1 = "再见"
STRINGS.TZCASTAOE = "分身斩"
STRINGS.CHARACTERS.TAIZHEN = require "speech_taizhen"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TAIZHEN = 
{
	GENERIC = "快过来让我捏捏你的小肥脸！",
	ATTACKER = "送你上西天.",
	MURDERER = "拜拜咯～",
	REVIVER = "略略略",
	GHOST = "叫大哥就给你复活",
}

STRINGS.NAMES.QIMOGE = "小丑兔奇莫格"
STRINGS.RECIPE_DESC.QIMOGE = "你会照顾它吗"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.QIMOGE = "是一只被主人丢弃的兔子"

STRINGS.NAMES.TURF_TZ_DRAGONFLOOR = "龙图腾地毯"
STRINGS.RECIPE_DESC.TURF_TZ_DRAGONFLOOR = "刻有龙纹章的地毯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_TZ_DRAGONFLOOR = "中国风的地毯"

STRINGS.RECIPE_DESC.ITEM_FANTA_BLADE = "使用后领悟技能【幻影剑舞】"

STRINGS.SKIN_NAMES.taizhen_none = "太真"
STRINGS.SKIN_DESCRIPTIONS.taizhen_none	= "一只可爱的灵狐"
STRINGS.SKIN_NAMES.taizhen_pink_none = "三周年贺岁"
STRINGS.SKIN_NAMES.taizhen_boying_none = "薄樱"
STRINGS.SKIN_DESCRIPTIONS.taizhen_pink_none = "感谢大家的陪伴，太真已经三岁了！"
STRINGS.SKIN_DESCRIPTIONS.taizhen_boying_none = "去年樱花盛开的地方，太真在那等主人回来"


STRINGS.NAMES.TZ_PING_CANDY = "阿平糖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TZ_PING_CANDY = "我还会回来的！"

