-- Multi-player Only
name = "Magic Torch"

description = "This Mod adds a magical multi-functional torch item to DST. Create the torch and then add any coloured gem for different results." 

author = "Jack with cameos by Cheese"

version = "7.2"

api_version_dst = 10
dst_compatible = true
all_clients_require_mod = true

icon_atlas = "nightmareitems.xml"
icon = "nightmareitems.tex"

forumthread = ""

server_filter_tags = {
"nightmare",
}

configuration_options = 
{
	{
		name="MagicTorch_Difficulty",
		label="Magic Torch Recipe Difficulty",
		hover = "Crafting recipe difficulty levels.",
		options = {
			{data="super_easy",description="Super Easy",
			   hover = "1 Living Log"},
			{data="easy",description="Easy",
			   hover = "1 Living Log, 1 Nightmare Fuel"},
			{data="default",description="Default",
			   hover = "1 Living Log, 3 Nightmare Fuel, 2 Gold Nuggets"},
			{data="hard",description="Hard",
			   hover = "2 Living Logs, 5 Nightmare Fuel, 1 Red Gem (Prestihatitator)"},
		},
		default="default",
	},
    --gems
	{
		name="yellowgemrange",
		label="Yellow Gem Range",
		hover = "The range the yellow gem in a torch can find targets.",
		options = {
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
			{data=4,description="4"},
			{data=5,description="5"},
			{data=6,description="6"},
			{data=7,description="7"},
			{data=8,description="8"},
			{data=9,description="9"},
			{data=10,description="10"},
			{data=11,description="11"},
			{data=12,description="12"},
			{data=13,description="13"},
			{data=14,description="14"},
			{data=15,description="15"},
			{data=16,description="16"},
			{data=17,description="17"},
			{data=18,description="18"},
			{data=19,description="19"},
			{data=20,description="20"},
			{data=21,description="21"},
			{data=22,description="22"},
			{data=23,description="23"},
			{data=24,description="25"},
			{data=25,description="25"},
			{data=26,description="26"},
			{data=27,description="27"},
			{data=28,description="28"},
			{data=29,description="29"},
			{data=30,description="30"},
			{data=40,description="40"},
			{data=50,description="50"},
			{data=70,description="70"},
			{data=90,description="90"},
		},
		default=15,
	},
	{
		name="yellowgemdamage",
		label="Yellow Gem Damage",
		hover = "The damage output of the yellow gem.",
		options = {
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
			{data=4,description="4"},
			{data=5,description="5"},
			{data=6,description="6"},
			{data=7,description="7"},
			{data=8,description="8"},
			{data=9,description="9"},
			{data=10,description="10"},
			{data=15,description="15"},
			{data=16,description="16"},
			{data=17,description="17"},
			{data=20,description="20"},
			{data=25,description="25"},
			{data=30,description="30"},
			{data=35,description="35"},
			{data=40,description="40"},
			{data=45,description="45"},
			{data=50,description="50"},
			{data=55,description="55"},
			{data=60,description="60"},
			{data=65,description="65"},
			{data=70,description="70"},
			{data=75,description="75"},
			{data=80,description="80"},
			{data=85,description="85"},
			{data=90,description="90"},
			{data=95,description="95"},
			{data=100,description="100"},
			{data=110,description="110"},
			{data=115,description="115"},
			{data=120,description="120"},
			{data=125,description="125"},
			{data=150,description="150"},
			{data=200,description="200"},
			{data=250,description="250"},
			{data=300,description="300"},
		},
		default=25,
	},
	{
		name="yellowgemrof",
		label="Yellow Gem Rate of Fire",
		hover = "The rate at which the yellow gem fires its projectiles.",
		options = {
			{data=.1,description="0.1"},
			{data=.2,description="0.2"},
			{data=.3,description="0.3"},
			{data=.4,description="0.4"},
			{data=.5,description="0.5"},
			{data=.6,description="0.6"},
			{data=.7,description="0.7"},
			{data=.8,description="0.8"},
			{data=.9,description="0.9"},
			{data=1,description="1"},
			{data=1.5,description="1.5"},
			{data=2,description="2"},
		},
		default=.5,
	},
	--purp
	{
		name="purplegemrange",
		label="Purple Gem Range",
		hover = "The range the purple gem in a torch can find targets.",
		options = {
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
			{data=4,description="4"},
			{data=5,description="5"},
			{data=6,description="6"},
			{data=7,description="7"},
			{data=8,description="8"},
			{data=9,description="9"},
			{data=10,description="10"},
			{data=11,description="11"},
			{data=12,description="12"},
			{data=13,description="13"},
			{data=14,description="14"},
			{data=15,description="15"},
			{data=16,description="16"},
			{data=17,description="17"},
			{data=18,description="18"},
			{data=19,description="19"},
			{data=20,description="20"},
			{data=21,description="21"},
			{data=22,description="22"},
			{data=23,description="23"},
			{data=24,description="25"},
			{data=25,description="25"},
			{data=26,description="26"},
			{data=27,description="27"},
			{data=28,description="28"},
			{data=29,description="29"},
			{data=30,description="30"},
			{data=40,description="40"},
			{data=50,description="50"},
			{data=70,description="70"},
			{data=90,description="90"},
		},
		default=15,
	},
	{
		name="purplegemdamage",
		label="Purple Gem Damage",
		hover = "The damage output of the purple gem.",
		options = {
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
			{data=4,description="4"},
			{data=5,description="5"},
			{data=6,description="6"},
			{data=7,description="7"},
			{data=8,description="8"},
			{data=9,description="9"},
			{data=10,description="10"},
			{data=15,description="15"},
			{data=16,description="16"},
			{data=17,description="17"},
			{data=20,description="20"},
			{data=25,description="25"},
			{data=30,description="30"},
			{data=35,description="35"},
			{data=40,description="40"},
			{data=45,description="45"},
			{data=50,description="50"},
			{data=55,description="55"},
			{data=60,description="60"},
			{data=65,description="65"},
			{data=70,description="70"},
			{data=75,description="75"},
			{data=80,description="80"},
			{data=85,description="85"},
			{data=90,description="90"},
			{data=95,description="95"},
			{data=100,description="100"},
			{data=110,description="110"},
			{data=115,description="115"},
			{data=120,description="120"},
			{data=125,description="125"},
			{data=150,description="150"},
			{data=200,description="200"},
			{data=250,description="250"},
			{data=300,description="300"},
		},
		default=3,
	},
	{
		name="purplegemrof",
		label="Purple Gem Rate of Fire",
		hover = "The rate at which the purple gem fires its projectiles.",
		options = {
			{data=.1,description="0.1"},
			{data=.2,description="0.2"},
			{data=.3,description="0.3"},
			{data=.4,description="0.4"},
			{data=.5,description="0.5"},
			{data=.6,description="0.6"},
			{data=.7,description="0.7"},
			{data=.8,description="0.8"},
			{data=.9,description="0.9"},
			{data=1,description="1"},
			{data=1.5,description="1.5"},
			{data=2,description="2"},
		},
		default=.1,
	},
	{
		name="purplegemfr",
		label="Purple Gem Fuel Useage Rate",
		hover = "The number of units the purple gem uses as fuel: (Unit) of fuel per second.",
		options = {
			{data=0,description="0"},
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
		},
		default=2,
	},
	--orange
	{
		name="orangegemcd",
		label="Orange Gem Cool Down Time",
		hover = "The time, in seconds, after harvesting before the trap is ready again.",
		options = {
			{data=0,description="0"},
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
			{data=4,description="4"},
			{data=5,description="5"},
			{data=6,description="6"},
			{data=7,description="7"},
			{data=8,description="8"},
			{data=9,description="9"},
			{data=10,description="10"},
		},
		default=10,
	},
	--opal
	{
		name="opalgemrange",
		label="Iridescent Gem Range",
		hover = "The range the Iridescent gem in a torch can find targets.",
		options = {
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
			{data=4,description="4"},
		        {data=5,description="5"},
			{data=6,description="6"},
		        {data=7,description="7"},
			{data=8,description="8"},
			{data=9,description="9"},
			{data=10,description="10"},
			{data=11,description="11"},
		        {data=12,description="12"},
			{data=13,description="13"},
			{data=14,description="14"},
			{data=15,description="15"},
			{data=16,description="16"},
			{data=17,description="17"},
			{data=18,description="18"},
			{data=19,description="19"},
			{data=20,description="20"},
			{data=21,description="21"},
			{data=22,description="22"},
			{data=23,description="23"},
			{data=24,description="25"},
			{data=25,description="25"},
			{data=26,description="26"},
			{data=27,description="27"},
			{data=28,description="28"},
			{data=29,description="29"},
			{data=30,description="30"},
			{data=40,description="40"},
			{data=50,description="50"},
			{data=70,description="70"},
			{data=90,description="90"},
		},
		default=15,
	},
	{
		name="opalgemdamage",
		label="Iridescent Gem Damage",
		hover = "The damage output of the iridescent gem.",
		options = {
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
			{data=4,description="4"},
			{data=5,description="5"},
			{data=6,description="6"},
			{data=7,description="7"},
			{data=8,description="8"},
			{data=9,description="9"},
			{data=10,description="10"},
			{data=15,description="15"},
			{data=16,description="16"},
			{data=17,description="17"},
			{data=20,description="20"},
			{data=25,description="25"},
			{data=30,description="30"},
			{data=35,description="35"},
			{data=40,description="40"},
			{data=45,description="45"},
			{data=50,description="50"},
			{data=55,description="55"},
			{data=60,description="60"},
			{data=65,description="65"},
			{data=70,description="70"},
			{data=75,description="75"},
			{data=80,description="80"},
			{data=85,description="85"},
			{data=90,description="90"},
			{data=95,description="95"},
			{data=100,description="100"},
			{data=110,description="110"},
			{data=115,description="115"},
			{data=120,description="120"},
			{data=125,description="125"},
			{data=150,description="150"},
			{data=200,description="200"},
			{data=250,description="250"},
			{data=300,description="300"},
		},
		default=25,
	},
	{
		name="opalgemrof",
		label="Iridescent Gem Rate of Fire",
		hover = "The rate at which the Iridescent gem fires its projectiles.",
		options = {
			{data=.1,description="0.1"},
			{data=.2,description="0.2"},
			{data=.3,description="0.3"},
			{data=.4,description="0.4"},
			{data=.5,description="0.5"},
			{data=.6,description="0.6"},
			{data=.7,description="0.7"},
			{data=.8,description="0.8"},
			{data=.9,description="0.9"},
			{data=1,description="1"},
			{data=1.5,description="1.5"},
			{data=2,description="2"},
		},
		default=1,
	},
	--green
		{
		name="greengemlifetime",
		label="Green Gem Timer",
		hover = "How long the green gem's effect lasts.",
		options = {
			{data=1,description="1"},
			{data=2,description="2"},
			{data=3,description="3"},
			{data=4,description="4"},
			{data=5,description="5"},
			{data=6,description="6"},
			{data=7,description="7"},
			{data=8,description="8"},
			{data=9,description="9"},
			{data=10,description="10"},
			{data=15,description="15"},
			{data=16,description="16"},
			{data=17,description="17"},
			{data=20,description="20"},
			{data=25,description="25"},
			{data=30,description="30"},
			{data=35,description="35"},
			{data=40,description="40"},
			{data=45,description="45"},
			{data=50,description="50"},
			{data=55,description="55"},
			{data=60,description="60"},
			{data=65,description="65"},
			{data=70,description="70"},
			{data=75,description="75"},
			{data=80,description="80"},
			{data=85,description="85"},
			{data=90,description="90"},
			{data=95,description="95"},
			{data=100,description="100"},
			{data=110,description="110"},
			{data=115,description="115"},
			{data=120,description="120"},
		},
		default=30,
	},
}
