GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

modimport("scripts/recipes.lua")
modimport("scripts/scythe.lua")
modimport("scripts/DST Fish Farm.lua")
modimport("scripts/Slot Machine.lua")
modimport("scripts/mini tipi.lua")
modimport("scripts/Blood Bag.lua")
modimport("scripts/Some Buildings.lua")
modimport("scripts/Sword MOD for DST.lua")
modimport("scripts/Steampunk.lua")
modimport("scripts/Large Chest.lua")
modimport("scripts/Moar Metals.lua")
modimport("scripts/Waiter 101.lua")
modimport("scripts/Turfed.lua")
modimport("scripts/kyno_foodstrings.lua")
modimport("scripts/Felix.lua")
modimport("scripts/g10mm.lua")
modimport("scripts/Archery Mod.lua")
modimport("scripts/default item pack.lua")
modimport("scripts/Some Characters.lua")
